id r1.r2*TOPO(32) = +Num(1+u)*Den(2)*TOPO(32)*DD9+Num(m2-m2*u*z)*Den(2*z)*TOPO(32)*1;
id p1.r1*TOPO(32) = +1*Den(2)*TOPO(32)*DD5;
id p2.r1*TOPO(32) = +(-1)*Den(2)*TOPO(32)*DD5+Num(-1-u)*Den(2)*TOPO(32)*DD9+(-1)*Den(2)*TOPO(32)*DD13+Num(-m2+m2*z+m2*u*z)*Den(2*z)*TOPO(32)*1;
id p1.r2*TOPO(32) = +(-1)*Den(2)*TOPO(32)*DD5+Num(-u)*Den(2)*TOPO(32)*DD9+Num(-m2+m2*u*z)*Den(2*z)*TOPO(32)*1;
id p2.r2*TOPO(32) = +1*Den(2)*TOPO(32)*DD5+Num(u)*Den(2)*TOPO(32)*DD9+1*Den(2)*TOPO(32)*DD13+Num(-m2*u)*Den(2)*TOPO(32)*1;
