id r1.r2*TOPO(27) = +Num(1+u)*Den(2*u)*TOPO(27)*DD10+Num(m2*u-m2*z)*Den(2*u*z)*TOPO(27)*1;
id p1.r1*TOPO(27) = +(-1)*Den(2)*TOPO(27)*DD6+Num(-1-u)*Den(2*u)*TOPO(27)*DD10+(-1)*Den(2)*TOPO(27)*DD13+Num(m2*z-m2*u+m2*u*z)*Den(2*u*z)*TOPO(27)*1;
id p2.r1*TOPO(27) = +1*Den(2)*TOPO(27)*DD6;
id p1.r2*TOPO(27) = +1*Den(2)*TOPO(27)*DD6+1*Den(2*u)*TOPO(27)*DD10+1*Den(2)*TOPO(27)*DD13+Num(-m2)*Den(2*u)*TOPO(27)*1;
id p2.r2*TOPO(27) = +(-1)*Den(2)*TOPO(27)*DD6+(-1)*Den(2*u)*TOPO(27)*DD10+Num(m2*z-m2*u)*Den(2*u*z)*TOPO(27)*1;
