id r1.r2*TOPO(24) = +(-1)*Den(2)*TOPO(24)*DD12+(-1)*Den(2)*TOPO(24)*DD13+Num(m2+m2*z)*Den(2*z)*TOPO(24)*1;
id p1.r1*TOPO(24) = +(-1)*Den(2)*TOPO(24)*DD6+1*Den(2)*TOPO(24)*DD12+Num(-m2)*Den(2*z)*TOPO(24)*1;
id p2.r1*TOPO(24) = +1*Den(2)*TOPO(24)*DD6;
id p1.r2*TOPO(24) = +1*Den(2)*TOPO(24)*DD6+(-1)*Den(2+2*u)*TOPO(24)*DD12+Num(u)*Den(2+2*u)*TOPO(24)*DD13;
id p2.r2*TOPO(24) = +(-1)*Den(2)*TOPO(24)*DD6+1*Den(2+2*u)*TOPO(24)*DD12+1*Den(2+2*u)*TOPO(24)*DD13+Num(-m2)*Den(2*z)*TOPO(24)*1;
