id r1.r2*TOPO(33) = +Num(1+u)*Den(2)*TOPO(33)*DD9+Num(m2-m2*u*z)*Den(2*z)*TOPO(33)*1;
id p1.r1*TOPO(33) = +(-1)*Den(2)*TOPO(33)*DD7+Num(-u)*Den(2)*TOPO(33)*DD9+Num(-m2+m2*u*z)*Den(2*z)*TOPO(33)*1;
id p2.r1*TOPO(33) = +1*Den(2)*TOPO(33)*DD7+(-1)*Den(2)*TOPO(33)*DD9+(-1)*Den(2)*TOPO(33)*DD13+Num(m2)*Den(2)*TOPO(33)*1;
id p1.r2*TOPO(33) = +1*Den(2)*TOPO(33)*DD7;
id p2.r2*TOPO(33) = +(-1)*Den(2)*TOPO(33)*DD7+1*Den(2)*TOPO(33)*DD13+Num(-m2)*Den(2*z)*TOPO(33)*1;
