id r1.r2*TOPO(34) = +Num(1+u)*Den(2)*TOPO(34)*DD9+Num(m2-m2*u*z)*Den(2*z)*TOPO(34)*1;
id p1.r1*TOPO(34) = +1*Den(2)*TOPO(34)*DD8+Num(-u)*Den(2)*TOPO(34)*DD9+(-1)*Den(2)*TOPO(34)*DD13+Num(m2*u)*Den(2)*TOPO(34)*1;
id p2.r1*TOPO(34) = +(-1)*Den(2)*TOPO(34)*DD8+(-1)*Den(2)*TOPO(34)*DD9+Num(-m2+m2*z)*Den(2*z)*TOPO(34)*1;
id p1.r2*TOPO(34) = +(-1)*Den(2)*TOPO(34)*DD8+1*Den(2)*TOPO(34)*DD13+Num(-m2)*Den(2*z)*TOPO(34)*1;
id p2.r2*TOPO(34) = +1*Den(2)*TOPO(34)*DD8;
