id r1.r2*TOPO(22) = +Num(-1-u)*Den(2)*TOPO(22)*DD6+Num(-1-u)*Den(2)*TOPO(22)*DD8+Num(m2*z-m2*u)*Den(2*z)*TOPO(22)*1;
id p1.r1*TOPO(22) = +Num(u)*Den(2)*TOPO(22)*DD6+Num(1+u)*Den(2)*TOPO(22)*DD8+(-1)*Den(2)*TOPO(22)*DD13+Num(m2*u)*Den(2*z)*TOPO(22)*1;
id p2.r1*TOPO(22) = +1*Den(2)*TOPO(22)*DD6;
id p1.r2*TOPO(22) = +(-1)*Den(2)*TOPO(22)*DD8+1*Den(2)*TOPO(22)*DD13+Num(-m2)*Den(2*z)*TOPO(22)*1;
id p2.r2*TOPO(22) = +1*Den(2)*TOPO(22)*DD8;
