id r1.r2*TOPO(28) = +Num(1+u)*Den(2*u)*TOPO(28)*DD10+Num(m2*u-m2*z)*Den(2*u*z)*TOPO(28)*1;
id p1.r1*TOPO(28) = +(-1)*Den(2)*TOPO(28)*DD7+(-1)*Den(2)*TOPO(28)*DD10+Num(-m2+m2*z)*Den(2*z)*TOPO(28)*1;
id p2.r1*TOPO(28) = +1*Den(2)*TOPO(28)*DD7+(-1)*Den(2*u)*TOPO(28)*DD10+(-1)*Den(2)*TOPO(28)*DD13+Num(m2)*Den(2*u)*TOPO(28)*1;
id p1.r2*TOPO(28) = +1*Den(2)*TOPO(28)*DD7;
id p2.r2*TOPO(28) = +(-1)*Den(2)*TOPO(28)*DD7+1*Den(2)*TOPO(28)*DD13+Num(-m2)*Den(2*z)*TOPO(28)*1;
