L Had= - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*k1(mu95)
      *k1(nu95)*i_*gs^2*m2 + 2*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(
      ti)*cgv(tj)*k1(mu95)*k1(nu95)*i_*gs^2*d*m2 + 4*Prop(-k1)*Prop( - k1 + p1
      )*Prop( - k1 - p2)*gv(ti)*cgv(tj)*k1(mu95)*k1(nu95)*i_*gs^2*Nc^2*m2 - 2*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*k1(mu95)*
      k1(nu95)*i_*gs^2*Nc^2*d*m2 + 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - 
      p2)*gv(ti)*cgv(tj)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2 - 4*Prop(-k1)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*k1(mu95)*p1(nu95)*k1.p2*i_*
      gs^2*d - 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2 + 4*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*gv(ti)*cgv(tj)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2*d
       + 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*k1(mu95)
      *p2(nu95)*k1.p1*i_*gs^2 - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      gv(ti)*cgv(tj)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*d - 8*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2
      *Nc^2 + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2*d - 4*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*gv(ti)*cgv(tj)*k1(nu95)*p1(mu95)*i_*gs^2*m2 + 4*Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*k1(nu95)*p1(mu95)*
      i_*gs^2*Nc^2*m2 + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*
      cgv(tj)*k1(nu95)*p2(mu95)*i_*gs^2*m2 - 4*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*gv(ti)*cgv(tj)*k1(nu95)*p2(mu95)*i_*gs^2*Nc^2*m2 + 8*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*p1(mu95)*
      p1(nu95)*k1.p2*i_*gs^2 - 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      gv(ti)*cgv(tj)*p1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2 - 4*Prop(-k1)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*p1(mu95)*p2(nu95)*i_*gs^2*m2
       + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*p1(mu95)
      *p2(nu95)*i_*gs^2*Nc^2*m2 - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2
      )*gv(ti)*cgv(tj)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2 + 2*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2
      *d + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      p1(mu95)*p2(nu95)*k1.k1*i_*gs^2*Nc^2 - 2*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*gv(ti)*cgv(tj)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2*Nc^2*d
       + 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*p1(mu95)
      *p2(nu95)*k1.p2*i_*gs^2 - 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      gv(ti)*cgv(tj)*p1(mu95)*p2(nu95)*k1.p2*i_*gs^2*Nc^2 - 4*Prop(-k1)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*p1(nu95)*p2(mu95)*i_*gs^2*m2
       + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*p1(nu95)
      *p2(mu95)*i_*gs^2*Nc^2*m2 - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2
      )*gv(ti)*cgv(tj)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2 + 2*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2
      *d + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*Nc^2 - 2*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*gv(ti)*cgv(tj)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*Nc^2*d
       - 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*p1(nu95)
      *p2(mu95)*k1.p1*i_*gs^2 + 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      gv(ti)*cgv(tj)*p1(nu95)*p2(mu95)*k1.p1*i_*gs^2*Nc^2 - 8*Prop(-k1)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*p2(mu95)*p2(nu95)*k1.p1*i_*
      gs^2 + 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      p2(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2 + 2*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*gv(ti)*cgv(tj)*d_(mu95,nu95)*i_*gs^2*m2^2 - 2*Prop(-k1)
      *Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*d_(mu95,nu95)*i_*gs^2*
      Nc^2*m2^2 + 2*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)
      *d_(mu95,nu95)*k1.k1*i_*gs^2*m2 - Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*gv(ti)*cgv(tj)*d_(mu95,nu95)*k1.k1*i_*gs^2*d*m2 - 2*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*d_(mu95,nu95)*k1.k1*i_*
      gs^2*Nc^2*m2 + Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj
      )*d_(mu95,nu95)*k1.k1*i_*gs^2*Nc^2*d*m2 + 4*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*gv(ti)*cgv(tj)*d_(mu95,nu95)*k1.p1*i_*gs^2*m2 - 4*Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*d_(mu95,nu95)*
      k1.p1*i_*gs^2*Nc^2*m2 - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      gv(ti)*cgv(tj)*d_(mu95,nu95)*k1.p2*i_*gs^2*m2 + 4*Prop(-k1)*Prop( - k1
       + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*d_(mu95,nu95)*k1.p2*i_*gs^2*Nc^2*
      m2 - 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*e_(k1,
      p1,p2,nu95)*k1(mu95)*i_*gs^2 + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*gv(ti)*cga(tj)*e_(k1,p1,p2,nu95)*k1(mu95)*i_*gs^2*d + 8*Prop(-k1)
      *Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*e_(k1,p1,p2,nu95)*
      k1(mu95)*i_*gs^2*Nc^2 - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      gv(ti)*cga(tj)*e_(k1,p1,p2,nu95)*k1(mu95)*i_*gs^2*Nc^2*d - 8*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*e_(k1,p1,p2,nu95)*
      p1(mu95)*i_*gs^2 + 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*
      cga(tj)*e_(k1,p1,p2,nu95)*p1(mu95)*i_*gs^2*Nc^2 + 8*Prop(-k1)*Prop( - k1
       + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*e_(k1,p1,p2,nu95)*p2(mu95)*i_*
      gs^2 - 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*e_(
      k1,p1,p2,nu95)*p2(mu95)*i_*gs^2*Nc^2 + 4*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*gv(ti)*cga(tj)*e_(p1,p2,mu95,nu95)*i_*gs^2*m2 - 4*Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*e_(p1,p2,mu95,nu95
      )*i_*gs^2*Nc^2*m2 + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)
      *cga(tj)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2 - 2*Prop(-k1)*Prop( - k1 + p1
      )*Prop( - k1 - p2)*gv(ti)*cga(tj)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2*d - 
      4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*e_(p1,p2,
      mu95,nu95)*k1.k1*i_*gs^2*Nc^2 + 2*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*gv(ti)*cga(tj)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2*Nc^2*d + 8*Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*e_(p1,p2,mu95,nu95
      )*k1.p1*i_*gs^2 - 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*
      cga(tj)*e_(p1,p2,mu95,nu95)*k1.p1*i_*gs^2*Nc^2 - 8*Prop(-k1)*Prop( - k1
       + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*e_(p1,p2,mu95,nu95)*k1.p2*i_*gs^2
       + 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*e_(p1,p2
      ,mu95,nu95)*k1.p2*i_*gs^2*Nc^2 + 24*Prop(-k1)*Prop( - k1 + p1)*Prop( - 
      k1 - p2)*ga(ti)*cgv(tj)*e_(k1,p1,p2,mu95)*k1(nu95)*i_*gs^2 - 4*Prop(-k1)
      *Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(k1,p1,p2,mu95)*
      k1(nu95)*i_*gs^2*d - 24*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cgv(tj)*e_(k1,p1,p2,mu95)*k1(nu95)*i_*gs^2*Nc^2 + 4*Prop(-k1)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(k1,p1,p2,mu95)*k1(nu95)*
      i_*gs^2*Nc^2*d - 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cgv(tj)*e_(k1,p1,p2,mu95)*p1(nu95)*i_*gs^2 + 8*Prop(-k1)*Prop( - k1 + p1
      )*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(k1,p1,p2,mu95)*p1(nu95)*i_*gs^2*
      Nc^2 + 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(
      k1,p1,p2,mu95)*p2(nu95)*i_*gs^2 - 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - 
      k1 - p2)*ga(ti)*cgv(tj)*e_(k1,p1,p2,mu95)*p2(nu95)*i_*gs^2*Nc^2 - 4*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(k1,p1,mu95
      ,nu95)*i_*gs^2*m2 + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)
      *cgv(tj)*e_(k1,p1,mu95,nu95)*i_*gs^2*Nc^2*m2 + 24*Prop(-k1)*Prop( - k1
       + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(k1,p1,mu95,nu95)*k1.p2*i_*gs^2
       - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(k1,p1
      ,mu95,nu95)*k1.p2*i_*gs^2*d - 24*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cgv(tj)*e_(k1,p1,mu95,nu95)*k1.p2*i_*gs^2*Nc^2 + 4*Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(k1,p1,mu95,nu95
      )*k1.p2*i_*gs^2*Nc^2*d - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cgv(tj)*e_(k1,p2,mu95,nu95)*i_*gs^2*m2 + 4*Prop(-k1)*Prop( - k1
       + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(k1,p2,mu95,nu95)*i_*gs^2*Nc^2*
      m2 - 24*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(k1
      ,p2,mu95,nu95)*k1.p1*i_*gs^2 + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cgv(tj)*e_(k1,p2,mu95,nu95)*k1.p1*i_*gs^2*d + 24*Prop(-k1)
      *Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(k1,p2,mu95,nu95)*
      k1.p1*i_*gs^2*Nc^2 - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti
      )*cgv(tj)*e_(k1,p2,mu95,nu95)*k1.p1*i_*gs^2*Nc^2*d + 4*Prop(-k1)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(p1,p2,mu95,nu95)*i_*gs^2*
      m2 - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(p1,
      p2,mu95,nu95)*i_*gs^2*Nc^2*m2 + 12*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cgv(tj)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2 - 2*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(p1,p2,mu95,nu95)*
      k1.k1*i_*gs^2*d - 12*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cgv(tj)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2*Nc^2 + 2*Prop(-k1)*Prop( - k1
       + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2
      *Nc^2*d - 108*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)
      *k1(mu95)*k1(nu95)*i_*gs^2*m2 + 72*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cga(tj)*k1(mu95)*k1(nu95)*i_*gs^2*d*m2 - 15*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*k1(nu95)*i_*
      gs^2*d^2*m2 + Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)
      *k1(mu95)*k1(nu95)*i_*gs^2*d^3*m2 + 108*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*k1(nu95)*i_*gs^2*Nc^2*m2 - 72*Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*k1(nu95)*
      i_*gs^2*Nc^2*d*m2 + 15*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti
      )*cga(tj)*k1(mu95)*k1(nu95)*i_*gs^2*Nc^2*d^2*m2 - Prop(-k1)*Prop( - k1
       + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*k1(nu95)*i_*gs^2*Nc^2*
      d^3*m2 - 24*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      k1(mu95)*p1(nu95)*i_*gs^2*m2 + 14*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cga(tj)*k1(mu95)*p1(nu95)*i_*gs^2*d*m2 - 2*Prop(-k1)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*p1(nu95)*i_*gs^2*
      d^2*m2 + 24*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      k1(mu95)*p1(nu95)*i_*gs^2*Nc^2*m2 - 14*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*p1(nu95)*i_*gs^2*Nc^2*d*m2 + 2*Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*p1(nu95)*
      i_*gs^2*Nc^2*d^2*m2 + 72*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2 - 36*Prop(-k1)*Prop( - k1 + 
      p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*d + 
      4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*
      p1(nu95)*k1.p2*i_*gs^2*d^2 - 72*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - 
      p2)*ga(ti)*cga(tj)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2 + 36*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*p1(nu95)*k1.p2
      *i_*gs^2*Nc^2*d - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cga(tj)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2*d^2 + 24*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*p2(nu95)*i_*gs^2*m2 - 
      14*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*
      p2(nu95)*i_*gs^2*d*m2 + 2*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*k1(mu95)*p2(nu95)*i_*gs^2*d^2*m2 - 24*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*p2(nu95)*i_*gs^2*Nc^2*
      m2 + 14*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      k1(mu95)*p2(nu95)*i_*gs^2*Nc^2*d*m2 - 2*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*p2(nu95)*i_*gs^2*Nc^2*d^2*m2 + 72*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*
      p2(nu95)*k1.p1*i_*gs^2 - 36*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*d + 4*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2
      *d^2 - 72*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2 + 36*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2*d
       - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(mu95)
      *p2(nu95)*k1.p1*i_*gs^2*Nc^2*d^2 + 12*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*p1(mu95)*i_*gs^2*m2 - 4*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*p1(mu95)*i_*
      gs^2*d*m2 - 12*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj
      )*k1(nu95)*p1(mu95)*i_*gs^2*Nc^2*m2 + 4*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*p1(mu95)*i_*gs^2*Nc^2*d*m2 + 144*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*
      p1(mu95)*k1.p2*i_*gs^2 - 108*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)
      *ga(ti)*cga(tj)*k1(nu95)*p1(mu95)*k1.p2*i_*gs^2*d + 26*Prop(-k1)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*p1(mu95)*k1.p2*i_*
      gs^2*d^2 - 2*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      k1(nu95)*p1(mu95)*k1.p2*i_*gs^2*d^3 - 144*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*p1(mu95)*k1.p2*i_*gs^2*Nc^2 + 
      108*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*
      p1(mu95)*k1.p2*i_*gs^2*Nc^2*d - 26*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cga(tj)*k1(nu95)*p1(mu95)*k1.p2*i_*gs^2*Nc^2*d^2 + 2*Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*p1(mu95)*
      k1.p2*i_*gs^2*Nc^2*d^3 - 12*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*k1(nu95)*p2(mu95)*i_*gs^2*m2 + 4*Prop(-k1)*Prop( - k1 + 
      p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*p2(mu95)*i_*gs^2*d*m2 + 12*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*
      p2(mu95)*i_*gs^2*Nc^2*m2 - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)
      *ga(ti)*cga(tj)*k1(nu95)*p2(mu95)*i_*gs^2*Nc^2*d*m2 + 144*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*p2(mu95)*k1.p1
      *i_*gs^2 - 108*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj
      )*k1(nu95)*p2(mu95)*k1.p1*i_*gs^2*d + 26*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*p2(mu95)*k1.p1*i_*gs^2*d^2 - 2*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*
      p2(mu95)*k1.p1*i_*gs^2*d^3 - 144*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cga(tj)*k1(nu95)*p2(mu95)*k1.p1*i_*gs^2*Nc^2 + 108*Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*p2(mu95)*
      k1.p1*i_*gs^2*Nc^2*d - 26*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*k1(nu95)*p2(mu95)*k1.p1*i_*gs^2*Nc^2*d^2 + 2*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*k1(nu95)*p2(mu95)*k1.p1
      *i_*gs^2*Nc^2*d^3 + 24*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti
      )*cga(tj)*p1(mu95)*p1(nu95)*k1.p2*i_*gs^2 - 20*Prop(-k1)*Prop( - k1 + p1
      )*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*p1(nu95)*k1.p2*i_*gs^2*d + 4*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*
      p1(nu95)*k1.p2*i_*gs^2*d^2 - 24*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - 
      p2)*ga(ti)*cga(tj)*p1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2 + 20*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*p1(nu95)*k1.p2
      *i_*gs^2*Nc^2*d - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cga(tj)*p1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2*d^2 - 12*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*i_*gs^2*m2 + 
      10*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*
      p2(nu95)*i_*gs^2*d*m2 - 2*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*i_*gs^2*d^2*m2 + 12*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*i_*gs^2*Nc^2*
      m2 - 10*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      p1(mu95)*p2(nu95)*i_*gs^2*Nc^2*d*m2 + 2*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*i_*gs^2*Nc^2*d^2*m2 - 108*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*
      p2(nu95)*k1.k1*i_*gs^2 + 72*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2*d - 15*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2
      *d^2 + Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      p1(mu95)*p2(nu95)*k1.k1*i_*gs^2*d^3 + 108*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2*Nc^2 - 
      72*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*
      p2(nu95)*k1.k1*i_*gs^2*Nc^2*d + 15*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2*Nc^2*d^2 - Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*
      k1.k1*i_*gs^2*Nc^2*d^3 - 48*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*k1.p1*i_*gs^2 + 28*Prop(-k1)*Prop( - k1
       + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*k1.p1*i_*gs^2*d
       - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)
      *p2(nu95)*k1.p1*i_*gs^2*d^2 + 48*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2 - 28*Prop(-k1
      )*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*
      k1.p1*i_*gs^2*Nc^2*d + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*p1(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2*d^2 - 24*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*k1.p2
      *i_*gs^2 + 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      p1(mu95)*p2(nu95)*k1.p2*i_*gs^2*d + 24*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*p2(nu95)*k1.p2*i_*gs^2*Nc^2 - 8*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(mu95)*
      p2(nu95)*k1.p2*i_*gs^2*Nc^2*d - 12*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*i_*gs^2*m2 + 10*Prop(-k1)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*i_*gs^2*d*
      m2 - 2*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      p1(nu95)*p2(mu95)*i_*gs^2*d^2*m2 + 12*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*i_*gs^2*Nc^2*m2 - 10*Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*
      i_*gs^2*Nc^2*d*m2 + 2*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)
      *cga(tj)*p1(nu95)*p2(mu95)*i_*gs^2*Nc^2*d^2*m2 - 108*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2
       + 72*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*d - 15*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*d^2 + Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*
      k1.k1*i_*gs^2*d^3 + 108*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*Nc^2 - 72*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2
      *Nc^2*d + 15*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*Nc^2*d^2 - Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*Nc^2*d^3
       + 24*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      p1(nu95)*p2(mu95)*k1.p1*i_*gs^2 - 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - 
      k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*k1.p1*i_*gs^2*d - 24*Prop(-k1)
      *Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*
      k1.p1*i_*gs^2*Nc^2 + 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti
      )*cga(tj)*p1(nu95)*p2(mu95)*k1.p1*i_*gs^2*Nc^2*d + 48*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*k1.p2*i_*gs^2
       - 28*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      p1(nu95)*p2(mu95)*k1.p2*i_*gs^2*d + 4*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*k1.p2*i_*gs^2*d^2 - 48*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*
      p2(mu95)*k1.p2*i_*gs^2*Nc^2 + 28*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*k1.p2*i_*gs^2*Nc^2*d - 4*Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p1(nu95)*p2(mu95)*
      k1.p2*i_*gs^2*Nc^2*d^2 - 24*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*p2(mu95)*p2(nu95)*k1.p1*i_*gs^2 + 20*Prop(-k1)*Prop( - k1
       + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p2(mu95)*p2(nu95)*k1.p1*i_*gs^2*d
       - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p2(mu95)
      *p2(nu95)*k1.p1*i_*gs^2*d^2 + 24*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cga(tj)*p2(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2 - 20*Prop(-k1
      )*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*p2(mu95)*p2(nu95)*
      k1.p1*i_*gs^2*Nc^2*d + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*p2(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2*d^2 + 14*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*i_*gs^2*
      m2^2 - 41/3*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      d_(mu95,nu95)*i_*gs^2*d*m2^2 + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*i_*gs^2*d^2*m2^2 - 1/3*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*i_*gs^2*
      d^3*m2^2 - 14*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)
      *d_(mu95,nu95)*i_*gs^2*Nc^2*m2^2 + 41/3*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*i_*gs^2*Nc^2*d*m2^2 - 4*Prop(
      -k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*i_*
      gs^2*Nc^2*d^2*m2^2 + 1/3*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*d_(mu95,nu95)*i_*gs^2*Nc^2*d^3*m2^2 + 150*Prop(-k1)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.k1*i_*gs^2*m2
       - 120*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      d_(mu95,nu95)*k1.k1*i_*gs^2*d*m2 + 203/6*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.k1*i_*gs^2*d^2*m2 - 4*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)
      *k1.k1*i_*gs^2*d^3*m2 + 1/6*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*d_(mu95,nu95)*k1.k1*i_*gs^2*d^4*m2 - 150*Prop(-k1)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.k1*i_*gs^2*
      Nc^2*m2 + 120*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)
      *d_(mu95,nu95)*k1.k1*i_*gs^2*Nc^2*d*m2 - 203/6*Prop(-k1)*Prop( - k1 + p1
      )*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.k1*i_*gs^2*Nc^2*d^2*
      m2 + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      d_(mu95,nu95)*k1.k1*i_*gs^2*Nc^2*d^3*m2 - 1/6*Prop(-k1)*Prop( - k1 + p1)
      *Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.k1*i_*gs^2*Nc^2*d^4*m2
       - 288*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      d_(mu95,nu95)*k1.p1*k1.p2*i_*gs^2 + 216*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p1*k1.p2*i_*gs^2*d - 52*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)
      *k1.p1*k1.p2*i_*gs^2*d^2 + 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)
      *ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p1*k1.p2*i_*gs^2*d^3 + 288*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p1*
      k1.p2*i_*gs^2*Nc^2 - 216*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*d_(mu95,nu95)*k1.p1*k1.p2*i_*gs^2*Nc^2*d + 52*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p1*
      k1.p2*i_*gs^2*Nc^2*d^2 - 4*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p1*k1.p2*i_*gs^2*Nc^2*d^3 + 28*Prop(-k1)
      *Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p1*i_
      *gs^2*m2 - 82/3*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*d_(mu95,nu95)*k1.p1*i_*gs^2*d*m2 + 8*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p1*i_*gs^2*d^2*m2 - 2/3
      *Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      d_(mu95,nu95)*k1.p1*i_*gs^2*d^3*m2 - 28*Prop(-k1)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p1*i_*gs^2*Nc^2*m2 + 82/3*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)
      *k1.p1*i_*gs^2*Nc^2*d*m2 - 8*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)
      *ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p1*i_*gs^2*Nc^2*d^2*m2 + 2/3*Prop(-k1)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p1*i_*
      gs^2*Nc^2*d^3*m2 - 28*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)
      *cga(tj)*d_(mu95,nu95)*k1.p2*i_*gs^2*m2 + 82/3*Prop(-k1)*Prop( - k1 + p1
      )*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p2*i_*gs^2*d*m2 - 8*
      Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)
      *k1.p2*i_*gs^2*d^2*m2 + 2/3*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p2*i_*gs^2*d^3*m2 + 28*Prop(-k1)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p2*i_*gs^2*
      Nc^2*m2 - 82/3*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj
      )*d_(mu95,nu95)*k1.p2*i_*gs^2*Nc^2*d*m2 + 8*Prop(-k1)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*d_(mu95,nu95)*k1.p2*i_*gs^2*Nc^2*d^2*m2
       - 2/3*Prop(-k1)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      d_(mu95,nu95)*k1.p2*i_*gs^2*Nc^2*d^3*m2;

