repeat;
id Prop(p1 + r1)*Prop(p2 + r1)*Prop(p2 + r1 + r2)*Prop(p1 + p2 + r2) = +Num(u*z)*Den(m2*z-m2*u+m2*u*z)*Prop(p1 + r1)*Prop(p2 + r1)*Prop(p2 + r1 + r2)+Num(z+u*z)*Den(m2*z-m2*u+m2*u*z)*Prop(p1 + r1)*Prop(p2 + r1)*Prop(p1 + p2 + r2)+Num(u*z)*Den(m2*z-m2*u+m2*u*z)*Prop(p1 + r1)*Prop(p2 + r1 + r2)*Prop(p1 + p2 + r2)+Num(u*z)*Den(m2*z-m2*u+m2*u*z)*Prop(p2 + r1)*Prop(p2 + r1 + r2)*Prop(p1 + p2 + r2);
endrepeat;
