repeat;
id Prop(p2 + r1)*Prop(p2 + r2)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2) = +Num(-2*z)*Den(m2*u-2*m2*z+m2*u*z)*Prop(p2 + r1)*Prop(p2 + r2)*Prop(p1 + r1 + r2)+Num(u*z)*Den(m2*u-2*m2*z+m2*u*z)*Prop(p2 + r1)*Prop(p2 + r2)*Prop(p2 + r1 + r2)+Num(-u*z)*Den(m2*u-2*m2*z+m2*u*z)*Prop(p2 + r1)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2)+Num(-u*z)*Den(m2*u-2*m2*z+m2*u*z)*Prop(p2 + r2)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2);
endrepeat;
