l [interf7_7]= + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(p1 + r2)^2*
      Prop( - p2 - r1)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4*
      Nc^-1 * ( 16*p1.r2*p2.r1*p2.r2 - 16*p1.r2*p2.r1*p2.r2*d + 4*p1.r2*p2.r1*
         p2.r2*d^2 + 8*p1.r2*p2.r1*s12 - 8*p1.r2*p2.r1*d*s12 + 2*p1.r2*p2.r1*
         d^2*s12 + 16*p1.r2*p2.r1^2 - 16*p1.r2*p2.r1^2*d + 4*p1.r2*p2.r1^2*d^2
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(p1 + r2)^2*Prop( - p2
       - r1)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4*Nc * (  - 32
         *p1.r2*p2.r1*p2.r2 + 32*p1.r2*p2.r1*p2.r2*d - 8*p1.r2*p2.r1*p2.r2*d^2
          - 16*p1.r2*p2.r1*s12 + 16*p1.r2*p2.r1*d*s12 - 4*p1.r2*p2.r1*d^2*s12
          - 32*p1.r2*p2.r1^2 + 32*p1.r2*p2.r1^2*d - 8*p1.r2*p2.r1^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(p1 + r2)^2*Prop( - p2
       - r1)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4*Nc^3 * ( 16*
         p1.r2*p2.r1*p2.r2 - 16*p1.r2*p2.r1*p2.r2*d + 4*p1.r2*p2.r1*p2.r2*d^2
          + 8*p1.r2*p2.r1*s12 - 8*p1.r2*p2.r1*d*s12 + 2*p1.r2*p2.r1*d^2*s12 + 
         16*p1.r2*p2.r1^2 - 16*p1.r2*p2.r1^2*d + 4*p1.r2*p2.r1^2*d^2 );

