id r1.r2*TOPO(17) = +Num(1+u)*Den(2)*TOPO(17)*DD5+Num(-1-u)*Den(2)*TOPO(17)*DD8+Num(-1-u)*Den(2)*TOPO(17)*DD12+Num(m2+m2*z)*Den(2*z)*TOPO(17)*1;
id p1.r1*TOPO(17) = +1*Den(2)*TOPO(17)*DD5;
id p2.r1*TOPO(17) = +(-1)*Den(2)*TOPO(17)*DD5+1*Den(2)*TOPO(17)*DD12+Num(-m2)*Den(2*z)*TOPO(17)*1;
id p1.r2*TOPO(17) = +Num(-1-u)*Den(2)*TOPO(17)*DD5+Num(u)*Den(2)*TOPO(17)*DD8+Num(u)*Den(2)*TOPO(17)*DD12+Num(-m2)*Den(2*z)*TOPO(17)*1;
id p2.r2*TOPO(17) = +1*Den(2)*TOPO(17)*DD8;
