id r1.r2*TOPO(25) = +(-1)*Den(2)*TOPO(25)*DD12+(-1)*Den(2)*TOPO(25)*DD13+Num(m2+m2*z)*Den(2*z)*TOPO(25)*1;
id p1.r1*TOPO(25) = +(-1)*Den(2)*TOPO(25)*DD7+Num(u)*Den(2+2*u)*TOPO(25)*DD12+Num(u)*Den(2+2*u)*TOPO(25)*DD13+Num(-m2)*Den(2*z)*TOPO(25)*1;
id p2.r1*TOPO(25) = +1*Den(2)*TOPO(25)*DD7+1*Den(2+2*u)*TOPO(25)*DD12+Num(-u)*Den(2+2*u)*TOPO(25)*DD13;
id p1.r2*TOPO(25) = +1*Den(2)*TOPO(25)*DD7;
id p2.r2*TOPO(25) = +(-1)*Den(2)*TOPO(25)*DD7+1*Den(2)*TOPO(25)*DD13+Num(-m2)*Den(2*z)*TOPO(25)*1;
