L Had=2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*
      cgv(tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*k1(nu95)*i_*gs^2*m2^2 - Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      Den(cut, - q.p1 + q.p2*u)*k1(mu95)*k1(nu95)*i_*gs^2*d*m2^2 - 2*Prop(-k1)
      *Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(
      cut, - q.p1 + q.p2*u)*k1(mu95)*k1(nu95)*i_*gs^2*Nc^2*m2^2 + Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(mu95)*k1(nu95)*i_*gs^2*Nc^2*d*m2^2 - 4*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*m2 + 2*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*d*m2 + 4*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2*m2 - 2*Prop(-k1)
      *Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(
      cut, - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2*d*m2 - 4*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*m2 + 2*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*d*m2 + 4*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2*m2 - 
      2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*
      cgv(tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2*d
      *m2 + 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(
      ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*i_*gs^2*m2^2 - 2
      *Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*i_*gs^2*Nc^2*m2^2 - 2*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p2(mu95)*i_*gs^2*m2^2 + 2*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p2(mu95)*i_*gs^2*Nc^2*m2^2 - 4*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p1(nu95)*k1.p2*i_*gs^2*m2 + 4*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2*m2 + 2*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*i_*gs^2*m2^2 - 2*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*i_*gs^2*Nc^2*m2^2 + 2*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2*m2 - Prop(-k1)
      *Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(
      cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2*d*m2 - 2*Prop(-k1)
      *Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(
      cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2*Nc^2*m2 + Prop(-k1
      )*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(
      cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2*Nc^2*d*m2 - 4*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.p2*i_*gs^2*m2 + 4*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.p2*i_*gs^2*Nc^2*m2 + 
      2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*
      cgv(tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*i_*gs^2*m2^2 - 2*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*i_*gs^2*Nc^2*m2^2 + 2*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*m2 - Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*d*m2 - 2*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*
      Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*Nc^2*m2 + 
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*Nc^2*d*m2
       + 4*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*
      cgv(tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.p1*i_*gs^2*m2 - 4
      *Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.p1*i_*gs^2*Nc^2*m2 + 
      4*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*
      cgv(tj)*Den(cut, - q.p1 + q.p2*u)*p2(mu95)*p2(nu95)*k1.p1*i_*gs^2*m2 - 4
      *Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*p2(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2*m2 - 
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(
      tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*i_*gs^2*m2^3 + Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut
      , - q.p1 + q.p2*u)*d_(mu95,nu95)*i_*gs^2*Nc^2*m2^3 - Prop(-k1)*Prop(cut,
      -q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut, - q.p1
       + q.p2*u)*d_(mu95,nu95)*k1.k1*i_*gs^2*m2^2 + 1/2*Prop(-k1)*Prop(cut,-q,
      m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut, - q.p1 + 
      q.p2*u)*d_(mu95,nu95)*k1.k1*i_*gs^2*d*m2^2 + Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*
      u)*d_(mu95,nu95)*k1.k1*i_*gs^2*Nc^2*m2^2 - 1/2*Prop(-k1)*Prop(cut,-q,m2)
      *Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2
      *u)*d_(mu95,nu95)*k1.k1*i_*gs^2*Nc^2*d*m2^2 - 2*Prop(-k1)*Prop(cut,-q,m2
      )*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut, - q.p1 + 
      q.p2*u)*d_(mu95,nu95)*k1.p1*i_*gs^2*m2^2 + 2*Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*
      u)*d_(mu95,nu95)*k1.p1*i_*gs^2*Nc^2*m2^2 + 2*Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*
      u)*d_(mu95,nu95)*k1.p2*i_*gs^2*m2^2 - 2*Prop(-k1)*Prop(cut,-q,m2)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*
      d_(mu95,nu95)*k1.p2*i_*gs^2*Nc^2*m2^2 + 4*Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*
      u)*e_(k1,p1,p2,nu95)*k1(mu95)*i_*gs^2*m2 - 2*Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*
      u)*e_(k1,p1,p2,nu95)*k1(mu95)*i_*gs^2*d*m2 - 4*Prop(-k1)*Prop(cut,-q,m2)
      *Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(cut, - q.p1 + q.p2
      *u)*e_(k1,p1,p2,nu95)*k1(mu95)*i_*gs^2*Nc^2*m2 + 2*Prop(-k1)*Prop(cut,-q
      ,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(cut, - q.p1 + 
      q.p2*u)*e_(k1,p1,p2,nu95)*k1(mu95)*i_*gs^2*Nc^2*d*m2 + 4*Prop(-k1)*Prop(
      cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(cut, - 
      q.p1 + q.p2*u)*e_(k1,p1,p2,nu95)*p1(mu95)*i_*gs^2*m2 - 4*Prop(-k1)*Prop(
      cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(cut, - 
      q.p1 + q.p2*u)*e_(k1,p1,p2,nu95)*p1(mu95)*i_*gs^2*Nc^2*m2 - 4*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*e_(k1,p1,p2,nu95)*p2(mu95)*i_*gs^2*m2 + 4*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*e_(k1,p1,p2,nu95)*p2(mu95)*i_*gs^2*Nc^2*m2 - 2*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*i_*gs^2*m2^2 + 2*Prop(-k1)
      *Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*i_*gs^2*Nc^2*m2^2 - 2*Prop(-k1
      )*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2*m2 + Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2*d*m2 + 2*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2*Nc^2*m2 - Prop(-k1)
      *Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2*Nc^2*d*m2 - 4*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*k1.p1*i_*gs^2*m2 + 4*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*k1.p1*i_*gs^2*Nc^2*m2
       + 4*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*k1.p2*i_*gs^2*m2
       - 4*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*gv(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*k1.p2*i_*gs^2*Nc^2
      *m2 - 12*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(k1,p1,p2,mu95)*k1(nu95)*i_*gs^2
      *m2 + 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(k1,p1,p2,mu95)*k1(nu95)*i_*gs^2
      *d*m2 + 12*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(k1,p1,p2,mu95)*k1(nu95)*i_*
      gs^2*Nc^2*m2 - 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(k1,p1,p2,mu95)*
      k1(nu95)*i_*gs^2*Nc^2*d*m2 + 4*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1
      )*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(k1,p1,p2,
      mu95)*p1(nu95)*i_*gs^2*m2 - 4*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)
      *Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(k1,p1,p2,
      mu95)*p1(nu95)*i_*gs^2*Nc^2*m2 - 4*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1
       + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(k1,
      p1,p2,mu95)*p2(nu95)*i_*gs^2*m2 + 4*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1
       + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(k1,
      p1,p2,mu95)*p2(nu95)*i_*gs^2*Nc^2*m2 + 2*Prop(-k1)*Prop(cut,-q,m2)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*
      e_(k1,p1,mu95,nu95)*i_*gs^2*m2^2 - 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(k1
      ,p1,mu95,nu95)*i_*gs^2*Nc^2*m2^2 - 12*Prop(-k1)*Prop(cut,-q,m2)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(k1
      ,p1,mu95,nu95)*k1.p2*i_*gs^2*m2 + 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1
       + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(k1,
      p1,mu95,nu95)*k1.p2*i_*gs^2*d*m2 + 12*Prop(-k1)*Prop(cut,-q,m2)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(k1
      ,p1,mu95,nu95)*k1.p2*i_*gs^2*Nc^2*m2 - 2*Prop(-k1)*Prop(cut,-q,m2)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*
      e_(k1,p1,mu95,nu95)*k1.p2*i_*gs^2*Nc^2*d*m2 + 2*Prop(-k1)*Prop(cut,-q,m2
      )*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + 
      q.p2*u)*e_(k1,p2,mu95,nu95)*i_*gs^2*m2^2 - 2*Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*
      u)*e_(k1,p2,mu95,nu95)*i_*gs^2*Nc^2*m2^2 + 12*Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*
      u)*e_(k1,p2,mu95,nu95)*k1.p1*i_*gs^2*m2 - 2*Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*
      u)*e_(k1,p2,mu95,nu95)*k1.p1*i_*gs^2*d*m2 - 12*Prop(-k1)*Prop(cut,-q,m2)
      *Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2
      *u)*e_(k1,p2,mu95,nu95)*k1.p1*i_*gs^2*Nc^2*m2 + 2*Prop(-k1)*Prop(cut,-q,
      m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + 
      q.p2*u)*e_(k1,p2,mu95,nu95)*k1.p1*i_*gs^2*Nc^2*d*m2 - 2*Prop(-k1)*Prop(
      cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - 
      q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*i_*gs^2*m2^2 + 2*Prop(-k1)*Prop(cut,
      -q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1
       + q.p2*u)*e_(p1,p2,mu95,nu95)*i_*gs^2*Nc^2*m2^2 - 6*Prop(-k1)*Prop(cut,
      -q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1
       + q.p2*u)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2*m2 + Prop(-k1)*Prop(cut,-q,
      m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + 
      q.p2*u)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2*d*m2 + 6*Prop(-k1)*Prop(cut,-q
      ,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1 + 
      q.p2*u)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2*Nc^2*m2 - Prop(-k1)*Prop(cut,
      -q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cgv(tj)*Den(cut, - q.p1
       + q.p2*u)*e_(p1,p2,mu95,nu95)*k1.k1*i_*gs^2*Nc^2*d*m2 + 54*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(mu95)*k1(nu95)*i_*gs^2*m2^2 - 36*Prop(-k1)*Prop(
      cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - 
      q.p1 + q.p2*u)*k1(mu95)*k1(nu95)*i_*gs^2*d*m2^2 + 15/2*Prop(-k1)*Prop(
      cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - 
      q.p1 + q.p2*u)*k1(mu95)*k1(nu95)*i_*gs^2*d^2*m2^2 - 1/2*Prop(-k1)*Prop(
      cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - 
      q.p1 + q.p2*u)*k1(mu95)*k1(nu95)*i_*gs^2*d^3*m2^2 - 54*Prop(-k1)*Prop(
      cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - 
      q.p1 + q.p2*u)*k1(mu95)*k1(nu95)*i_*gs^2*Nc^2*m2^2 + 36*Prop(-k1)*Prop(
      cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - 
      q.p1 + q.p2*u)*k1(mu95)*k1(nu95)*i_*gs^2*Nc^2*d*m2^2 - 15/2*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(mu95)*k1(nu95)*i_*gs^2*Nc^2*d^2*m2^2 + 1/2*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*k1(mu95)*k1(nu95)*i_*gs^2*Nc^2*d^3*m2^2 + 12*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*i_*gs^2*m2^2 - 7*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*i_*gs^2*d*m2^2 + Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*i_*gs^2*d^2*m2^2 - 12*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*i_*gs^2*Nc^2*m2^2 + 7*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*i_*gs^2*Nc^2*d*m2^2 - Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*i_*gs^2*Nc^2*d^2*m2^2 - 36*Prop(-k1
      )*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*m2 + 18*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*d*m2 - 2*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*d^2*m2 + 36*Prop(-k1)
      *Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2*m2 - 18*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2*d*m2 + 2*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2*d^2*
      m2 - 12*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*i_*gs^2*m2^2 + 7
      *Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*i_*gs^2*d*m2^2 - Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*i_*gs^2*d^2*m2^2 + 12*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*i_*gs^2*Nc^2*m2^2 - 7*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*i_*gs^2*Nc^2*d*m2^2 + Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*i_*gs^2*Nc^2*d^2*m2^2 - 36*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*m2 + 18*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*d*m2 - 2*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*d^2*m2 + 
      36*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2*
      m2 - 18*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*k1.p1*i_*gs^2*
      Nc^2*d*m2 + 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2
      )*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(mu95)*p2(nu95)*k1.p1*i_*
      gs^2*Nc^2*d^2*m2 - 6*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - 
      k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*i_*
      gs^2*m2^2 + 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2
      )*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*i_*gs^2*d*
      m2^2 + 6*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*i_*gs^2*Nc^2*
      m2^2 - 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*i_*gs^2*Nc^2*d*
      m2^2 - 72*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*k1.p2*i_*gs^2
      *m2 + 54*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*k1.p2*i_*gs^2*d*
      m2 - 13*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*k1.p2*i_*gs^2*
      d^2*m2 + Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*k1.p2*i_*gs^2*
      d^3*m2 + 72*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*k1.p2*i_*gs^2
      *Nc^2*m2 - 54*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2
      )*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*k1.p2*i_*
      gs^2*Nc^2*d*m2 + 13*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - 
      k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*p1(mu95)*
      k1.p2*i_*gs^2*Nc^2*d^2*m2 - Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*k1(nu95)*
      p1(mu95)*k1.p2*i_*gs^2*Nc^2*d^3*m2 + 6*Prop(-k1)*Prop(cut,-q,m2)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*
      k1(nu95)*p2(mu95)*i_*gs^2*m2^2 - 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1
       + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*
      k1(nu95)*p2(mu95)*i_*gs^2*d*m2^2 - 6*Prop(-k1)*Prop(cut,-q,m2)*Prop( - 
      k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*
      k1(nu95)*p2(mu95)*i_*gs^2*Nc^2*m2^2 + 2*Prop(-k1)*Prop(cut,-q,m2)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*
      k1(nu95)*p2(mu95)*i_*gs^2*Nc^2*d*m2^2 - 72*Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*
      u)*k1(nu95)*p2(mu95)*k1.p1*i_*gs^2*m2 + 54*Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*
      u)*k1(nu95)*p2(mu95)*k1.p1*i_*gs^2*d*m2 - 13*Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*
      u)*k1(nu95)*p2(mu95)*k1.p1*i_*gs^2*d^2*m2 + Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*
      u)*k1(nu95)*p2(mu95)*k1.p1*i_*gs^2*d^3*m2 + 72*Prop(-k1)*Prop(cut,-q,m2)
      *Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2
      *u)*k1(nu95)*p2(mu95)*k1.p1*i_*gs^2*Nc^2*m2 - 54*Prop(-k1)*Prop(cut,-q,
      m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + 
      q.p2*u)*k1(nu95)*p2(mu95)*k1.p1*i_*gs^2*Nc^2*d*m2 + 13*Prop(-k1)*Prop(
      cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - 
      q.p1 + q.p2*u)*k1(nu95)*p2(mu95)*k1.p1*i_*gs^2*Nc^2*d^2*m2 - Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*k1(nu95)*p2(mu95)*k1.p1*i_*gs^2*Nc^2*d^3*m2 - 12*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p1(nu95)*k1.p2*i_*gs^2*m2 + 10*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p1(nu95)*k1.p2*i_*gs^2*d*m2 - 2*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p1(nu95)*k1.p2*i_*gs^2*d^2*m2 + 
      12*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p1(nu95)*k1.p2*i_*gs^2*Nc^2*
      m2 - 10*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p1(nu95)*k1.p2*i_*gs^2*
      Nc^2*d*m2 + 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2
      )*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p1(nu95)*k1.p2*i_*
      gs^2*Nc^2*d^2*m2 + 6*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - 
      k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*i_*
      gs^2*m2^2 - 5*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2
      )*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*i_*gs^2*d*
      m2^2 + Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti
      )*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*i_*gs^2*d^2*m2^2
       - 6*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*i_*gs^2*Nc^2*m2^2 + 
      5*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*i_*gs^2*Nc^2*d*m2^2
       - Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*i_*gs^2*Nc^2*d^2*
      m2^2 + 54*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2
      *m2 - 36*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2*d*
      m2 + 15/2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.k1*i_*gs^2
      *d^2*m2 - 1/2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2
      )*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.k1*i_*
      gs^2*d^3*m2 - 54*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1
       - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.k1*
      i_*gs^2*Nc^2*m2 + 36*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - 
      k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*
      k1.k1*i_*gs^2*Nc^2*d*m2 - 15/2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1
      )*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*
      p2(nu95)*k1.k1*i_*gs^2*Nc^2*d^2*m2 + 1/2*Prop(-k1)*Prop(cut,-q,m2)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*
      p1(mu95)*p2(nu95)*k1.k1*i_*gs^2*Nc^2*d^3*m2 + 24*Prop(-k1)*Prop(cut,-q,
      m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + 
      q.p2*u)*p1(mu95)*p2(nu95)*k1.p1*i_*gs^2*m2 - 14*Prop(-k1)*Prop(cut,-q,m2
      )*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + 
      q.p2*u)*p1(mu95)*p2(nu95)*k1.p1*i_*gs^2*d*m2 + 2*Prop(-k1)*Prop(cut,-q,
      m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + 
      q.p2*u)*p1(mu95)*p2(nu95)*k1.p1*i_*gs^2*d^2*m2 - 24*Prop(-k1)*Prop(cut,
      -q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1
       + q.p2*u)*p1(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2*m2 + 14*Prop(-k1)*Prop(
      cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - 
      q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2*d*m2 - 2*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2*d^2*m2 + 12*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.p2*i_*gs^2*m2 - 4*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.p2*i_*gs^2*d*m2 - 12*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.p2*i_*gs^2*Nc^2*m2 + 
      4*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*k1.p2*i_*gs^2*Nc^2*d
      *m2 + 6*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*i_*gs^2*m2^2 - 5
      *Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*i_*gs^2*d*m2^2 + Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*i_*gs^2*d^2*m2^2 - 6*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*i_*gs^2*Nc^2*m2^2 + 5*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*i_*gs^2*Nc^2*d*m2^2 - Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*i_*gs^2*Nc^2*d^2*m2^2 + 54*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*m2 - 36*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*d*m2 + 15/
      2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*d^2*m2
       - 1/2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti
      )*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*d^3*
      m2 - 54*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.k1*i_*gs^2*
      Nc^2*m2 + 36*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)
      *ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.k1*i_*
      gs^2*Nc^2*d*m2 - 15/2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop(
       - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*
      k1.k1*i_*gs^2*Nc^2*d^2*m2 + 1/2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + 
      p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*
      p2(mu95)*k1.k1*i_*gs^2*Nc^2*d^3*m2 - 12*Prop(-k1)*Prop(cut,-q,m2)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*
      p1(nu95)*p2(mu95)*k1.p1*i_*gs^2*m2 + 4*Prop(-k1)*Prop(cut,-q,m2)*Prop(
       - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*
      p1(nu95)*p2(mu95)*k1.p1*i_*gs^2*d*m2 + 12*Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*
      u)*p1(nu95)*p2(mu95)*k1.p1*i_*gs^2*Nc^2*m2 - 4*Prop(-k1)*Prop(cut,-q,m2)
      *Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2
      *u)*p1(nu95)*p2(mu95)*k1.p1*i_*gs^2*Nc^2*d*m2 - 24*Prop(-k1)*Prop(cut,-q
      ,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + 
      q.p2*u)*p1(nu95)*p2(mu95)*k1.p2*i_*gs^2*m2 + 14*Prop(-k1)*Prop(cut,-q,m2
      )*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + 
      q.p2*u)*p1(nu95)*p2(mu95)*k1.p2*i_*gs^2*d*m2 - 2*Prop(-k1)*Prop(cut,-q,
      m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + 
      q.p2*u)*p1(nu95)*p2(mu95)*k1.p2*i_*gs^2*d^2*m2 + 24*Prop(-k1)*Prop(cut,
      -q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1
       + q.p2*u)*p1(nu95)*p2(mu95)*k1.p2*i_*gs^2*Nc^2*m2 - 14*Prop(-k1)*Prop(
      cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - 
      q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.p2*i_*gs^2*Nc^2*d*m2 + 2*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*k1.p2*i_*gs^2*Nc^2*d^2*m2 + 12*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*p2(mu95)*p2(nu95)*k1.p1*i_*gs^2*m2 - 10*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*p2(mu95)*p2(nu95)*k1.p1*i_*gs^2*d*m2 + 2*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*p2(mu95)*p2(nu95)*k1.p1*i_*gs^2*d^2*m2 - 
      12*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*p2(mu95)*p2(nu95)*k1.p1*i_*gs^2*Nc^2*
      m2 + 10*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p2(mu95)*p2(nu95)*k1.p1*i_*gs^2*
      Nc^2*d*m2 - 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2
      )*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p2(mu95)*p2(nu95)*k1.p1*i_*
      gs^2*Nc^2*d^2*m2 - 7*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - 
      k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*i_*gs^2*
      m2^3 + 41/6*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*i_*gs^2*d*m2^3 - 
      2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*i_*gs^2*d^2*m2^3 + 1/6*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*i_*gs^2*d^3*m2^3 + 7*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*i_*gs^2*Nc^2*m2^3 - 41/6*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*i_*gs^2*Nc^2*d*m2^3 + 2*Prop(-k1
      )*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*i_*gs^2*Nc^2*d^2*m2^3 - 1/6*Prop(-k1
      )*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*i_*gs^2*Nc^2*d^3*m2^3 - 75*Prop(-k1)
      *Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.k1*i_*gs^2*m2^2 + 60*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.k1*i_*gs^2*d*m2^2 - 203/12*Prop(-k1)
      *Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.k1*i_*gs^2*d^2*m2^2 + 2*Prop(-k1)
      *Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.k1*i_*gs^2*d^3*m2^2 - 1/12*Prop(
      -k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.k1*i_*gs^2*d^4*m2^2 + 75*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.k1*i_*gs^2*Nc^2*m2^2 - 60
      *Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.k1*i_*gs^2*Nc^2*d*m2^2 + 
      203/12*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti
      )*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.k1*i_*gs^2*Nc^2*d^2
      *m2^2 - 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.k1*i_*gs^2*
      Nc^2*d^3*m2^2 + 1/12*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - 
      k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.k1*i_
      *gs^2*Nc^2*d^4*m2^2 + 144*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*
      k1.p1*k1.p2*i_*gs^2*m2 - 108*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*
      k1.p1*k1.p2*i_*gs^2*d*m2 + 26*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)
      *Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)
      *k1.p1*k1.p2*i_*gs^2*d^2*m2 - 2*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + 
      p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*
      d_(mu95,nu95)*k1.p1*k1.p2*i_*gs^2*d^3*m2 - 144*Prop(-k1)*Prop(cut,-q,m2)
      *Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2
      *u)*d_(mu95,nu95)*k1.p1*k1.p2*i_*gs^2*Nc^2*m2 + 108*Prop(-k1)*Prop(cut,
      -q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1
       + q.p2*u)*d_(mu95,nu95)*k1.p1*k1.p2*i_*gs^2*Nc^2*d*m2 - 26*Prop(-k1)*
      Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.p1*k1.p2*i_*gs^2*Nc^2*d^2*m2 + 2*
      Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(
      tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.p1*k1.p2*i_*gs^2*Nc^2*d^3
      *m2 - 14*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.p1*i_*gs^2*m2^2
       + 41/3*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.p1*i_*gs^2*d*m2^2
       - 4*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.p1*i_*gs^2*d^2*m2^2
       + 1/3*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti
      )*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.p1*i_*gs^2*d^3*m2^2
       + 14*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)
      *cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.p1*i_*gs^2*Nc^2*m2^2
       - 41/3*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(
      ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.p1*i_*gs^2*Nc^2*d
      *m2^2 + 4*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*
      ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.p1*i_*gs^2*
      Nc^2*d^2*m2^2 - 1/3*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*Prop( - 
      k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*k1.p1*i_
      *gs^2*Nc^2*d^3*m2^2 + 14*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*
      k1.p2*i_*gs^2*m2^2 - 41/3*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*
      k1.p2*i_*gs^2*d*m2^2 + 4*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*
      k1.p2*i_*gs^2*d^2*m2^2 - 1/3*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*
      k1.p2*i_*gs^2*d^3*m2^2 - 14*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1)*
      Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*
      k1.p2*i_*gs^2*Nc^2*m2^2 + 41/3*Prop(-k1)*Prop(cut,-q,m2)*Prop( - k1 + p1
      )*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*
      d_(mu95,nu95)*k1.p2*i_*gs^2*Nc^2*d*m2^2 - 4*Prop(-k1)*Prop(cut,-q,m2)*
      Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*
      u)*d_(mu95,nu95)*k1.p2*i_*gs^2*Nc^2*d^2*m2^2 + 1/3*Prop(-k1)*Prop(cut,-q
      ,m2)*Prop( - k1 + p1)*Prop( - k1 - p2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + 
      q.p2*u)*d_(mu95,nu95)*k1.p2*i_*gs^2*Nc^2*d^3*m2^2;

