repeat;
id Prop(p1 + r1 + r2)*Prop(r1 + r2)*Prop(p1 + p2 + r1)*Prop(p1 + p2 + r2) = +Num(z+u*z)*Den(m2*u+m2*z+2*m2*u*z)*Prop(p1 + r1 + r2)*Prop(r1 + r2)*Prop(p1 + p2 + r1)+Num(z+u*z)*Den(m2*u+m2*z+2*m2*u*z)*Prop(p1 + r1 + r2)*Prop(r1 + r2)*Prop(p1 + p2 + r2)+Num(u*z)*Den(m2*u+m2*z+2*m2*u*z)*Prop(p1 + r1 + r2)*Prop(p1 + p2 + r1)*Prop(p1 + p2 + r2)+Num(z+u*z)*Den(m2*u+m2*z+2*m2*u*z)*Prop(r1 + r2)*Prop(p1 + p2 + r1)*Prop(p1 + p2 + r2);
endrepeat;
