repeat;
id Prop(p2 + r1 + r2)*Prop(r1 + r2)*Prop(p1 + p2 + r1)*Prop(p1 + p2 + r2) = +Num(z+u*z)*Den(m2+2*m2*z+m2*u*z)*Prop(p2 + r1 + r2)*Prop(r1 + r2)*Prop(p1 + p2 + r1)+Num(z+u*z)*Den(m2+2*m2*z+m2*u*z)*Prop(p2 + r1 + r2)*Prop(r1 + r2)*Prop(p1 + p2 + r2)+Num(z)*Den(m2+2*m2*z+m2*u*z)*Prop(p2 + r1 + r2)*Prop(p1 + p2 + r1)*Prop(p1 + p2 + r2)+Num(z+u*z)*Den(m2+2*m2*z+m2*u*z)*Prop(r1 + r2)*Prop(p1 + p2 + r1)*Prop(p1 + p2 + r2);
endrepeat;
