l [interf2_2]= + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r2)^2*
      Prop( - p1 - p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*gs^4
       * ( 16*p1.r1*p2.r1*p2.r2 + 4*p1.r1*p2.r1*d*s12 + 16*p1.r1*p2.r1^2 - 8*
         p1.r1*p2.r2*s12 + 4*p1.r1*p2.r2*d*s12 - 4*p1.r1*s12^2 + 2*p1.r1*d*
         s12^2 - 16*p2.r1*p2.r2*s12 + 4*p2.r1*p2.r2*d*s12 - 8*p2.r1*s12^2 + 2*
         p2.r1*d*s12^2 - 16*p2.r1^2*p2.r2 - 24*p2.r1^2*s12 + 4*p2.r1^2*d*s12
          - 16*p2.r1^3 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r2)^2*Prop( - 
      p1 - p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*gs^4*Nc^2 * ( 
          - 16*p1.r1*p2.r1*p2.r2 - 4*p1.r1*p2.r1*d*s12 - 16*p1.r1*p2.r1^2 + 8*
         p1.r1*p2.r2*s12 - 4*p1.r1*p2.r2*d*s12 + 4*p1.r1*s12^2 - 2*p1.r1*d*
         s12^2 + 16*p2.r1*p2.r2*s12 - 4*p2.r1*p2.r2*d*s12 + 8*p2.r1*s12^2 - 2*
         p2.r1*d*s12^2 + 16*p2.r1^2*p2.r2 + 24*p2.r1^2*s12 - 4*p2.r1^2*d*s12
          + 16*p2.r1^3 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r2)^2*Prop( - 
      p1 - p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*gs^4 * ( 16*
         p1.r1*p2.r1*p2.r2 - 8*p1.r1*p2.r1*s12 + 4*p1.r1*p2.r1*d*s12 + 16*
         p1.r1*p2.r1^2 - 16*p1.r1*p2.r2*s12 + 4*p1.r1*p2.r2*d*s12 - 8*p1.r1*
         s12^2 + 2*p1.r1*d*s12^2 - 16*p1.r1^2*p2.r1 - 16*p1.r1^2*p2.r2 - 8*
         p1.r1^2*s12 - 8*p2.r1*p2.r2*s12 + 4*p2.r1*p2.r2*d*s12 - 4*p2.r1*s12^2
          + 2*p2.r1*d*s12^2 - 8*p2.r1^2*s12 + 4*p2.r1^2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r2)^2*Prop( - 
      p1 - p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*gs^4*Nc^2 * ( 
          - 16*p1.r1*p2.r1*p2.r2 + 8*p1.r1*p2.r1*s12 - 4*p1.r1*p2.r1*d*s12 - 
         16*p1.r1*p2.r1^2 + 16*p1.r1*p2.r2*s12 - 4*p1.r1*p2.r2*d*s12 + 8*p1.r1
         *s12^2 - 2*p1.r1*d*s12^2 + 16*p1.r1^2*p2.r1 + 16*p1.r1^2*p2.r2 + 8*
         p1.r1^2*s12 + 8*p2.r1*p2.r2*s12 - 4*p2.r1*p2.r2*d*s12 + 4*p2.r1*s12^2
          - 2*p2.r1*d*s12^2 + 8*p2.r1^2*s12 - 4*p2.r1^2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r2)^2*Prop( - 
      p1 - p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4 * ( 4*
         s12^3 - d*s12^3 + 32*p1.r1*p2.r1*p2.r2 + 24*p1.r1*p2.r1*s12 + 32*
         p1.r1*p2.r1^2 + 8*p1.r1*p2.r2*s12 + 4*p1.r1*s12^2 + 8*p2.r1*p2.r2*s12
          + 12*p2.r1*s12^2 - 2*p2.r1*d*s12^2 + 8*p2.r1^2*s12 + 8*p2.r2*s12^2
          - 2*p2.r2*d*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r2)^2*Prop( - 
      p1 - p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4*Nc^2 * ( 
          - 4*s12^3 + d*s12^3 - 32*p1.r1*p2.r1*p2.r2 - 24*p1.r1*p2.r1*s12 - 32
         *p1.r1*p2.r1^2 - 8*p1.r1*p2.r2*s12 - 4*p1.r1*s12^2 - 8*p2.r1*p2.r2*
         s12 - 12*p2.r1*s12^2 + 2*p2.r1*d*s12^2 - 8*p2.r1^2*s12 - 8*p2.r2*
         s12^2 + 2*p2.r2*d*s12^2 );

