l [interf4_4]= + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*
      Prop( - r1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*gs^4
       * ( 32*p2.r1*p2.r2*r1.r2 + 16*p2.r1*p2.r2*s12 + 32*p2.r1*p2.r2^2 + 8*
         p2.r1*r1.r2*s12 + 32*p2.r1*r1.r2^2 - 8*p2.r1*r1.r2^2*d + 32*p2.r1^2*
         p2.r2 + 16*p2.r1^2*r1.r2 + 8*p2.r2*r1.r2*s12 + 32*p2.r2*r1.r2^2 - 8*
         p2.r2*r1.r2^2*d + 16*p2.r2^2*r1.r2 + 16*r1.r2^2*s12 - 4*r1.r2^2*d*s12
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - r1
       - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*gs^4*Nc^2 * (  - 
         32*p2.r1*p2.r2*r1.r2 - 16*p2.r1*p2.r2*s12 - 32*p2.r1*p2.r2^2 - 8*
         p2.r1*r1.r2*s12 - 32*p2.r1*r1.r2^2 + 8*p2.r1*r1.r2^2*d - 32*p2.r1^2*
         p2.r2 - 16*p2.r1^2*r1.r2 - 8*p2.r2*r1.r2*s12 - 32*p2.r2*r1.r2^2 + 8*
         p2.r2*r1.r2^2*d - 16*p2.r2^2*r1.r2 - 16*r1.r2^2*s12 + 4*r1.r2^2*d*s12
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - r1
       - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^4 * (  - 48*
         p2.r1*p2.r2*r1.r2 + 16*p2.r1*p2.r2*r1.r2*d + 8*p2.r1*p2.r2*s12 - 8*
         p2.r1*r1.r2*s12 + 4*p2.r1*r1.r2*d*s12 + 16*p2.r1^2*p2.r2 - 16*p2.r1^2
         *r1.r2 + 8*p2.r1^2*r1.r2*d - 16*p2.r2*r1.r2*s12 + 4*p2.r2*r1.r2*d*s12
          - 32*p2.r2^2*r1.r2 + 8*p2.r2^2*r1.r2*d - 8*p2.r2^2*s12 - 16*p2.r2^3
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - r1
       - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^4*Nc^2 * ( 48*
         p2.r1*p2.r2*r1.r2 - 16*p2.r1*p2.r2*r1.r2*d - 8*p2.r1*p2.r2*s12 + 8*
         p2.r1*r1.r2*s12 - 4*p2.r1*r1.r2*d*s12 - 16*p2.r1^2*p2.r2 + 16*p2.r1^2
         *r1.r2 - 8*p2.r1^2*r1.r2*d + 16*p2.r2*r1.r2*s12 - 4*p2.r2*r1.r2*d*s12
          + 32*p2.r2^2*r1.r2 - 8*p2.r2^2*r1.r2*d + 8*p2.r2^2*s12 + 16*p2.r2^3
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - r1
       - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*gs^4 * (  - 48*
         p2.r1*p2.r2*r1.r2 + 16*p2.r1*p2.r2*r1.r2*d + 8*p2.r1*p2.r2*s12 + 16*
         p2.r1*p2.r2^2 - 16*p2.r1*r1.r2*s12 + 4*p2.r1*r1.r2*d*s12 - 32*p2.r1^2
         *r1.r2 + 8*p2.r1^2*r1.r2*d - 8*p2.r1^2*s12 - 16*p2.r1^3 - 8*p2.r2*
         r1.r2*s12 + 4*p2.r2*r1.r2*d*s12 - 16*p2.r2^2*r1.r2 + 8*p2.r2^2*r1.r2*
         d )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - r1
       - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*gs^4*Nc^2 * ( 48*
         p2.r1*p2.r2*r1.r2 - 16*p2.r1*p2.r2*r1.r2*d - 8*p2.r1*p2.r2*s12 - 16*
         p2.r1*p2.r2^2 + 16*p2.r1*r1.r2*s12 - 4*p2.r1*r1.r2*d*s12 + 32*p2.r1^2
         *r1.r2 - 8*p2.r1^2*r1.r2*d + 8*p2.r1^2*s12 + 16*p2.r1^3 + 8*p2.r2*
         r1.r2*s12 - 4*p2.r2*r1.r2*d*s12 + 16*p2.r2^2*r1.r2 - 8*p2.r2^2*r1.r2*
         d );

