l [interf5_2]= + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(
      p1 + r1)*Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r1,nu95)*
      gs^4*Nc^-1 * ( 8*r2(mu95)*p2.r1*p2.r2 - 8*r2(mu95)*p2.r1*p2.r2*d + 2*
         r2(mu95)*p2.r1*p2.r2*d^2 + 4*r2(mu95)*p2.r2*s12 - 4*r2(mu95)*p2.r2*d*
         s12 + r2(mu95)*p2.r2*d^2*s12 + 8*r2(mu95)*p2.r2^2 - 8*r2(mu95)*
         p2.r2^2*d + 2*r2(mu95)*p2.r2^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r1,nu95)*gs^4*Nc
       * (  - 16*r2(mu95)*p2.r1*p2.r2 + 16*r2(mu95)*p2.r1*p2.r2*d - 4*r2(mu95)
         *p2.r1*p2.r2*d^2 - 8*r2(mu95)*p2.r2*s12 + 8*r2(mu95)*p2.r2*d*s12 - 2*
         r2(mu95)*p2.r2*d^2*s12 - 16*r2(mu95)*p2.r2^2 + 16*r2(mu95)*p2.r2^2*d
          - 4*r2(mu95)*p2.r2^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r1,nu95)*gs^4*Nc^3
       * ( 8*r2(mu95)*p2.r1*p2.r2 - 8*r2(mu95)*p2.r1*p2.r2*d + 2*r2(mu95)*
         p2.r1*p2.r2*d^2 + 4*r2(mu95)*p2.r2*s12 - 4*r2(mu95)*p2.r2*d*s12 + 
         r2(mu95)*p2.r2*d^2*s12 + 8*r2(mu95)*p2.r2^2 - 8*r2(mu95)*p2.r2^2*d + 
         2*r2(mu95)*p2.r2^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r2,nu95)*gs^4*
      Nc^-1 * (  - 16*p1(mu95)*p2.r1*p2.r2 + 8*p1(mu95)*p2.r1*p2.r2*d - 8*
         p1(mu95)*p2.r2*s12 + 4*p1(mu95)*p2.r2*d*s12 - 16*p1(mu95)*p2.r2^2 + 8
         *p1(mu95)*p2.r2^2*d + 8*r1(mu95)*p2.r1*p2.r2 - 8*r1(mu95)*p2.r1*p2.r2
         *d + 2*r1(mu95)*p2.r1*p2.r2*d^2 + 4*r1(mu95)*p2.r2*s12 - 4*r1(mu95)*
         p2.r2*d*s12 + r1(mu95)*p2.r2*d^2*s12 + 8*r1(mu95)*p2.r2^2 - 8*
         r1(mu95)*p2.r2^2*d + 2*r1(mu95)*p2.r2^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r2,nu95)*gs^4*Nc
       * ( 32*p1(mu95)*p2.r1*p2.r2 - 16*p1(mu95)*p2.r1*p2.r2*d + 16*p1(mu95)*
         p2.r2*s12 - 8*p1(mu95)*p2.r2*d*s12 + 32*p1(mu95)*p2.r2^2 - 16*
         p1(mu95)*p2.r2^2*d - 16*r1(mu95)*p2.r1*p2.r2 + 16*r1(mu95)*p2.r1*
         p2.r2*d - 4*r1(mu95)*p2.r1*p2.r2*d^2 - 8*r1(mu95)*p2.r2*s12 + 8*
         r1(mu95)*p2.r2*d*s12 - 2*r1(mu95)*p2.r2*d^2*s12 - 16*r1(mu95)*p2.r2^2
          + 16*r1(mu95)*p2.r2^2*d - 4*r1(mu95)*p2.r2^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r2,nu95)*gs^4*Nc^3
       * (  - 16*p1(mu95)*p2.r1*p2.r2 + 8*p1(mu95)*p2.r1*p2.r2*d - 8*p1(mu95)*
         p2.r2*s12 + 4*p1(mu95)*p2.r2*d*s12 - 16*p1(mu95)*p2.r2^2 + 8*p1(mu95)
         *p2.r2^2*d + 8*r1(mu95)*p2.r1*p2.r2 - 8*r1(mu95)*p2.r1*p2.r2*d + 2*
         r1(mu95)*p2.r1*p2.r2*d^2 + 4*r1(mu95)*p2.r2*s12 - 4*r1(mu95)*p2.r2*d*
         s12 + r1(mu95)*p2.r2*d^2*s12 + 8*r1(mu95)*p2.r2^2 - 8*r1(mu95)*
         p2.r2^2*d + 2*r1(mu95)*p2.r2^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*gs^4*
      Nc^-1 * ( 16*p1.r2*p2.r1*p2.r2 - 8*p1.r2*p2.r1*p2.r2*d + 8*p1.r2*p2.r2*
         s12 - 4*p1.r2*p2.r2*d*s12 + 16*p1.r2*p2.r2^2 - 8*p1.r2*p2.r2^2*d - 8*
         p2.r1*p2.r2*r1.r2 + 8*p2.r1*p2.r2*r1.r2*d - 2*p2.r1*p2.r2*r1.r2*d^2
          - 4*p2.r2*r1.r2*s12 + 4*p2.r2*r1.r2*d*s12 - p2.r2*r1.r2*d^2*s12 - 8*
         p2.r2^2*r1.r2 + 8*p2.r2^2*r1.r2*d - 2*p2.r2^2*r1.r2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*gs^4*Nc
       * (  - 32*p1.r2*p2.r1*p2.r2 + 16*p1.r2*p2.r1*p2.r2*d - 16*p1.r2*p2.r2*
         s12 + 8*p1.r2*p2.r2*d*s12 - 32*p1.r2*p2.r2^2 + 16*p1.r2*p2.r2^2*d + 
         16*p2.r1*p2.r2*r1.r2 - 16*p2.r1*p2.r2*r1.r2*d + 4*p2.r1*p2.r2*r1.r2*
         d^2 + 8*p2.r2*r1.r2*s12 - 8*p2.r2*r1.r2*d*s12 + 2*p2.r2*r1.r2*d^2*s12
          + 16*p2.r2^2*r1.r2 - 16*p2.r2^2*r1.r2*d + 4*p2.r2^2*r1.r2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*gs^4*
      Nc^3 * ( 16*p1.r2*p2.r1*p2.r2 - 8*p1.r2*p2.r1*p2.r2*d + 8*p1.r2*p2.r2*
         s12 - 4*p1.r2*p2.r2*d*s12 + 16*p1.r2*p2.r2^2 - 8*p1.r2*p2.r2^2*d - 8*
         p2.r1*p2.r2*r1.r2 + 8*p2.r1*p2.r2*r1.r2*d - 2*p2.r1*p2.r2*r1.r2*d^2
          - 4*p2.r2*r1.r2*s12 + 4*p2.r2*r1.r2*d*s12 - p2.r2*r1.r2*d^2*s12 - 8*
         p2.r2^2*r1.r2 + 8*p2.r2^2*r1.r2*d - 2*p2.r2^2*r1.r2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,r2,nu95)*gs^4*
      Nc^-1 * (  - 16*p1(mu95)*p2.r1*p2.r2 + 8*p1(mu95)*p2.r1*p2.r2*d - 8*
         p1(mu95)*p2.r2*s12 + 4*p1(mu95)*p2.r2*d*s12 - 16*p1(mu95)*p2.r2^2 + 8
         *p1(mu95)*p2.r2^2*d + 24*p2(mu95)*p2.r1*p2.r2 - 16*p2(mu95)*p2.r1*
         p2.r2*d + 2*p2(mu95)*p2.r1*p2.r2*d^2 + 12*p2(mu95)*p2.r2*s12 - 8*
         p2(mu95)*p2.r2*d*s12 + p2(mu95)*p2.r2*d^2*s12 + 24*p2(mu95)*p2.r2^2
          - 16*p2(mu95)*p2.r2^2*d + 2*p2(mu95)*p2.r2^2*d^2 + 32*r1(mu95)*p2.r1
         *p2.r2 - 24*r1(mu95)*p2.r1*p2.r2*d + 4*r1(mu95)*p2.r1*p2.r2*d^2 + 16*
         r1(mu95)*p2.r2*s12 - 12*r1(mu95)*p2.r2*d*s12 + 2*r1(mu95)*p2.r2*d^2*
         s12 + 32*r1(mu95)*p2.r2^2 - 24*r1(mu95)*p2.r2^2*d + 4*r1(mu95)*
         p2.r2^2*d^2 + 16*r2(mu95)*p2.r1*p2.r2 - 8*r2(mu95)*p2.r1*p2.r2*d + 8*
         r2(mu95)*p2.r2*s12 - 4*r2(mu95)*p2.r2*d*s12 + 16*r2(mu95)*p2.r2^2 - 8
         *r2(mu95)*p2.r2^2*d )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,r2,nu95)*gs^4*Nc
       * ( 32*p1(mu95)*p2.r1*p2.r2 - 16*p1(mu95)*p2.r1*p2.r2*d + 16*p1(mu95)*
         p2.r2*s12 - 8*p1(mu95)*p2.r2*d*s12 + 32*p1(mu95)*p2.r2^2 - 16*
         p1(mu95)*p2.r2^2*d - 48*p2(mu95)*p2.r1*p2.r2 + 32*p2(mu95)*p2.r1*
         p2.r2*d - 4*p2(mu95)*p2.r1*p2.r2*d^2 - 24*p2(mu95)*p2.r2*s12 + 16*
         p2(mu95)*p2.r2*d*s12 - 2*p2(mu95)*p2.r2*d^2*s12 - 48*p2(mu95)*p2.r2^2
          + 32*p2(mu95)*p2.r2^2*d - 4*p2(mu95)*p2.r2^2*d^2 - 64*r1(mu95)*p2.r1
         *p2.r2 + 48*r1(mu95)*p2.r1*p2.r2*d - 8*r1(mu95)*p2.r1*p2.r2*d^2 - 32*
         r1(mu95)*p2.r2*s12 + 24*r1(mu95)*p2.r2*d*s12 - 4*r1(mu95)*p2.r2*d^2*
         s12 - 64*r1(mu95)*p2.r2^2 + 48*r1(mu95)*p2.r2^2*d - 8*r1(mu95)*
         p2.r2^2*d^2 - 32*r2(mu95)*p2.r1*p2.r2 + 16*r2(mu95)*p2.r1*p2.r2*d - 
         16*r2(mu95)*p2.r2*s12 + 8*r2(mu95)*p2.r2*d*s12 - 32*r2(mu95)*p2.r2^2
          + 16*r2(mu95)*p2.r2^2*d )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,r2,nu95)*gs^4*Nc^3
       * (  - 16*p1(mu95)*p2.r1*p2.r2 + 8*p1(mu95)*p2.r1*p2.r2*d - 8*p1(mu95)*
         p2.r2*s12 + 4*p1(mu95)*p2.r2*d*s12 - 16*p1(mu95)*p2.r2^2 + 8*p1(mu95)
         *p2.r2^2*d + 24*p2(mu95)*p2.r1*p2.r2 - 16*p2(mu95)*p2.r1*p2.r2*d + 2*
         p2(mu95)*p2.r1*p2.r2*d^2 + 12*p2(mu95)*p2.r2*s12 - 8*p2(mu95)*p2.r2*d
         *s12 + p2(mu95)*p2.r2*d^2*s12 + 24*p2(mu95)*p2.r2^2 - 16*p2(mu95)*
         p2.r2^2*d + 2*p2(mu95)*p2.r2^2*d^2 + 32*r1(mu95)*p2.r1*p2.r2 - 24*
         r1(mu95)*p2.r1*p2.r2*d + 4*r1(mu95)*p2.r1*p2.r2*d^2 + 16*r1(mu95)*
         p2.r2*s12 - 12*r1(mu95)*p2.r2*d*s12 + 2*r1(mu95)*p2.r2*d^2*s12 + 32*
         r1(mu95)*p2.r2^2 - 24*r1(mu95)*p2.r2^2*d + 4*r1(mu95)*p2.r2^2*d^2 + 
         16*r2(mu95)*p2.r1*p2.r2 - 8*r2(mu95)*p2.r1*p2.r2*d + 8*r2(mu95)*p2.r2
         *s12 - 4*r2(mu95)*p2.r2*d*s12 + 16*r2(mu95)*p2.r2^2 - 8*r2(mu95)*
         p2.r2^2*d )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^4*
      Nc^-1 * ( 16*p1.r2*p2.r1*p2.r2 - 8*p1.r2*p2.r1*p2.r2*d + 8*p1.r2*p2.r2*
         s12 - 4*p1.r2*p2.r2*d*s12 + 16*p1.r2*p2.r2^2 - 8*p1.r2*p2.r2^2*d - 32
         *p2.r1*p2.r2*r1.r2 + 24*p2.r1*p2.r2*r1.r2*d - 4*p2.r1*p2.r2*r1.r2*d^2
          - 24*p2.r1*p2.r2^2 + 16*p2.r1*p2.r2^2*d - 2*p2.r1*p2.r2^2*d^2 - 16*
         p2.r2*r1.r2*s12 + 12*p2.r2*r1.r2*d*s12 - 2*p2.r2*r1.r2*d^2*s12 - 32*
         p2.r2^2*r1.r2 + 24*p2.r2^2*r1.r2*d - 4*p2.r2^2*r1.r2*d^2 - 12*p2.r2^2
         *s12 + 8*p2.r2^2*d*s12 - p2.r2^2*d^2*s12 - 24*p2.r2^3 + 16*p2.r2^3*d
          - 2*p2.r2^3*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^4*Nc
       * (  - 32*p1.r2*p2.r1*p2.r2 + 16*p1.r2*p2.r1*p2.r2*d - 16*p1.r2*p2.r2*
         s12 + 8*p1.r2*p2.r2*d*s12 - 32*p1.r2*p2.r2^2 + 16*p1.r2*p2.r2^2*d + 
         64*p2.r1*p2.r2*r1.r2 - 48*p2.r1*p2.r2*r1.r2*d + 8*p2.r1*p2.r2*r1.r2*
         d^2 + 48*p2.r1*p2.r2^2 - 32*p2.r1*p2.r2^2*d + 4*p2.r1*p2.r2^2*d^2 + 
         32*p2.r2*r1.r2*s12 - 24*p2.r2*r1.r2*d*s12 + 4*p2.r2*r1.r2*d^2*s12 + 
         64*p2.r2^2*r1.r2 - 48*p2.r2^2*r1.r2*d + 8*p2.r2^2*r1.r2*d^2 + 24*
         p2.r2^2*s12 - 16*p2.r2^2*d*s12 + 2*p2.r2^2*d^2*s12 + 48*p2.r2^3 - 32*
         p2.r2^3*d + 4*p2.r2^3*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^4*
      Nc^3 * ( 16*p1.r2*p2.r1*p2.r2 - 8*p1.r2*p2.r1*p2.r2*d + 8*p1.r2*p2.r2*
         s12 - 4*p1.r2*p2.r2*d*s12 + 16*p1.r2*p2.r2^2 - 8*p1.r2*p2.r2^2*d - 32
         *p2.r1*p2.r2*r1.r2 + 24*p2.r1*p2.r2*r1.r2*d - 4*p2.r1*p2.r2*r1.r2*d^2
          - 24*p2.r1*p2.r2^2 + 16*p2.r1*p2.r2^2*d - 2*p2.r1*p2.r2^2*d^2 - 16*
         p2.r2*r1.r2*s12 + 12*p2.r2*r1.r2*d*s12 - 2*p2.r2*r1.r2*d^2*s12 - 32*
         p2.r2^2*r1.r2 + 24*p2.r2^2*r1.r2*d - 4*p2.r2^2*r1.r2*d^2 - 12*p2.r2^2
         *s12 + 8*p2.r2^2*d*s12 - p2.r2^2*d^2*s12 - 24*p2.r2^3 + 16*p2.r2^3*d
          - 2*p2.r2^3*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*gs^4*
      Nc^-1 * ( 16*p1.r2*p2.r1*p2.r2 - 8*p1.r2*p2.r1*p2.r2*d + 8*p1.r2*p2.r2*
         s12 - 4*p1.r2*p2.r2*d*s12 + 16*p1.r2*p2.r2^2 - 8*p1.r2*p2.r2^2*d + 16
         *p2.r1*p2.r2*r1.r2 - 8*p2.r1*p2.r2*r1.r2*d + 12*p2.r1*p2.r2*s12 - 8*
         p2.r1*p2.r2*d*s12 + p2.r1*p2.r2*d^2*s12 + 24*p2.r1*p2.r2^2 - 16*p2.r1
         *p2.r2^2*d + 2*p2.r1*p2.r2^2*d^2 + 24*p2.r1^2*p2.r2 - 16*p2.r1^2*
         p2.r2*d + 2*p2.r1^2*p2.r2*d^2 + 8*p2.r2*r1.r2*s12 - 4*p2.r2*r1.r2*d*
         s12 + 16*p2.r2^2*r1.r2 - 8*p2.r2^2*r1.r2*d )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*gs^4*Nc
       * (  - 32*p1.r2*p2.r1*p2.r2 + 16*p1.r2*p2.r1*p2.r2*d - 16*p1.r2*p2.r2*
         s12 + 8*p1.r2*p2.r2*d*s12 - 32*p1.r2*p2.r2^2 + 16*p1.r2*p2.r2^2*d - 
         32*p2.r1*p2.r2*r1.r2 + 16*p2.r1*p2.r2*r1.r2*d - 24*p2.r1*p2.r2*s12 + 
         16*p2.r1*p2.r2*d*s12 - 2*p2.r1*p2.r2*d^2*s12 - 48*p2.r1*p2.r2^2 + 32*
         p2.r1*p2.r2^2*d - 4*p2.r1*p2.r2^2*d^2 - 48*p2.r1^2*p2.r2 + 32*p2.r1^2
         *p2.r2*d - 4*p2.r1^2*p2.r2*d^2 - 16*p2.r2*r1.r2*s12 + 8*p2.r2*r1.r2*d
         *s12 - 32*p2.r2^2*r1.r2 + 16*p2.r2^2*r1.r2*d )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*gs^4*
      Nc^3 * ( 16*p1.r2*p2.r1*p2.r2 - 8*p1.r2*p2.r1*p2.r2*d + 8*p1.r2*p2.r2*
         s12 - 4*p1.r2*p2.r2*d*s12 + 16*p1.r2*p2.r2^2 - 8*p1.r2*p2.r2^2*d + 16
         *p2.r1*p2.r2*r1.r2 - 8*p2.r1*p2.r2*r1.r2*d + 12*p2.r1*p2.r2*s12 - 8*
         p2.r1*p2.r2*d*s12 + p2.r1*p2.r2*d^2*s12 + 24*p2.r1*p2.r2^2 - 16*p2.r1
         *p2.r2^2*d + 2*p2.r1*p2.r2^2*d^2 + 24*p2.r1^2*p2.r2 - 16*p2.r1^2*
         p2.r2*d + 2*p2.r1^2*p2.r2*d^2 + 8*p2.r2*r1.r2*s12 - 4*p2.r2*r1.r2*d*
         s12 + 16*p2.r2^2*r1.r2 - 8*p2.r2^2*r1.r2*d )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,r2,nu95)*gs^4*
      Nc^-1 * ( 24*p1(mu95)*p2.r1*p2.r2 - 16*p1(mu95)*p2.r1*p2.r2*d + 2*
         p1(mu95)*p2.r1*p2.r2*d^2 + 12*p1(mu95)*p2.r2*s12 - 8*p1(mu95)*p2.r2*d
         *s12 + p1(mu95)*p2.r2*d^2*s12 + 24*p1(mu95)*p2.r2^2 - 16*p1(mu95)*
         p2.r2^2*d + 2*p1(mu95)*p2.r2^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,r2,nu95)*gs^4*Nc
       * (  - 48*p1(mu95)*p2.r1*p2.r2 + 32*p1(mu95)*p2.r1*p2.r2*d - 4*p1(mu95)
         *p2.r1*p2.r2*d^2 - 24*p1(mu95)*p2.r2*s12 + 16*p1(mu95)*p2.r2*d*s12 - 
         2*p1(mu95)*p2.r2*d^2*s12 - 48*p1(mu95)*p2.r2^2 + 32*p1(mu95)*p2.r2^2*
         d - 4*p1(mu95)*p2.r2^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,r2,nu95)*gs^4*Nc^3
       * ( 24*p1(mu95)*p2.r1*p2.r2 - 16*p1(mu95)*p2.r1*p2.r2*d + 2*p1(mu95)*
         p2.r1*p2.r2*d^2 + 12*p1(mu95)*p2.r2*s12 - 8*p1(mu95)*p2.r2*d*s12 + 
         p1(mu95)*p2.r2*d^2*s12 + 24*p1(mu95)*p2.r2^2 - 16*p1(mu95)*p2.r2^2*d
          + 2*p1(mu95)*p2.r2^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^4*
      Nc^-1 * (  - 24*p1.r2*p2.r1*p2.r2 + 16*p1.r2*p2.r1*p2.r2*d - 2*p1.r2*
         p2.r1*p2.r2*d^2 - 12*p1.r2*p2.r2*s12 + 8*p1.r2*p2.r2*d*s12 - p1.r2*
         p2.r2*d^2*s12 - 24*p1.r2*p2.r2^2 + 16*p1.r2*p2.r2^2*d - 2*p1.r2*
         p2.r2^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^4*Nc
       * ( 48*p1.r2*p2.r1*p2.r2 - 32*p1.r2*p2.r1*p2.r2*d + 4*p1.r2*p2.r1*p2.r2
         *d^2 + 24*p1.r2*p2.r2*s12 - 16*p1.r2*p2.r2*d*s12 + 2*p1.r2*p2.r2*d^2*
         s12 + 48*p1.r2*p2.r2^2 - 32*p1.r2*p2.r2^2*d + 4*p1.r2*p2.r2^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^4*
      Nc^3 * (  - 24*p1.r2*p2.r1*p2.r2 + 16*p1.r2*p2.r1*p2.r2*d - 2*p1.r2*
         p2.r1*p2.r2*d^2 - 12*p1.r2*p2.r2*s12 + 8*p1.r2*p2.r2*d*s12 - p1.r2*
         p2.r2*d^2*s12 - 24*p1.r2*p2.r2^2 + 16*p1.r2*p2.r2^2*d - 2*p1.r2*
         p2.r2^2*d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*gs^4*
      Nc^-1 * ( 24*p1.r1*p2.r1*p2.r2 - 16*p1.r1*p2.r1*p2.r2*d + 2*p1.r1*p2.r1*
         p2.r2*d^2 + 12*p1.r1*p2.r2*s12 - 8*p1.r1*p2.r2*d*s12 + p1.r1*p2.r2*
         d^2*s12 + 24*p1.r1*p2.r2^2 - 16*p1.r1*p2.r2^2*d + 2*p1.r1*p2.r2^2*d^2
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*gs^4*Nc
       * (  - 48*p1.r1*p2.r1*p2.r2 + 32*p1.r1*p2.r1*p2.r2*d - 4*p1.r1*p2.r1*
         p2.r2*d^2 - 24*p1.r1*p2.r2*s12 + 16*p1.r1*p2.r2*d*s12 - 2*p1.r1*p2.r2
         *d^2*s12 - 48*p1.r1*p2.r2^2 + 32*p1.r1*p2.r2^2*d - 4*p1.r1*p2.r2^2*
         d^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*gs^4*
      Nc^3 * ( 24*p1.r1*p2.r1*p2.r2 - 16*p1.r1*p2.r1*p2.r2*d + 2*p1.r1*p2.r1*
         p2.r2*d^2 + 12*p1.r1*p2.r2*s12 - 8*p1.r1*p2.r2*d*s12 + p1.r1*p2.r2*
         d^2*s12 + 24*p1.r1*p2.r2^2 - 16*p1.r1*p2.r2^2*d + 2*p1.r1*p2.r2^2*d^2
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4*
      Nc^-1 * (  - 12*p2.r1*p2.r2*s12 + 8*p2.r1*p2.r2*d*s12 - p2.r1*p2.r2*d^2*
         s12 - 6*p2.r2*s12^2 + 4*p2.r2*d*s12^2 - 1/2*p2.r2*d^2*s12^2 - 12*
         p2.r2^2*s12 + 8*p2.r2^2*d*s12 - p2.r2^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4*Nc
       * ( 24*p2.r1*p2.r2*s12 - 16*p2.r1*p2.r2*d*s12 + 2*p2.r1*p2.r2*d^2*s12
          + 12*p2.r2*s12^2 - 8*p2.r2*d*s12^2 + p2.r2*d^2*s12^2 + 24*p2.r2^2*
         s12 - 16*p2.r2^2*d*s12 + 2*p2.r2^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)*Prop(p1 + r1)*
      Prop( - p2 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4*
      Nc^3 * (  - 12*p2.r1*p2.r2*s12 + 8*p2.r1*p2.r2*d*s12 - p2.r1*p2.r2*d^2*
         s12 - 6*p2.r2*s12^2 + 4*p2.r2*d*s12^2 - 1/2*p2.r2*d^2*s12^2 - 12*
         p2.r2^2*s12 + 8*p2.r2^2*d*s12 - p2.r2^2*d^2*s12 );

