L Had= + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)^2*gv(ti)*cgv(tj)*Den(cut
      , - q.p1 + q.p2*u)*gs^2 * ( 4*p1(mu95)*p2(nu95)*p2.r1*[Nc^2-1]*s12 - 2*
         p1(mu95)*p2(nu95)*p2.r1*d*[Nc^2-1]*s12 + 8*p1(mu95)*p2(nu95)*p2.r1^2*
         [Nc^2-1] - 4*p1(mu95)*p2(nu95)*p2.r1^2*d*[Nc^2-1] + 4*p1(nu95)*
         p2(mu95)*p2.r1*[Nc^2-1]*s12 - 2*p1(nu95)*p2(mu95)*p2.r1*d*[Nc^2-1]*
         s12 + 8*p1(nu95)*p2(mu95)*p2.r1^2*[Nc^2-1] - 4*p1(nu95)*p2(mu95)*
         p2.r1^2*d*[Nc^2-1] )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)^2*gv(ti)*cgv(tj)*Den(cut
      , - q.p1 + q.p2*u)*d_(mu95,nu95)*gs^2 * (  - 2*p2.r1*[Nc^2-1]*s12^2 + 
         p2.r1*d*[Nc^2-1]*s12^2 - 4*p2.r1^2*[Nc^2-1]*s12 + 2*p2.r1^2*d*
         [Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)^2*gv(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*gs^2 * ( 4*p2.r1*[Nc^2-1]*s12 - 2
         *p2.r1*d*[Nc^2-1]*s12 + 8*p2.r1^2*[Nc^2-1] - 4*p2.r1^2*d*[Nc^2-1] )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)^2*ga(ti)*cgv(tj)*Den(cut
      , - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*gs^2 * ( 4*p2.r1*[Nc^2-1]*s12 - 2
         *p2.r1*d*[Nc^2-1]*s12 + 8*p2.r1^2*[Nc^2-1] - 4*p2.r1^2*d*[Nc^2-1] )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)^2*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*gs^2 * ( 12*p1(mu95)*p2(nu95)*p2.r1*[Nc^2-1]*s12 - 16
         *p1(mu95)*p2(nu95)*p2.r1*d*[Nc^2-1]*s12 + 7*p1(mu95)*p2(nu95)*p2.r1*
         d^2*[Nc^2-1]*s12 - p1(mu95)*p2(nu95)*p2.r1*d^3*[Nc^2-1]*s12 + 24*
         p1(mu95)*p2(nu95)*p2.r1^2*[Nc^2-1] - 32*p1(mu95)*p2(nu95)*p2.r1^2*d*
         [Nc^2-1] + 14*p1(mu95)*p2(nu95)*p2.r1^2*d^2*[Nc^2-1] - 2*p1(mu95)*
         p2(nu95)*p2.r1^2*d^3*[Nc^2-1] + 12*p1(nu95)*p2(mu95)*p2.r1*[Nc^2-1]*
         s12 - 16*p1(nu95)*p2(mu95)*p2.r1*d*[Nc^2-1]*s12 + 7*p1(nu95)*p2(mu95)
         *p2.r1*d^2*[Nc^2-1]*s12 - p1(nu95)*p2(mu95)*p2.r1*d^3*[Nc^2-1]*s12 + 
         24*p1(nu95)*p2(mu95)*p2.r1^2*[Nc^2-1] - 32*p1(nu95)*p2(mu95)*p2.r1^2*
         d*[Nc^2-1] + 14*p1(nu95)*p2(mu95)*p2.r1^2*d^2*[Nc^2-1] - 2*p1(nu95)*
         p2(mu95)*p2.r1^2*d^3*[Nc^2-1] )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)^2*ga(ti)*cga(tj)*Den(cut
      , - q.p1 + q.p2*u)*d_(mu95,nu95)*gs^2 * (  - 14*p2.r1*[Nc^2-1]*s12^2 + 
         62/3*p2.r1*d*[Nc^2-1]*s12^2 - 65/6*p2.r1*d^2*[Nc^2-1]*s12^2 + 7/3*
         p2.r1*d^3*[Nc^2-1]*s12^2 - 1/6*p2.r1*d^4*[Nc^2-1]*s12^2 - 28*p2.r1^2*
         [Nc^2-1]*s12 + 124/3*p2.r1^2*d*[Nc^2-1]*s12 - 65/3*p2.r1^2*d^2*
         [Nc^2-1]*s12 + 14/3*p2.r1^2*d^3*[Nc^2-1]*s12 - 1/3*p2.r1^2*d^4*
         [Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)*Prop( - p1 - p2)*gv(ti)*
      cgv(tj)*Den(cut, - q.p1 + q.p2*u)*gs^2 * ( 8*p1(mu95)*p1(nu95)*p2.r1*
         [Nc^2-1]*s12 + 16*p1(mu95)*p1(nu95)*p2.r1^2*[Nc^2-1] - 8*p1(mu95)*
         p2(nu95)*p1.r1*p2.r1*[Nc^2-1] - 4*p1(mu95)*p2(nu95)*p1.r1*[Nc^2-1]*
         s12 + 8*p1(mu95)*p2(nu95)*p2.r1*[Nc^2-1]*s12 - 2*p1(mu95)*p2(nu95)*
         p2.r1*d*[Nc^2-1]*s12 + 16*p1(mu95)*p2(nu95)*p2.r1^2*[Nc^2-1] - 4*
         p1(mu95)*p2(nu95)*p2.r1^2*d*[Nc^2-1] - 2*p1(mu95)*r1(nu95)*[Nc^2-1]*
         s12^2 - 16*p1(mu95)*r1(nu95)*p1.r1*p2.r1*[Nc^2-1] - 8*p1(mu95)*
         r1(nu95)*p1.r1*[Nc^2-1]*s12 - 8*p1(mu95)*r1(nu95)*p2.r1*[Nc^2-1]*s12
          - 8*p1(mu95)*r1(nu95)*p2.r1^2*[Nc^2-1] - 8*p1(nu95)*p2(mu95)*p1.r1*
         p2.r1*[Nc^2-1] - 4*p1(nu95)*p2(mu95)*p1.r1*[Nc^2-1]*s12 + 8*p1(nu95)*
         p2(mu95)*p2.r1*[Nc^2-1]*s12 - 2*p1(nu95)*p2(mu95)*p2.r1*d*[Nc^2-1]*
         s12 + 16*p1(nu95)*p2(mu95)*p2.r1^2*[Nc^2-1] - 4*p1(nu95)*p2(mu95)*
         p2.r1^2*d*[Nc^2-1] - 2*p1(nu95)*r1(mu95)*[Nc^2-1]*s12^2 - 16*p1(nu95)
         *r1(mu95)*p1.r1*p2.r1*[Nc^2-1] - 8*p1(nu95)*r1(mu95)*p1.r1*[Nc^2-1]*
         s12 - 8*p1(nu95)*r1(mu95)*p2.r1*[Nc^2-1]*s12 - 8*p1(nu95)*r1(mu95)*
         p2.r1^2*[Nc^2-1] - 32*p2(mu95)*p2(nu95)*p1.r1*p2.r1*[Nc^2-1] + 8*
         p2(mu95)*p2(nu95)*p1.r1*p2.r1*d*[Nc^2-1] - 16*p2(mu95)*p2(nu95)*p1.r1
         *[Nc^2-1]*s12 + 4*p2(mu95)*p2(nu95)*p1.r1*d*[Nc^2-1]*s12 + 4*p2(mu95)
         *r1(nu95)*[Nc^2-1]*s12^2 - p2(mu95)*r1(nu95)*d*[Nc^2-1]*s12^2 - 8*
         p2(mu95)*r1(nu95)*p1.r1*p2.r1*[Nc^2-1] - 4*p2(mu95)*r1(nu95)*p1.r1*
         [Nc^2-1]*s12 + 8*p2(mu95)*r1(nu95)*p2.r1*[Nc^2-1]*s12 - 2*p2(mu95)*
         r1(nu95)*p2.r1*d*[Nc^2-1]*s12 + 4*p2(nu95)*r1(mu95)*[Nc^2-1]*s12^2 - 
         p2(nu95)*r1(mu95)*d*[Nc^2-1]*s12^2 - 8*p2(nu95)*r1(mu95)*p1.r1*p2.r1*
         [Nc^2-1] - 4*p2(nu95)*r1(mu95)*p1.r1*[Nc^2-1]*s12 + 8*p2(nu95)*
         r1(mu95)*p2.r1*[Nc^2-1]*s12 - 2*p2(nu95)*r1(mu95)*p2.r1*d*[Nc^2-1]*
         s12 + 4*r1(mu95)*r1(nu95)*[Nc^2-1]*s12^2 + 8*r1(mu95)*r1(nu95)*p2.r1*
         [Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)*Prop( - p1 - p2)*gv(ti)*
      cgv(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*gs^2 * ( 16*p1.r1*p2.r1*
         [Nc^2-1]*s12 + 16*p1.r1*p2.r1^2*[Nc^2-1] + 4*p1.r1*[Nc^2-1]*s12^2 + 
         16*p1.r1^2*p2.r1*[Nc^2-1] + 8*p1.r1^2*[Nc^2-1]*s12 - 8*p2.r1*[Nc^2-1]
         *s12^2 + 2*p2.r1*d*[Nc^2-1]*s12^2 - 16*p2.r1^2*[Nc^2-1]*s12 + 4*
         p2.r1^2*d*[Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)*Prop( - p1 - p2)*gv(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r1,nu95)*gs^2 * (  - 16*
         p2(mu95)*[Nc^2-1]*s12 + 4*p2(mu95)*d*[Nc^2-1]*s12 - 32*p2(mu95)*p2.r1
         *[Nc^2-1] + 8*p2(mu95)*p2.r1*d*[Nc^2-1] )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)*Prop( - p1 - p2)*gv(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*gs^2 * (  - 8*
         p1.r1*p2.r1*[Nc^2-1] - 4*p1.r1*[Nc^2-1]*s12 + 8*p2.r1*[Nc^2-1]*s12 - 
         2*p2.r1*d*[Nc^2-1]*s12 + 16*p2.r1^2*[Nc^2-1] - 4*p2.r1^2*d*[Nc^2-1] )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)*Prop( - p1 - p2)*gv(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^2 * (  - 2*
         [Nc^2-1]*s12^2 - 16*p1.r1*p2.r1*[Nc^2-1] - 8*p1.r1*[Nc^2-1]*s12 - 8*
         p2.r1*[Nc^2-1]*s12 - 8*p2.r1^2*[Nc^2-1] )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)*Prop( - p1 - p2)*gv(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^2 * ( 4*
         [Nc^2-1]*s12^2 - d*[Nc^2-1]*s12^2 - 8*p1.r1*p2.r1*[Nc^2-1] - 4*p1.r1*
         [Nc^2-1]*s12 + 8*p2.r1*[Nc^2-1]*s12 - 2*p2.r1*d*[Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)*Prop( - p1 - p2)*ga(ti)*
      cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r1,mu95)*gs^2 * ( 16*p2(nu95)
         *[Nc^2-1]*s12 - 4*p2(nu95)*d*[Nc^2-1]*s12 + 32*p2(nu95)*p2.r1*
         [Nc^2-1] - 8*p2(nu95)*p2.r1*d*[Nc^2-1] )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)*Prop( - p1 - p2)*ga(ti)*
      cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*gs^2 * (  - 8*
         p1.r1*p2.r1*[Nc^2-1] - 4*p1.r1*[Nc^2-1]*s12 + 8*p2.r1*[Nc^2-1]*s12 - 
         2*p2.r1*d*[Nc^2-1]*s12 + 16*p2.r1^2*[Nc^2-1] - 4*p2.r1^2*d*[Nc^2-1] )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)*Prop( - p1 - p2)*ga(ti)*
      cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^2 * (  - 2*
         [Nc^2-1]*s12^2 - 16*p1.r1*p2.r1*[Nc^2-1] - 8*p1.r1*[Nc^2-1]*s12 - 8*
         p2.r1*[Nc^2-1]*s12 - 8*p2.r1^2*[Nc^2-1] )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)*Prop( - p1 - p2)*ga(ti)*
      cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^2 * ( 4*
         [Nc^2-1]*s12^2 - d*[Nc^2-1]*s12^2 - 8*p1.r1*p2.r1*[Nc^2-1] - 4*p1.r1*
         [Nc^2-1]*s12 + 8*p2.r1*[Nc^2-1]*s12 - 2*p2.r1*d*[Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)*Prop( - p1 - p2)*ga(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*gs^2 * ( 24*p1(mu95)*p1(nu95)*p2.r1*
         [Nc^2-1]*s12 - 20*p1(mu95)*p1(nu95)*p2.r1*d*[Nc^2-1]*s12 + 4*p1(mu95)
         *p1(nu95)*p2.r1*d^2*[Nc^2-1]*s12 + 48*p1(mu95)*p1(nu95)*p2.r1^2*
         [Nc^2-1] - 40*p1(mu95)*p1(nu95)*p2.r1^2*d*[Nc^2-1] + 8*p1(mu95)*
         p1(nu95)*p2.r1^2*d^2*[Nc^2-1] - 24*p1(mu95)*p2(nu95)*p1.r1*p2.r1*
         [Nc^2-1] + 20*p1(mu95)*p2(nu95)*p1.r1*p2.r1*d*[Nc^2-1] - 4*p1(mu95)*
         p2(nu95)*p1.r1*p2.r1*d^2*[Nc^2-1] - 12*p1(mu95)*p2(nu95)*p1.r1*
         [Nc^2-1]*s12 + 10*p1(mu95)*p2(nu95)*p1.r1*d*[Nc^2-1]*s12 - 2*p1(mu95)
         *p2(nu95)*p1.r1*d^2*[Nc^2-1]*s12 + 120*p1(mu95)*p2(nu95)*p2.r1*
         [Nc^2-1]*s12 - 82*p1(mu95)*p2(nu95)*p2.r1*d*[Nc^2-1]*s12 + 17*
         p1(mu95)*p2(nu95)*p2.r1*d^2*[Nc^2-1]*s12 - p1(mu95)*p2(nu95)*p2.r1*
         d^3*[Nc^2-1]*s12 + 240*p1(mu95)*p2(nu95)*p2.r1^2*[Nc^2-1] - 164*
         p1(mu95)*p2(nu95)*p2.r1^2*d*[Nc^2-1] + 34*p1(mu95)*p2(nu95)*p2.r1^2*
         d^2*[Nc^2-1] - 2*p1(mu95)*p2(nu95)*p2.r1^2*d^3*[Nc^2-1] - 6*p1(mu95)*
         r1(nu95)*[Nc^2-1]*s12^2 + 5*p1(mu95)*r1(nu95)*d*[Nc^2-1]*s12^2 - 
         p1(mu95)*r1(nu95)*d^2*[Nc^2-1]*s12^2 - 48*p1(mu95)*r1(nu95)*p1.r1*
         p2.r1*[Nc^2-1] + 40*p1(mu95)*r1(nu95)*p1.r1*p2.r1*d*[Nc^2-1] - 8*
         p1(mu95)*r1(nu95)*p1.r1*p2.r1*d^2*[Nc^2-1] - 24*p1(mu95)*r1(nu95)*
         p1.r1*[Nc^2-1]*s12 + 20*p1(mu95)*r1(nu95)*p1.r1*d*[Nc^2-1]*s12 - 4*
         p1(mu95)*r1(nu95)*p1.r1*d^2*[Nc^2-1]*s12 - 24*p1(mu95)*r1(nu95)*p2.r1
         *[Nc^2-1]*s12 + 20*p1(mu95)*r1(nu95)*p2.r1*d*[Nc^2-1]*s12 - 4*
         p1(mu95)*r1(nu95)*p2.r1*d^2*[Nc^2-1]*s12 - 24*p1(mu95)*r1(nu95)*
         p2.r1^2*[Nc^2-1] + 20*p1(mu95)*r1(nu95)*p2.r1^2*d*[Nc^2-1] - 4*
         p1(mu95)*r1(nu95)*p2.r1^2*d^2*[Nc^2-1] - 24*p1(nu95)*p2(mu95)*p1.r1*
         p2.r1*[Nc^2-1] + 20*p1(nu95)*p2(mu95)*p1.r1*p2.r1*d*[Nc^2-1] - 4*
         p1(nu95)*p2(mu95)*p1.r1*p2.r1*d^2*[Nc^2-1] - 12*p1(nu95)*p2(mu95)*
         p1.r1*[Nc^2-1]*s12 + 10*p1(nu95)*p2(mu95)*p1.r1*d*[Nc^2-1]*s12 - 2*
         p1(nu95)*p2(mu95)*p1.r1*d^2*[Nc^2-1]*s12 + 120*p1(nu95)*p2(mu95)*
         p2.r1*[Nc^2-1]*s12 - 82*p1(nu95)*p2(mu95)*p2.r1*d*[Nc^2-1]*s12 + 17*
         p1(nu95)*p2(mu95)*p2.r1*d^2*[Nc^2-1]*s12 - p1(nu95)*p2(mu95)*p2.r1*
         d^3*[Nc^2-1]*s12 + 240*p1(nu95)*p2(mu95)*p2.r1^2*[Nc^2-1] - 164*
         p1(nu95)*p2(mu95)*p2.r1^2*d*[Nc^2-1] + 34*p1(nu95)*p2(mu95)*p2.r1^2*
         d^2*[Nc^2-1] - 2*p1(nu95)*p2(mu95)*p2.r1^2*d^3*[Nc^2-1] - 6*p1(nu95)*
         r1(mu95)*[Nc^2-1]*s12^2 + 5*p1(nu95)*r1(mu95)*d*[Nc^2-1]*s12^2 - 
         p1(nu95)*r1(mu95)*d^2*[Nc^2-1]*s12^2 - 48*p1(nu95)*r1(mu95)*p1.r1*
         p2.r1*[Nc^2-1] + 40*p1(nu95)*r1(mu95)*p1.r1*p2.r1*d*[Nc^2-1] - 8*
         p1(nu95)*r1(mu95)*p1.r1*p2.r1*d^2*[Nc^2-1] - 24*p1(nu95)*r1(mu95)*
         p1.r1*[Nc^2-1]*s12 + 20*p1(nu95)*r1(mu95)*p1.r1*d*[Nc^2-1]*s12 - 4*
         p1(nu95)*r1(mu95)*p1.r1*d^2*[Nc^2-1]*s12 - 24*p1(nu95)*r1(mu95)*p2.r1
         *[Nc^2-1]*s12 + 20*p1(nu95)*r1(mu95)*p2.r1*d*[Nc^2-1]*s12 - 4*
         p1(nu95)*r1(mu95)*p2.r1*d^2*[Nc^2-1]*s12 - 24*p1(nu95)*r1(mu95)*
         p2.r1^2*[Nc^2-1] + 20*p1(nu95)*r1(mu95)*p2.r1^2*d*[Nc^2-1] - 4*
         p1(nu95)*r1(mu95)*p2.r1^2*d^2*[Nc^2-1] - 480*p2(mu95)*p2(nu95)*p1.r1*
         p2.r1*[Nc^2-1] + 328*p2(mu95)*p2(nu95)*p1.r1*p2.r1*d*[Nc^2-1] - 68*
         p2(mu95)*p2(nu95)*p1.r1*p2.r1*d^2*[Nc^2-1] + 4*p2(mu95)*p2(nu95)*
         p1.r1*p2.r1*d^3*[Nc^2-1] - 240*p2(mu95)*p2(nu95)*p1.r1*[Nc^2-1]*s12
          + 164*p2(mu95)*p2(nu95)*p1.r1*d*[Nc^2-1]*s12 - 34*p2(mu95)*p2(nu95)*
         p1.r1*d^2*[Nc^2-1]*s12 + 2*p2(mu95)*p2(nu95)*p1.r1*d^3*[Nc^2-1]*s12
          + 60*p2(mu95)*r1(nu95)*[Nc^2-1]*s12^2 - 41*p2(mu95)*r1(nu95)*d*
         [Nc^2-1]*s12^2 + 17/2*p2(mu95)*r1(nu95)*d^2*[Nc^2-1]*s12^2 - 1/2*
         p2(mu95)*r1(nu95)*d^3*[Nc^2-1]*s12^2 - 24*p2(mu95)*r1(nu95)*p1.r1*
         p2.r1*[Nc^2-1] + 20*p2(mu95)*r1(nu95)*p1.r1*p2.r1*d*[Nc^2-1] - 4*
         p2(mu95)*r1(nu95)*p1.r1*p2.r1*d^2*[Nc^2-1] - 12*p2(mu95)*r1(nu95)*
         p1.r1*[Nc^2-1]*s12 + 10*p2(mu95)*r1(nu95)*p1.r1*d*[Nc^2-1]*s12 - 2*
         p2(mu95)*r1(nu95)*p1.r1*d^2*[Nc^2-1]*s12 + 120*p2(mu95)*r1(nu95)*
         p2.r1*[Nc^2-1]*s12 - 82*p2(mu95)*r1(nu95)*p2.r1*d*[Nc^2-1]*s12 + 17*
         p2(mu95)*r1(nu95)*p2.r1*d^2*[Nc^2-1]*s12 - p2(mu95)*r1(nu95)*p2.r1*
         d^3*[Nc^2-1]*s12 + 60*p2(nu95)*r1(mu95)*[Nc^2-1]*s12^2 - 41*p2(nu95)*
         r1(mu95)*d*[Nc^2-1]*s12^2 + 17/2*p2(nu95)*r1(mu95)*d^2*[Nc^2-1]*s12^2
          - 1/2*p2(nu95)*r1(mu95)*d^3*[Nc^2-1]*s12^2 - 24*p2(nu95)*r1(mu95)*
         p1.r1*p2.r1*[Nc^2-1] + 20*p2(nu95)*r1(mu95)*p1.r1*p2.r1*d*[Nc^2-1] - 
         4*p2(nu95)*r1(mu95)*p1.r1*p2.r1*d^2*[Nc^2-1] - 12*p2(nu95)*r1(mu95)*
         p1.r1*[Nc^2-1]*s12 + 10*p2(nu95)*r1(mu95)*p1.r1*d*[Nc^2-1]*s12 - 2*
         p2(nu95)*r1(mu95)*p1.r1*d^2*[Nc^2-1]*s12 + 120*p2(nu95)*r1(mu95)*
         p2.r1*[Nc^2-1]*s12 - 82*p2(nu95)*r1(mu95)*p2.r1*d*[Nc^2-1]*s12 + 17*
         p2(nu95)*r1(mu95)*p2.r1*d^2*[Nc^2-1]*s12 - p2(nu95)*r1(mu95)*p2.r1*
         d^3*[Nc^2-1]*s12 + 12*r1(mu95)*r1(nu95)*[Nc^2-1]*s12^2 - 10*r1(mu95)*
         r1(nu95)*d*[Nc^2-1]*s12^2 + 2*r1(mu95)*r1(nu95)*d^2*[Nc^2-1]*s12^2 + 
         24*r1(mu95)*r1(nu95)*p2.r1*[Nc^2-1]*s12 - 20*r1(mu95)*r1(nu95)*p2.r1*
         d*[Nc^2-1]*s12 + 4*r1(mu95)*r1(nu95)*p2.r1*d^2*[Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - q - p1)*Prop( - p1 - p2)*ga(ti)*
      cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*gs^2 * ( 112*p1.r1*p2.r1
         *[Nc^2-1]*s12 - 328/3*p1.r1*p2.r1*d*[Nc^2-1]*s12 + 32*p1.r1*p2.r1*d^2
         *[Nc^2-1]*s12 - 8/3*p1.r1*p2.r1*d^3*[Nc^2-1]*s12 + 112*p1.r1*p2.r1^2*
         [Nc^2-1] - 328/3*p1.r1*p2.r1^2*d*[Nc^2-1] + 32*p1.r1*p2.r1^2*d^2*
         [Nc^2-1] - 8/3*p1.r1*p2.r1^2*d^3*[Nc^2-1] + 28*p1.r1*[Nc^2-1]*s12^2
          - 82/3*p1.r1*d*[Nc^2-1]*s12^2 + 8*p1.r1*d^2*[Nc^2-1]*s12^2 - 2/3*
         p1.r1*d^3*[Nc^2-1]*s12^2 + 112*p1.r1^2*p2.r1*[Nc^2-1] - 328/3*p1.r1^2
         *p2.r1*d*[Nc^2-1] + 32*p1.r1^2*p2.r1*d^2*[Nc^2-1] - 8/3*p1.r1^2*p2.r1
         *d^3*[Nc^2-1] + 56*p1.r1^2*[Nc^2-1]*s12 - 164/3*p1.r1^2*d*[Nc^2-1]*
         s12 + 16*p1.r1^2*d^2*[Nc^2-1]*s12 - 4/3*p1.r1^2*d^3*[Nc^2-1]*s12 - 
         184*p2.r1*[Nc^2-1]*s12^2 + 478/3*p2.r1*d*[Nc^2-1]*s12^2 - 149/3*p2.r1
         *d^2*[Nc^2-1]*s12^2 + 20/3*p2.r1*d^3*[Nc^2-1]*s12^2 - 1/3*p2.r1*d^4*
         [Nc^2-1]*s12^2 - 368*p2.r1^2*[Nc^2-1]*s12 + 956/3*p2.r1^2*d*[Nc^2-1]*
         s12 - 298/3*p2.r1^2*d^2*[Nc^2-1]*s12 + 40/3*p2.r1^2*d^3*[Nc^2-1]*s12
          - 2/3*p2.r1^2*d^4*[Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - p1 - p2)^2*gv(ti)*cgv(tj)*Den(
      cut, - q.p1 + q.p2*u)*gs^2 * ( 2*p2(mu95)*r1(nu95)*[Nc^2-1]*s12^2 - 
         p2(mu95)*r1(nu95)*d*[Nc^2-1]*s12^2 + 4*p2(mu95)*r1(nu95)*p2.r1*
         [Nc^2-1]*s12 - 2*p2(mu95)*r1(nu95)*p2.r1*d*[Nc^2-1]*s12 + 2*p2(nu95)*
         r1(mu95)*[Nc^2-1]*s12^2 - p2(nu95)*r1(mu95)*d*[Nc^2-1]*s12^2 + 4*
         p2(nu95)*r1(mu95)*p2.r1*[Nc^2-1]*s12 - 2*p2(nu95)*r1(mu95)*p2.r1*d*
         [Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - p1 - p2)^2*gv(ti)*cgv(tj)*Den(
      cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*gs^2 * (  - 2*p2.r1*[Nc^2-1]*s12^2
          + p2.r1*d*[Nc^2-1]*s12^2 - 4*p2.r1^2*[Nc^2-1]*s12 + 2*p2.r1^2*d*
         [Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - p1 - p2)^2*gv(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^2 * ( 2*[Nc^2-1]*s12^2 - d*
         [Nc^2-1]*s12^2 + 4*p2.r1*[Nc^2-1]*s12 - 2*p2.r1*d*[Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - p1 - p2)^2*ga(ti)*cgv(tj)*Den(
      cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^2 * ( 2*[Nc^2-1]*s12^2 - d*
         [Nc^2-1]*s12^2 + 4*p2.r1*[Nc^2-1]*s12 - 2*p2.r1*d*[Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - p1 - p2)^2*ga(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*gs^2 * ( 6*p2(mu95)*r1(nu95)*[Nc^2-1]*s12^2 - 8*
         p2(mu95)*r1(nu95)*d*[Nc^2-1]*s12^2 + 7/2*p2(mu95)*r1(nu95)*d^2*
         [Nc^2-1]*s12^2 - 1/2*p2(mu95)*r1(nu95)*d^3*[Nc^2-1]*s12^2 + 12*
         p2(mu95)*r1(nu95)*p2.r1*[Nc^2-1]*s12 - 16*p2(mu95)*r1(nu95)*p2.r1*d*
         [Nc^2-1]*s12 + 7*p2(mu95)*r1(nu95)*p2.r1*d^2*[Nc^2-1]*s12 - p2(mu95)*
         r1(nu95)*p2.r1*d^3*[Nc^2-1]*s12 + 6*p2(nu95)*r1(mu95)*[Nc^2-1]*s12^2
          - 8*p2(nu95)*r1(mu95)*d*[Nc^2-1]*s12^2 + 7/2*p2(nu95)*r1(mu95)*d^2*
         [Nc^2-1]*s12^2 - 1/2*p2(nu95)*r1(mu95)*d^3*[Nc^2-1]*s12^2 + 12*
         p2(nu95)*r1(mu95)*p2.r1*[Nc^2-1]*s12 - 16*p2(nu95)*r1(mu95)*p2.r1*d*
         [Nc^2-1]*s12 + 7*p2(nu95)*r1(mu95)*p2.r1*d^2*[Nc^2-1]*s12 - p2(nu95)*
         r1(mu95)*p2.r1*d^3*[Nc^2-1]*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop( - p1 - p2)^2*ga(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*gs^2 * (  - 14*p2.r1*[Nc^2-1]*s12^2
          + 62/3*p2.r1*d*[Nc^2-1]*s12^2 - 65/6*p2.r1*d^2*[Nc^2-1]*s12^2 + 7/3*
         p2.r1*d^3*[Nc^2-1]*s12^2 - 1/6*p2.r1*d^4*[Nc^2-1]*s12^2 - 28*p2.r1^2*
         [Nc^2-1]*s12 + 124/3*p2.r1^2*d*[Nc^2-1]*s12 - 65/3*p2.r1^2*d^2*
         [Nc^2-1]*s12 + 14/3*p2.r1^2*d^3*[Nc^2-1]*s12 - 1/3*p2.r1^2*d^4*
         [Nc^2-1]*s12 );

