l [interf6_6]= + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + r1)^2*
      Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^4
       * ( 32*p1.r2*p2.r1*p2.r2 - 8*p1.r2*p2.r1*p2.r2*d + 8*p1.r2*p2.r1*s12 - 
         4*p1.r2*p2.r1*d*s12 + 24*p1.r2*p2.r2*s12 - 8*p1.r2*p2.r2*d*s12 + 32*
         p1.r2*p2.r2^2 - 8*p1.r2*p2.r2^2*d + 4*p1.r2*s12^2 - 2*p1.r2*d*s12^2
          - 8*p2.r1*p2.r2*s12 + 16*p2.r1*p2.r2^2 - 4*p2.r2*s12^2 + 16*p2.r2^3
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + r1)^2*Prop( - p1
       - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^4*Nc^2 * (  - 
         32*p1.r2*p2.r1*p2.r2 + 8*p1.r2*p2.r1*p2.r2*d - 8*p1.r2*p2.r1*s12 + 4*
         p1.r2*p2.r1*d*s12 - 24*p1.r2*p2.r2*s12 + 8*p1.r2*p2.r2*d*s12 - 32*
         p1.r2*p2.r2^2 + 8*p1.r2*p2.r2^2*d - 4*p1.r2*s12^2 + 2*p1.r2*d*s12^2
          + 8*p2.r1*p2.r2*s12 - 16*p2.r1*p2.r2^2 + 4*p2.r2*s12^2 - 16*p2.r2^3
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + r1)^2*Prop( - p1
       - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^4 * (  - 16*
         p1.r2*p2.r1*p2.r2 - 8*p1.r2*p2.r1*s12 - 16*p1.r2*p2.r2*s12 - 16*p1.r2
         *p2.r2^2 - 4*p1.r2*s12^2 - 32*p1.r2^2*p2.r1 + 8*p1.r2^2*p2.r1*d - 32*
         p1.r2^2*p2.r2 + 8*p1.r2^2*p2.r2*d - 16*p1.r2^2*s12 + 4*p1.r2^2*d*s12
          - 16*p2.r1*p2.r2*s12 - 8*p2.r2*s12^2 - 16*p2.r2^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + r1)^2*Prop( - p1
       - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^4*Nc^2 * ( 16*
         p1.r2*p2.r1*p2.r2 + 8*p1.r2*p2.r1*s12 + 16*p1.r2*p2.r2*s12 + 16*p1.r2
         *p2.r2^2 + 4*p1.r2*s12^2 + 32*p1.r2^2*p2.r1 - 8*p1.r2^2*p2.r1*d + 32*
         p1.r2^2*p2.r2 - 8*p1.r2^2*p2.r2*d + 16*p1.r2^2*s12 - 4*p1.r2^2*d*s12
          + 16*p2.r1*p2.r2*s12 + 8*p2.r2*s12^2 + 16*p2.r2^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + r1)^2*Prop( - p1
       - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4 * (  - 2*
         s12^3 - 16*p1.r2*p2.r1*p2.r2 + 8*p1.r2*p2.r1*p2.r2*d - 16*p1.r2*p2.r1
         *s12 + 4*p1.r2*p2.r1*d*s12 - 24*p1.r2*p2.r2*s12 + 8*p1.r2*p2.r2*d*s12
          - 16*p1.r2*p2.r2^2 + 8*p1.r2*p2.r2^2*d - 8*p1.r2*s12^2 + 2*p1.r2*d*
         s12^2 + 8*p2.r1*p2.r2*s12 - 4*p2.r1*s12^2 + 8*p2.r2^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + r1)^2*Prop( - p1
       - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4*Nc^2 * ( 2*
         s12^3 + 16*p1.r2*p2.r1*p2.r2 - 8*p1.r2*p2.r1*p2.r2*d + 16*p1.r2*p2.r1
         *s12 - 4*p1.r2*p2.r1*d*s12 + 24*p1.r2*p2.r2*s12 - 8*p1.r2*p2.r2*d*s12
          + 16*p1.r2*p2.r2^2 - 8*p1.r2*p2.r2^2*d + 8*p1.r2*s12^2 - 2*p1.r2*d*
         s12^2 - 8*p2.r1*p2.r2*s12 + 4*p2.r1*s12^2 - 8*p2.r2^2*s12 );

