l [interf6_5]= + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*
      Prop(q + r1)*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r1,
      nu95)*gs^4 * ( 32*p1(mu95)*p1.r2*p2.r1 - 8*p1(mu95)*p1.r2*p2.r1*d + 32*
         p1(mu95)*p1.r2*p2.r2 - 8*p1(mu95)*p1.r2*p2.r2*d + 16*p1(mu95)*p1.r2*
         s12 - 4*p1(mu95)*p1.r2*d*s12 - 16*p2(mu95)*p1.r2*p2.r1 - 16*p2(mu95)*
         p1.r2*p2.r2 - 8*p2(mu95)*p1.r2*s12 + 16*r1(mu95)*p1.r2*p2.r1 + 16*
         r1(mu95)*p1.r2*p2.r2 + 8*r1(mu95)*p1.r2*s12 + 2*r2(mu95)*s12^2 - 8*
         r2(mu95)*p1.r1*p2.r1 - 8*r2(mu95)*p1.r1*p2.r2 - 4*r2(mu95)*p1.r1*s12
          + 48*r2(mu95)*p1.r2*p2.r1 - 8*r2(mu95)*p1.r2*p2.r1*d + 48*r2(mu95)*
         p1.r2*p2.r2 - 8*r2(mu95)*p1.r2*p2.r2*d + 24*r2(mu95)*p1.r2*s12 - 4*
         r2(mu95)*p1.r2*d*s12 - 8*r2(mu95)*p2.r1*p2.r2 + 8*r2(mu95)*p2.r1*
         r1.r2 + 4*r2(mu95)*p2.r1*s12 + 8*r2(mu95)*p2.r2*r1.r2 - 8*r2(mu95)*
         p2.r2^2 + 4*r2(mu95)*r1.r2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r1,nu95)*gs^4*
      Nc^2 * (  - 32*p1(mu95)*p1.r2*p2.r1 + 8*p1(mu95)*p1.r2*p2.r1*d - 32*
         p1(mu95)*p1.r2*p2.r2 + 8*p1(mu95)*p1.r2*p2.r2*d - 16*p1(mu95)*p1.r2*
         s12 + 4*p1(mu95)*p1.r2*d*s12 + 16*p2(mu95)*p1.r2*p2.r1 + 16*p2(mu95)*
         p1.r2*p2.r2 + 8*p2(mu95)*p1.r2*s12 - 16*r1(mu95)*p1.r2*p2.r1 - 16*
         r1(mu95)*p1.r2*p2.r2 - 8*r1(mu95)*p1.r2*s12 - 2*r2(mu95)*s12^2 + 8*
         r2(mu95)*p1.r1*p2.r1 + 8*r2(mu95)*p1.r1*p2.r2 + 4*r2(mu95)*p1.r1*s12
          - 48*r2(mu95)*p1.r2*p2.r1 + 8*r2(mu95)*p1.r2*p2.r1*d - 48*r2(mu95)*
         p1.r2*p2.r2 + 8*r2(mu95)*p1.r2*p2.r2*d - 24*r2(mu95)*p1.r2*s12 + 4*
         r2(mu95)*p1.r2*d*s12 + 8*r2(mu95)*p2.r1*p2.r2 - 8*r2(mu95)*p2.r1*
         r1.r2 - 4*r2(mu95)*p2.r1*s12 - 8*r2(mu95)*p2.r2*r1.r2 + 8*r2(mu95)*
         p2.r2^2 - 4*r2(mu95)*r1.r2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r2,nu95)*gs^4
       * ( 32*p1(mu95)*p2.r1*r1.r2 + 32*p1(mu95)*p2.r2*r1.r2 + 16*p1(mu95)*
         r1.r2*s12 - 2*r1(mu95)*s12^2 - 8*r1(mu95)*p1.r1*p2.r1 - 8*r1(mu95)*
         p1.r1*p2.r2 - 4*r1(mu95)*p1.r1*s12 + 8*r1(mu95)*p2.r1*p2.r2 + 8*
         r1(mu95)*p2.r1*r1.r2 - 4*r1(mu95)*p2.r1*s12 + 8*r1(mu95)*p2.r2*r1.r2
          + 8*r1(mu95)*p2.r2^2 + 4*r1(mu95)*r1.r2*s12 - 32*r2(mu95)*p1.r1*
         p2.r1 - 32*r2(mu95)*p1.r1*p2.r2 - 16*r2(mu95)*p1.r1*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r2,nu95)*gs^4*
      Nc^2 * (  - 32*p1(mu95)*p2.r1*r1.r2 - 32*p1(mu95)*p2.r2*r1.r2 - 16*
         p1(mu95)*r1.r2*s12 + 2*r1(mu95)*s12^2 + 8*r1(mu95)*p1.r1*p2.r1 + 8*
         r1(mu95)*p1.r1*p2.r2 + 4*r1(mu95)*p1.r1*s12 - 8*r1(mu95)*p2.r1*p2.r2
          - 8*r1(mu95)*p2.r1*r1.r2 + 4*r1(mu95)*p2.r1*s12 - 8*r1(mu95)*p2.r2*
         r1.r2 - 8*r1(mu95)*p2.r2^2 - 4*r1(mu95)*r1.r2*s12 + 32*r2(mu95)*p1.r1
         *p2.r1 + 32*r2(mu95)*p1.r1*p2.r2 + 16*r2(mu95)*p1.r1*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*gs^4
       * (  - 32*p1.r1*p1.r2*p2.r1 + 8*p1.r1*p1.r2*p2.r1*d - 32*p1.r1*p1.r2*
         p2.r2 + 8*p1.r1*p1.r2*p2.r2*d - 16*p1.r1*p1.r2*s12 + 4*p1.r1*p1.r2*d*
         s12 + 8*p1.r1*p2.r1*r1.r2 + 8*p1.r1*p2.r2*r1.r2 + 4*p1.r1*r1.r2*s12
          + 16*p1.r2*p2.r1*p2.r2 - 48*p1.r2*p2.r1*r1.r2 + 8*p1.r2*p2.r1*r1.r2*
         d + 8*p1.r2*p2.r1*s12 + 16*p1.r2*p2.r1^2 - 48*p1.r2*p2.r2*r1.r2 + 8*
         p1.r2*p2.r2*r1.r2*d - 24*p1.r2*r1.r2*s12 + 4*p1.r2*r1.r2*d*s12 + 8*
         p2.r1*p2.r2*r1.r2 - 4*p2.r1*r1.r2*s12 - 8*p2.r1*r1.r2^2 - 8*p2.r2*
         r1.r2^2 + 8*p2.r2^2*r1.r2 - 2*r1.r2*s12^2 - 4*r1.r2^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*gs^4*
      Nc^2 * ( 32*p1.r1*p1.r2*p2.r1 - 8*p1.r1*p1.r2*p2.r1*d + 32*p1.r1*p1.r2*
         p2.r2 - 8*p1.r1*p1.r2*p2.r2*d + 16*p1.r1*p1.r2*s12 - 4*p1.r1*p1.r2*d*
         s12 - 8*p1.r1*p2.r1*r1.r2 - 8*p1.r1*p2.r2*r1.r2 - 4*p1.r1*r1.r2*s12
          - 16*p1.r2*p2.r1*p2.r2 + 48*p1.r2*p2.r1*r1.r2 - 8*p1.r2*p2.r1*r1.r2*
         d - 8*p1.r2*p2.r1*s12 - 16*p1.r2*p2.r1^2 + 48*p1.r2*p2.r2*r1.r2 - 8*
         p1.r2*p2.r2*r1.r2*d + 24*p1.r2*r1.r2*s12 - 4*p1.r2*r1.r2*d*s12 - 8*
         p2.r1*p2.r2*r1.r2 + 4*p2.r1*r1.r2*s12 + 8*p2.r1*r1.r2^2 + 8*p2.r2*
         r1.r2^2 - 8*p2.r2^2*r1.r2 + 2*r1.r2*s12^2 + 4*r1.r2^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,r2,nu95)*gs^4
       * (  - 2*p2(mu95)*s12^2 - 8*p2(mu95)*p1.r1*p2.r1 - 8*p2(mu95)*p1.r1*
         p2.r2 - 4*p2(mu95)*p1.r1*s12 + 8*p2(mu95)*p2.r1*p2.r2 + 8*p2(mu95)*
         p2.r1*r1.r2 - 4*p2(mu95)*p2.r1*s12 + 8*p2(mu95)*p2.r2*r1.r2 + 8*
         p2(mu95)*p2.r2^2 + 4*p2(mu95)*r1.r2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,r2,nu95)*gs^4*
      Nc^2 * ( 2*p2(mu95)*s12^2 + 8*p2(mu95)*p1.r1*p2.r1 + 8*p2(mu95)*p1.r1*
         p2.r2 + 4*p2(mu95)*p1.r1*s12 - 8*p2(mu95)*p2.r1*p2.r2 - 8*p2(mu95)*
         p2.r1*r1.r2 + 4*p2(mu95)*p2.r1*s12 - 8*p2(mu95)*p2.r2*r1.r2 - 8*
         p2(mu95)*p2.r2^2 - 4*p2(mu95)*r1.r2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^4
       * ( 8*p1.r1*p2.r1*p2.r2 + 4*p1.r1*p2.r2*s12 + 8*p1.r1*p2.r2^2 - 8*p2.r1
         *p2.r2*r1.r2 + 4*p2.r1*p2.r2*s12 - 8*p2.r1*p2.r2^2 - 4*p2.r2*r1.r2*
         s12 + 2*p2.r2*s12^2 - 8*p2.r2^2*r1.r2 - 8*p2.r2^3 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^4*
      Nc^2 * (  - 8*p1.r1*p2.r1*p2.r2 - 4*p1.r1*p2.r2*s12 - 8*p1.r1*p2.r2^2 + 
         8*p2.r1*p2.r2*r1.r2 - 4*p2.r1*p2.r2*s12 + 8*p2.r1*p2.r2^2 + 4*p2.r2*
         r1.r2*s12 - 2*p2.r2*s12^2 + 8*p2.r2^2*r1.r2 + 8*p2.r2^3 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*gs^4
       * (  - 8*p1.r1*p2.r1*p2.r2 - 4*p1.r1*p2.r1*s12 - 8*p1.r1*p2.r1^2 + 8*
         p2.r1*p2.r2*r1.r2 + 8*p2.r1*p2.r2^2 + 4*p2.r1*r1.r2*s12 - 2*p2.r1*
         s12^2 + 8*p2.r1^2*p2.r2 + 8*p2.r1^2*r1.r2 - 4*p2.r1^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*gs^4*
      Nc^2 * ( 8*p1.r1*p2.r1*p2.r2 + 4*p1.r1*p2.r1*s12 + 8*p1.r1*p2.r1^2 - 8*
         p2.r1*p2.r2*r1.r2 - 8*p2.r1*p2.r2^2 - 4*p2.r1*r1.r2*s12 + 2*p2.r1*
         s12^2 - 8*p2.r1^2*p2.r2 - 8*p2.r1^2*r1.r2 + 4*p2.r1^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,r2,nu95)*gs^4
       * (  - 2*p1(mu95)*s12^2 + 8*p1(mu95)*p1.r1*p2.r1 + 8*p1(mu95)*p1.r1*
         p2.r2 + 4*p1(mu95)*p1.r1*s12 + 48*p1(mu95)*p1.r2*p2.r1 - 8*p1(mu95)*
         p1.r2*p2.r1*d + 48*p1(mu95)*p1.r2*p2.r2 - 8*p1(mu95)*p1.r2*p2.r2*d + 
         24*p1(mu95)*p1.r2*s12 - 4*p1(mu95)*p1.r2*d*s12 + 8*p1(mu95)*p2.r1*
         p2.r2 - 8*p1(mu95)*p2.r1*r1.r2 - 4*p1(mu95)*p2.r1*s12 - 8*p1(mu95)*
         p2.r2*r1.r2 + 8*p1(mu95)*p2.r2^2 - 4*p1(mu95)*r1.r2*s12 - 16*p2(mu95)
         *p1.r2*p2.r1 - 16*p2(mu95)*p1.r2*p2.r2 - 8*p2(mu95)*p1.r2*s12 + 16*
         r1(mu95)*p1.r2*p2.r1 + 16*r1(mu95)*p1.r2*p2.r2 + 8*r1(mu95)*p1.r2*s12
          + 32*r2(mu95)*p1.r2*p2.r1 - 8*r2(mu95)*p1.r2*p2.r1*d + 32*r2(mu95)*
         p1.r2*p2.r2 - 8*r2(mu95)*p1.r2*p2.r2*d + 16*r2(mu95)*p1.r2*s12 - 4*
         r2(mu95)*p1.r2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,r2,nu95)*gs^4*
      Nc^2 * ( 2*p1(mu95)*s12^2 - 8*p1(mu95)*p1.r1*p2.r1 - 8*p1(mu95)*p1.r1*
         p2.r2 - 4*p1(mu95)*p1.r1*s12 - 48*p1(mu95)*p1.r2*p2.r1 + 8*p1(mu95)*
         p1.r2*p2.r1*d - 48*p1(mu95)*p1.r2*p2.r2 + 8*p1(mu95)*p1.r2*p2.r2*d - 
         24*p1(mu95)*p1.r2*s12 + 4*p1(mu95)*p1.r2*d*s12 - 8*p1(mu95)*p2.r1*
         p2.r2 + 8*p1(mu95)*p2.r1*r1.r2 + 4*p1(mu95)*p2.r1*s12 + 8*p1(mu95)*
         p2.r2*r1.r2 - 8*p1(mu95)*p2.r2^2 + 4*p1(mu95)*r1.r2*s12 + 16*p2(mu95)
         *p1.r2*p2.r1 + 16*p2(mu95)*p1.r2*p2.r2 + 8*p2(mu95)*p1.r2*s12 - 16*
         r1(mu95)*p1.r2*p2.r1 - 16*r1(mu95)*p1.r2*p2.r2 - 8*r1(mu95)*p1.r2*s12
          - 32*r2(mu95)*p1.r2*p2.r1 + 8*r2(mu95)*p1.r2*p2.r1*d - 32*r2(mu95)*
         p1.r2*p2.r2 + 8*r2(mu95)*p1.r2*p2.r2*d - 16*r2(mu95)*p1.r2*s12 + 4*
         r2(mu95)*p1.r2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^4
       * (  - 8*p1.r1*p1.r2*p2.r1 - 8*p1.r1*p1.r2*p2.r2 - 4*p1.r1*p1.r2*s12 + 
         16*p1.r1*p2.r1*p2.r2 + 8*p1.r1*p2.r2*s12 + 16*p1.r1*p2.r2^2 - 8*p1.r2
         *p2.r1*p2.r2 - 8*p1.r2*p2.r1*r1.r2 - 4*p1.r2*p2.r1*s12 - 16*p1.r2*
         p2.r1^2 - 8*p1.r2*p2.r2*r1.r2 + 8*p1.r2*p2.r2*s12 + 8*p1.r2*p2.r2^2
          - 4*p1.r2*r1.r2*s12 + 2*p1.r2*s12^2 - 48*p1.r2^2*p2.r1 + 8*p1.r2^2*
         p2.r1*d - 48*p1.r2^2*p2.r2 + 8*p1.r2^2*p2.r2*d - 24*p1.r2^2*s12 + 4*
         p1.r2^2*d*s12 + 8*p2.r1*r1.r2*s12 + 8*p2.r2*r1.r2*s12 + 4*r1.r2*s12^2
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^4*
      Nc^2 * ( 8*p1.r1*p1.r2*p2.r1 + 8*p1.r1*p1.r2*p2.r2 + 4*p1.r1*p1.r2*s12
          - 16*p1.r1*p2.r1*p2.r2 - 8*p1.r1*p2.r2*s12 - 16*p1.r1*p2.r2^2 + 8*
         p1.r2*p2.r1*p2.r2 + 8*p1.r2*p2.r1*r1.r2 + 4*p1.r2*p2.r1*s12 + 16*
         p1.r2*p2.r1^2 + 8*p1.r2*p2.r2*r1.r2 - 8*p1.r2*p2.r2*s12 - 8*p1.r2*
         p2.r2^2 + 4*p1.r2*r1.r2*s12 - 2*p1.r2*s12^2 + 48*p1.r2^2*p2.r1 - 8*
         p1.r2^2*p2.r1*d + 48*p1.r2^2*p2.r2 - 8*p1.r2^2*p2.r2*d + 24*p1.r2^2*
         s12 - 4*p1.r2^2*d*s12 - 8*p2.r1*r1.r2*s12 - 8*p2.r2*r1.r2*s12 - 4*
         r1.r2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*gs^4
       * ( 48*p1.r1*p1.r2*p2.r1 - 8*p1.r1*p1.r2*p2.r1*d + 48*p1.r1*p1.r2*p2.r2
          - 8*p1.r1*p1.r2*p2.r2*d + 24*p1.r1*p1.r2*s12 - 4*p1.r1*p1.r2*d*s12
          + 8*p1.r1*p2.r1*p2.r2 - 8*p1.r1*p2.r1*r1.r2 - 4*p1.r1*p2.r1*s12 - 8*
         p1.r1*p2.r2*r1.r2 + 8*p1.r1*p2.r2^2 - 4*p1.r1*r1.r2*s12 - 2*p1.r1*
         s12^2 + 8*p1.r1^2*p2.r1 + 8*p1.r1^2*p2.r2 + 4*p1.r1^2*s12 - 16*p1.r2*
         p2.r1*p2.r2 + 32*p1.r2*p2.r1*r1.r2 - 8*p1.r2*p2.r1*r1.r2*d - 8*p1.r2*
         p2.r1*s12 - 16*p1.r2*p2.r1^2 + 32*p1.r2*p2.r2*r1.r2 - 8*p1.r2*p2.r2*
         r1.r2*d + 16*p1.r2*r1.r2*s12 - 4*p1.r2*r1.r2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*gs^4*
      Nc^2 * (  - 48*p1.r1*p1.r2*p2.r1 + 8*p1.r1*p1.r2*p2.r1*d - 48*p1.r1*
         p1.r2*p2.r2 + 8*p1.r1*p1.r2*p2.r2*d - 24*p1.r1*p1.r2*s12 + 4*p1.r1*
         p1.r2*d*s12 - 8*p1.r1*p2.r1*p2.r2 + 8*p1.r1*p2.r1*r1.r2 + 4*p1.r1*
         p2.r1*s12 + 8*p1.r1*p2.r2*r1.r2 - 8*p1.r1*p2.r2^2 + 4*p1.r1*r1.r2*s12
          + 2*p1.r1*s12^2 - 8*p1.r1^2*p2.r1 - 8*p1.r1^2*p2.r2 - 4*p1.r1^2*s12
          + 16*p1.r2*p2.r1*p2.r2 - 32*p1.r2*p2.r1*r1.r2 + 8*p1.r2*p2.r1*r1.r2*
         d + 8*p1.r2*p2.r1*s12 + 16*p1.r2*p2.r1^2 - 32*p1.r2*p2.r2*r1.r2 + 8*
         p1.r2*p2.r2*r1.r2*d - 16*p1.r2*r1.r2*s12 + 4*p1.r2*r1.r2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4
       * ( s12^3 + 4*p1.r1*p2.r1*s12 + 4*p1.r1*p2.r2*s12 + 2*p1.r1*s12^2 - 4*
         p2.r1*p2.r2*s12 - 4*p2.r1*r1.r2*s12 + 2*p2.r1*s12^2 - 4*p2.r2*r1.r2*
         s12 - 4*p2.r2^2*s12 - 2*r1.r2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - p2)*Prop(q + r1
      )*Prop( - p1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4*
      Nc^2 * (  - s12^3 - 4*p1.r1*p2.r1*s12 - 4*p1.r1*p2.r2*s12 - 2*p1.r1*
         s12^2 + 4*p2.r1*p2.r2*s12 + 4*p2.r1*r1.r2*s12 - 2*p2.r1*s12^2 + 4*
         p2.r2*r1.r2*s12 + 4*p2.r2^2*s12 + 2*r1.r2*s12^2 );

