repeat;
id Prop(p2 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3) = +Num(2
z-6*u*z+5*u*z)*Den(22
m2*z+5*m2*u+m2*u*z-7*m2*u*z)*Prop(p2 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(2
u*z-u*z)*Den(22
m2*z+5*m2*u+m2*u*z-7*m2*u*z)*Prop(p2 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-5*u*z)*Den(22
m2*z+5*m2*u+m2*u*z-7*m2*u*z)*Prop(p2 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-5*u*z)*Den(22
m2*z+5*m2*u+m2*u*z-7*m2*u*z)*Prop(p2 + r1 + r2)*Prop(p2 + r2 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-5*u*z)*Den(22
m2*z+5*m2*u+m2*u*z-7*m2*u*z)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3);
endrepeat;
