repeat;
id Prop(p2 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)*Prop(p1 + r1 + r2 + r3) = +Num(-z+u*z)*Den(m2-2*m2*z+m2*u*z)*Prop(p2 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)+Num(-z)*Den(m2-2*m2*z+m2*u*z)*Prop(p2 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p1 + r1 + r2 + r3)+Num(-z)*Den(m2-2*m2*z+m2*u*z)*Prop(p2 + r1 + r2)*Prop(p2 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(-z)*Den(m2-2*m2*z+m2*u*z)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)*Prop(p1 + r1 + r2 + r3);
endrepeat;
