repeat;
id Prop(p1 + r3)*Prop(r1 + r2)*Prop(p1 + r1 + r3)*Prop(p1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3) = +Num(-1)*Den(-m2+m2*u)*Prop(p1 + r3)*Prop(r1 + r2)*Prop(p1 + r1 + r3)*Prop(p1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(-u)*Den(2
m2-7*m2*u+6*m2*u)*Prop(p1 + r3)*Prop(r1 + r2)*Prop(p1 + r1 + r3)*Prop(p1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
6*u)*Den(2
m2-7*m2*u+6*m2*u)*Prop(p1 + r3)*Prop(r1 + r2)*Prop(p1 + r1 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
6*u)*Den(2
m2-7*m2*u+6*m2*u)*Prop(p1 + r3)*Prop(r1 + r2)*Prop(p1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
6*u)*Den(2
m2-7*m2*u+6*m2*u)*Prop(p1 + r3)*Prop(p1 + r1 + r3)*Prop(p1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-6*u)*Den(2
m2-7*m2*u+6*m2*u)*Prop(r1 + r2)*Prop(p1 + r1 + r3)*Prop(p1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3);
endrepeat;
