repeat;
id Prop(p2 + r1)*Prop(r2 + r3)*Prop(p2 + r2 + r3)*Prop(p2 + r1 + r2 + r3) = +Num(z)*Den(m2*z-m2*u)*Prop(p2 + r1)*Prop(r2 + r3)*Prop(p2 + r2 + r3)+Num(-u*z)*Den(m2*u-m2*z)*Prop(p2 + r1)*Prop(r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(u*z)*Den(m2*u-m2*z)*Prop(p2 + r1)*Prop(p2 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(-u*z)*Den(m2*u-m2*z)*Prop(r2 + r3)*Prop(p2 + r2 + r3)*Prop(p2 + r1 + r2 + r3);
endrepeat;
