repeat;
id Prop(p1 + r3)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3) = +Num(z)*Den(-m2+m2*z)*Prop(p1 + r3)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r3)+Num(z)*Den(-m2+m2*z)*Prop(p1 + r3)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r2 + r3)+Num(z)*Den(-m2+m2*z)*Prop(p1 + r3)*Prop(p2 + r3)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)+Num(-z)*Den(-m2+m2*z)*Prop(p1 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)+Num(z)*Den(-m2+m2*z)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3);
endrepeat;
