repeat;
id Prop(p1 + r1)*Prop(r2 + r3)*Prop(p1 + r1 + r2)*Prop(p1 + r1 + r3)*Prop(p2 + r1 + r2 + r3) = +Num(-1)*Den(-m2+m2*u)*Prop(p1 + r1)*Prop(r2 + r3)*Prop(p1 + r1 + r2)*Prop(p1 + r1 + r3)+Num(u)*Den(-m2+m2*u)*Prop(p1 + r1)*Prop(r2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2 + r3)+Num(u)*Den(-m2+m2*u)*Prop(p1 + r1)*Prop(r2 + r3)*Prop(p1 + r1 + r3)*Prop(p2 + r1 + r2 + r3)+Num(u)*Den(-m2+m2*u)*Prop(p1 + r1)*Prop(p1 + r1 + r2)*Prop(p1 + r1 + r3)*Prop(p2 + r1 + r2 + r3)+Num(-u)*Den(-m2+m2*u)*Prop(r2 + r3)*Prop(p1 + r1 + r2)*Prop(p1 + r1 + r3)*Prop(p2 + r1 + r2 + r3);
endrepeat;
