repeat;
id Prop(p1 + r1 + r2)*Prop(p1 + r1 + r3)*Prop(p1 + r2 + r3)*Prop(p1 + r1 + r2 + r3) = +Num(-z+u*z)*Den(-m2+m2*u*z)*Prop(p1 + r1 + r2)*Prop(p1 + r1 + r3)*Prop(p1 + r2 + r3)+Num(z)*Den(-m2+m2*u*z)*Prop(p1 + r1 + r2)*Prop(p1 + r1 + r3)*Prop(p1 + r1 + r2 + r3)+Num(z)*Den(-m2+m2*u*z)*Prop(p1 + r1 + r2)*Prop(p1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(z)*Den(-m2+m2*u*z)*Prop(p1 + r1 + r3)*Prop(p1 + r2 + r3)*Prop(p1 + r1 + r2 + r3);
endrepeat;
