repeat;
id Prop(p1 + r1 + r2)*Prop(p1 + r1 + r3)*Prop(p1 + r2 + r3)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3) = +Num(2
4*z+u*z-5*u*z)*Den(2
6*m2-m2*u+m2*u*z-6*m2*u*z)*Prop(p1 + r1 + r2)*Prop(p1 + r1 + r3)*Prop(p1 + r2 + r3)*Prop(r1 + r2 + r3)+Num(z-u*z)*Den(2
6*m2-m2*u+m2*u*z-6*m2*u*z)*Prop(p1 + r1 + r2)*Prop(p1 + r1 + r3)*Prop(p1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(-5*z)*Den(2
6*m2-m2*u+m2*u*z-6*m2*u*z)*Prop(p1 + r1 + r2)*Prop(p1 + r1 + r3)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(-5*z)*Den(2
6*m2-m2*u+m2*u*z-6*m2*u*z)*Prop(p1 + r1 + r2)*Prop(p1 + r2 + r3)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(-5*z)*Den(2
6*m2-m2*u+m2*u*z-6*m2*u*z)*Prop(p1 + r1 + r3)*Prop(p1 + r2 + r3)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3);
endrepeat;
