repeat;
id Prop(r1 + r2)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3) = +Num(2
-z+4*u*z+5*u*z)*Den(22
-5*m2*u-m2*z+m2*u*z+5*m2*u*z)*Prop(r1 + r2)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(p1 + r1 + r2 + r3)+Num(2
u*z+u*z)*Den(22
-5*m2*u-m2*z+m2*u*z+5*m2*u*z)*Prop(r1 + r2)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-5*u*z)*Den(22
-5*m2*u-m2*z+m2*u*z+5*m2*u*z)*Prop(r1 + r2)*Prop(r2 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-5*u*z)*Den(22
-5*m2*u-m2*z+m2*u*z+5*m2*u*z)*Prop(r1 + r2)*Prop(r1 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-5*u*z)*Den(22
-5*m2*u-m2*z+m2*u*z+5*m2*u*z)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3);
endrepeat;
