repeat;
id Prop(p1 + r3)*Prop(r1 + r2)*Prop(p1 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3) = +Num(2
-z+5*u*z+6*u*z)*Den(22
-6*m2*u-3*m2*u-m2*z+4*m2*u*z+6*m2*u*z)*Prop(p1 + r3)*Prop(r1 + r2)*Prop(p1 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(2
u*z+u*z)*Den(22
-6*m2*u-3*m2*u-m2*z+4*m2*u*z+6*m2*u*z)*Prop(p1 + r3)*Prop(r1 + r2)*Prop(p1 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-3*u*z)*Den(22
-6*m2*u-3*m2*u-m2*z+4*m2*u*z+6*m2*u*z)*Prop(p1 + r3)*Prop(r1 + r2)*Prop(p1 + r1 + r2)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
3*u*z+3*u*z)*Den(22
-6*m2*u-3*m2*u-m2*z+4*m2*u*z+6*m2*u*z)*Prop(p1 + r3)*Prop(r1 + r2)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-3*u*z-3*u*z)*Den(22
-6*m2*u-3*m2*u-m2*z+4*m2*u*z+6*m2*u*z)*Prop(p1 + r3)*Prop(p1 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
3*u*z+3*u*z)*Den(22
-6*m2*u-3*m2*u-m2*z+4*m2*u*z+6*m2*u*z)*Prop(r1 + r2)*Prop(p1 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3);
endrepeat;
