repeat;
id Prop(p1 + r3)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3) = +Num(-1+6*u)*Den(-m2+7*m2*u)*Prop(p1 + r3)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2)*Prop(p1 + r1 + r2 + r3)+Num(u)*Den(-m2+7*m2*u)*Prop(p1 + r3)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2)*Prop(p2 + r1 + r2 + r3)+Num(2
-6*u)*Den(2
m2-8*m2*u+7*m2*u)*Prop(p1 + r3)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
6*u)*Den(2
m2-8*m2*u+7*m2*u)*Prop(p1 + r3)*Prop(p2 + r3)*Prop(p2 + r1 + r2)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-6*u)*Den(2
m2-8*m2*u+7*m2*u)*Prop(p1 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
6*u)*Den(2
m2-8*m2*u+7*m2*u)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2)*Prop(p1 + r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3);
endrepeat;
