repeat;
id Prop(p1 + r3)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3) = +Num(-5*z+u*z)*Den(-m2-6*m2*z+m2*u*z)*Prop(p1 + r3)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2)*Prop(r1 + r2 + r3)+Num(-z)*Den(-m2-6*m2*z+m2*u*z)*Prop(p1 + r3)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2)*Prop(p1 + r1 + r2 + r3)+Num(6*z)*Den(2
m2-m2*u+6*m2*z+m2*u*z-7*m2*u*z)*Prop(p1 + r3)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(-6*z)*Den(2
m2-m2*u+6*m2*z+m2*u*z-7*m2*u*z)*Prop(p1 + r3)*Prop(p2 + r3)*Prop(p2 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(6*z)*Den(2
m2-m2*u+6*m2*z+m2*u*z-7*m2*u*z)*Prop(p1 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(-6*z)*Den(2
m2-m2*u+6*m2*z+m2*u*z-7*m2*u*z)*Prop(p2 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3);
endrepeat;
