repeat;
id Prop(p2 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)*Prop(r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3) = +Num(2
z-5*u*z+4*u*z)*Den(2
m2*z-m2*u+6*m2*u-6*m2*u*z)*Prop(p2 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)*Prop(r1 + r2 + r3)+Num(2
u*z-u*z)*Den(2
m2*z-m2*u+6*m2*u-6*m2*u*z)*Prop(p2 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-5*u*z)*Den(2
m2*z-m2*u+6*m2*u-6*m2*u*z)*Prop(p2 + r1 + r2)*Prop(p2 + r1 + r3)*Prop(r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-5*u*z)*Den(2
m2*z-m2*u+6*m2*u-6*m2*u*z)*Prop(p2 + r1 + r2)*Prop(p2 + r2 + r3)*Prop(r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
-5*u*z)*Den(2
m2*z-m2*u+6*m2*u-6*m2*u*z)*Prop(p2 + r1 + r3)*Prop(p2 + r2 + r3)*Prop(r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3);
endrepeat;
