repeat;
id Prop(r1 + r2)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3) = +Num(z+u*z)*Den(-m2+m2*u*z)*Prop(r1 + r2)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(r1 + r2 + r3)+Num(-z-u*z)*Den(2
4*m2-m2*u+m2*u*z-4*m2*u*z)*Prop(r1 + r2)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(p1 + r1 + r2 + r3)+Num(5*z)*Den(2
4*m2-m2*u+m2*u*z-4*m2*u*z)*Prop(r1 + r2)*Prop(r2 + r3)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(5*z)*Den(2
4*m2-m2*u+m2*u*z-4*m2*u*z)*Prop(r1 + r2)*Prop(r1 + r3)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3)+Num(5*z)*Den(2
4*m2-m2*u+m2*u*z-4*m2*u*z)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(r1 + r2 + r3)*Prop(p1 + r1 + r2 + r3);
endrepeat;
