repeat;
id Prop(p1 + r3)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(p1 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3) = +Num(z-5*u*z)*Den(2
m2*z-m2*u-6*m2*u*z+6*m2*u*z)*Prop(p1 + r3)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(p1 + r1 + r2)*Prop(r1 + r2 + r3)+Num(-u*z)*Den(2
m2*z-m2*u-6*m2*u*z+6*m2*u*z)*Prop(p1 + r3)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(p1 + r1 + r2)*Prop(p2 + r1 + r2 + r3)+Num(2
6*u*z)*Den(2
m2*z-m2*u-6*m2*u*z+6*m2*u*z)*Prop(p1 + r3)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
6*u*z)*Den(2
m2*z-m2*u-6*m2*u*z+6*m2*u*z)*Prop(p1 + r3)*Prop(r2 + r3)*Prop(p1 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
6*u*z)*Den(2
m2*z-m2*u-6*m2*u*z+6*m2*u*z)*Prop(p1 + r3)*Prop(r1 + r3)*Prop(p1 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3)+Num(2
6*u*z)*Den(2
m2*z-m2*u-6*m2*u*z+6*m2*u*z)*Prop(r2 + r3)*Prop(r1 + r3)*Prop(p1 + r1 + r2)*Prop(r1 + r2 + r3)*Prop(p2 + r1 + r2 + r3);
endrepeat;
