l [interf2_2]= + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(p1 + p2)^2*
      Prop( - r1 - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*gs^4*
      Nc^-1 * (  - 8*p2.r1*r1.r2*s12 + 8*p2.r1*r1.r2*d*s12 - 2*p2.r1*r1.r2*d^2
         *s12 - 8*p2.r2*r1.r2*s12 + 8*p2.r2*r1.r2*d*s12 - 2*p2.r2*r1.r2*d^2*
         s12 - 4*r1.r2*s12^2 + 4*r1.r2*d*s12^2 - r1.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(p1 + p2)^2*Prop( - r1
       - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*gs^4*Nc * ( 16*
         p2.r1*r1.r2*s12 - 16*p2.r1*r1.r2*d*s12 + 4*p2.r1*r1.r2*d^2*s12 + 16*
         p2.r2*r1.r2*s12 - 16*p2.r2*r1.r2*d*s12 + 4*p2.r2*r1.r2*d^2*s12 + 8*
         r1.r2*s12^2 - 8*r1.r2*d*s12^2 + 2*r1.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(p1 + p2)^2*Prop( - r1
       - r2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*gs^4*Nc^3 * (  - 
         8*p2.r1*r1.r2*s12 + 8*p2.r1*r1.r2*d*s12 - 2*p2.r1*r1.r2*d^2*s12 - 8*
         p2.r2*r1.r2*s12 + 8*p2.r2*r1.r2*d*s12 - 2*p2.r2*r1.r2*d^2*s12 - 4*
         r1.r2*s12^2 + 4*r1.r2*d*s12^2 - r1.r2*d^2*s12^2 );

