l [interf2_1]= + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*
      Prop(p1 + p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r1,
      mu95)*gs^4*Nc^-1 * ( 4*r1(nu95)*s12^2 - 2*r1(nu95)*d*s12^2 + 8*r1(nu95)*
         p2.r1*s12 - 4*r1(nu95)*p2.r1*d*s12 + 8*r1(nu95)*p2.r2*s12 - 4*
         r1(nu95)*p2.r2*d*s12 + 6*r2(nu95)*s12^2 - 4*r2(nu95)*d*s12^2 + 1/2*
         r2(nu95)*d^2*s12^2 + 12*r2(nu95)*p2.r1*s12 - 8*r2(nu95)*p2.r1*d*s12
          + r2(nu95)*p2.r1*d^2*s12 + 12*r2(nu95)*p2.r2*s12 - 8*r2(nu95)*p2.r2*
         d*s12 + r2(nu95)*p2.r2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r1,mu95)*gs^4*
      Nc * (  - 8*r1(nu95)*s12^2 + 4*r1(nu95)*d*s12^2 - 16*r1(nu95)*p2.r1*s12
          + 8*r1(nu95)*p2.r1*d*s12 - 16*r1(nu95)*p2.r2*s12 + 8*r1(nu95)*p2.r2*
         d*s12 - 12*r2(nu95)*s12^2 + 8*r2(nu95)*d*s12^2 - r2(nu95)*d^2*s12^2
          - 24*r2(nu95)*p2.r1*s12 + 16*r2(nu95)*p2.r1*d*s12 - 2*r2(nu95)*p2.r1
         *d^2*s12 - 24*r2(nu95)*p2.r2*s12 + 16*r2(nu95)*p2.r2*d*s12 - 2*
         r2(nu95)*p2.r2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r1,mu95)*gs^4*
      Nc^3 * ( 4*r1(nu95)*s12^2 - 2*r1(nu95)*d*s12^2 + 8*r1(nu95)*p2.r1*s12 - 
         4*r1(nu95)*p2.r1*d*s12 + 8*r1(nu95)*p2.r2*s12 - 4*r1(nu95)*p2.r2*d*
         s12 + 6*r2(nu95)*s12^2 - 4*r2(nu95)*d*s12^2 + 1/2*r2(nu95)*d^2*s12^2
          + 12*r2(nu95)*p2.r1*s12 - 8*r2(nu95)*p2.r1*d*s12 + r2(nu95)*p2.r1*
         d^2*s12 + 12*r2(nu95)*p2.r2*s12 - 8*r2(nu95)*p2.r2*d*s12 + r2(nu95)*
         p2.r2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r2,mu95)*gs^4*
      Nc^-1 * (  - 2*r1(nu95)*s12^2 + 2*r1(nu95)*d*s12^2 - 1/2*r1(nu95)*d^2*
         s12^2 - 4*r1(nu95)*p2.r1*s12 + 4*r1(nu95)*p2.r1*d*s12 - r1(nu95)*
         p2.r1*d^2*s12 - 4*r1(nu95)*p2.r2*s12 + 4*r1(nu95)*p2.r2*d*s12 - 
         r1(nu95)*p2.r2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r2,mu95)*gs^4*
      Nc * ( 4*r1(nu95)*s12^2 - 4*r1(nu95)*d*s12^2 + r1(nu95)*d^2*s12^2 + 8*
         r1(nu95)*p2.r1*s12 - 8*r1(nu95)*p2.r1*d*s12 + 2*r1(nu95)*p2.r1*d^2*
         s12 + 8*r1(nu95)*p2.r2*s12 - 8*r1(nu95)*p2.r2*d*s12 + 2*r1(nu95)*
         p2.r2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r2,mu95)*gs^4*
      Nc^3 * (  - 2*r1(nu95)*s12^2 + 2*r1(nu95)*d*s12^2 - 1/2*r1(nu95)*d^2*
         s12^2 - 4*r1(nu95)*p2.r1*s12 + 4*r1(nu95)*p2.r1*d*s12 - r1(nu95)*
         p2.r1*d^2*s12 - 4*r1(nu95)*p2.r2*s12 + 4*r1(nu95)*p2.r2*d*s12 - 
         r1(nu95)*p2.r2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*
      gs^4*Nc^-1 * ( 12*p2.r1*r1.r2*s12 - 8*p2.r1*r1.r2*d*s12 + p2.r1*r1.r2*
         d^2*s12 + 12*p2.r2*r1.r2*s12 - 8*p2.r2*r1.r2*d*s12 + p2.r2*r1.r2*d^2*
         s12 + 6*r1.r2*s12^2 - 4*r1.r2*d*s12^2 + 1/2*r1.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*
      gs^4*Nc * (  - 24*p2.r1*r1.r2*s12 + 16*p2.r1*r1.r2*d*s12 - 2*p2.r1*r1.r2
         *d^2*s12 - 24*p2.r2*r1.r2*s12 + 16*p2.r2*r1.r2*d*s12 - 2*p2.r2*r1.r2*
         d^2*s12 - 12*r1.r2*s12^2 + 8*r1.r2*d*s12^2 - r1.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*
      gs^4*Nc^3 * ( 12*p2.r1*r1.r2*s12 - 8*p2.r1*r1.r2*d*s12 + p2.r1*r1.r2*d^2
         *s12 + 12*p2.r2*r1.r2*s12 - 8*p2.r2*r1.r2*d*s12 + p2.r2*r1.r2*d^2*s12
          + 6*r1.r2*s12^2 - 4*r1.r2*d*s12^2 + 1/2*r1.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,r2,mu95)*gs^4*
      Nc^-1 * (  - 6*p2(nu95)*s12^2 + 4*p2(nu95)*d*s12^2 - 1/2*p2(nu95)*d^2*
         s12^2 - 12*p2(nu95)*p2.r1*s12 + 8*p2(nu95)*p2.r1*d*s12 - p2(nu95)*
         p2.r1*d^2*s12 - 12*p2(nu95)*p2.r2*s12 + 8*p2(nu95)*p2.r2*d*s12 - 
         p2(nu95)*p2.r2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,r2,mu95)*gs^4*
      Nc * ( 12*p2(nu95)*s12^2 - 8*p2(nu95)*d*s12^2 + p2(nu95)*d^2*s12^2 + 24*
         p2(nu95)*p2.r1*s12 - 16*p2(nu95)*p2.r1*d*s12 + 2*p2(nu95)*p2.r1*d^2*
         s12 + 24*p2(nu95)*p2.r2*s12 - 16*p2(nu95)*p2.r2*d*s12 + 2*p2(nu95)*
         p2.r2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,r2,mu95)*gs^4*
      Nc^3 * (  - 6*p2(nu95)*s12^2 + 4*p2(nu95)*d*s12^2 - 1/2*p2(nu95)*d^2*
         s12^2 - 12*p2(nu95)*p2.r1*s12 + 8*p2(nu95)*p2.r1*d*s12 - p2(nu95)*
         p2.r1*d^2*s12 - 12*p2(nu95)*p2.r2*s12 + 8*p2(nu95)*p2.r2*d*s12 - 
         p2(nu95)*p2.r2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*
      gs^4*Nc^-1 * (  - 12*p2.r1*p2.r2*s12 + 8*p2.r1*p2.r2*d*s12 - p2.r1*p2.r2
         *d^2*s12 - 6*p2.r2*s12^2 + 4*p2.r2*d*s12^2 - 1/2*p2.r2*d^2*s12^2 - 12
         *p2.r2^2*s12 + 8*p2.r2^2*d*s12 - p2.r2^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*
      gs^4*Nc * ( 24*p2.r1*p2.r2*s12 - 16*p2.r1*p2.r2*d*s12 + 2*p2.r1*p2.r2*
         d^2*s12 + 12*p2.r2*s12^2 - 8*p2.r2*d*s12^2 + p2.r2*d^2*s12^2 + 24*
         p2.r2^2*s12 - 16*p2.r2^2*d*s12 + 2*p2.r2^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*
      gs^4*Nc^3 * (  - 12*p2.r1*p2.r2*s12 + 8*p2.r1*p2.r2*d*s12 - p2.r1*p2.r2*
         d^2*s12 - 6*p2.r2*s12^2 + 4*p2.r2*d*s12^2 - 1/2*p2.r2*d^2*s12^2 - 12*
         p2.r2^2*s12 + 8*p2.r2^2*d*s12 - p2.r2^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*
      gs^4*Nc^-1 * ( 12*p2.r1*p2.r2*s12 - 8*p2.r1*p2.r2*d*s12 + p2.r1*p2.r2*
         d^2*s12 + 6*p2.r1*s12^2 - 4*p2.r1*d*s12^2 + 1/2*p2.r1*d^2*s12^2 + 12*
         p2.r1^2*s12 - 8*p2.r1^2*d*s12 + p2.r1^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*
      gs^4*Nc * (  - 24*p2.r1*p2.r2*s12 + 16*p2.r1*p2.r2*d*s12 - 2*p2.r1*p2.r2
         *d^2*s12 - 12*p2.r1*s12^2 + 8*p2.r1*d*s12^2 - p2.r1*d^2*s12^2 - 24*
         p2.r1^2*s12 + 16*p2.r1^2*d*s12 - 2*p2.r1^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*
      gs^4*Nc^3 * ( 12*p2.r1*p2.r2*s12 - 8*p2.r1*p2.r2*d*s12 + p2.r1*p2.r2*d^2
         *s12 + 6*p2.r1*s12^2 - 4*p2.r1*d*s12^2 + 1/2*p2.r1*d^2*s12^2 + 12*
         p2.r1^2*s12 - 8*p2.r1^2*d*s12 + p2.r1^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,r2,mu95)*gs^4*
      Nc^-1 * ( 2*p1(nu95)*s12^2 - 2*p1(nu95)*d*s12^2 + 1/2*p1(nu95)*d^2*s12^2
          + 4*p1(nu95)*p2.r1*s12 - 4*p1(nu95)*p2.r1*d*s12 + p1(nu95)*p2.r1*d^2
         *s12 + 4*p1(nu95)*p2.r2*s12 - 4*p1(nu95)*p2.r2*d*s12 + p1(nu95)*p2.r2
         *d^2*s12 - 4*p2(nu95)*s12^2 + 2*p2(nu95)*d*s12^2 - 8*p2(nu95)*p2.r1*
         s12 + 4*p2(nu95)*p2.r1*d*s12 - 8*p2(nu95)*p2.r2*s12 + 4*p2(nu95)*
         p2.r2*d*s12 + 4*r1(nu95)*s12^2 - 2*r1(nu95)*d*s12^2 + 8*r1(nu95)*
         p2.r1*s12 - 4*r1(nu95)*p2.r1*d*s12 + 8*r1(nu95)*p2.r2*s12 - 4*
         r1(nu95)*p2.r2*d*s12 + 8*r2(nu95)*s12^2 - 6*r2(nu95)*d*s12^2 + 
         r2(nu95)*d^2*s12^2 + 16*r2(nu95)*p2.r1*s12 - 12*r2(nu95)*p2.r1*d*s12
          + 2*r2(nu95)*p2.r1*d^2*s12 + 16*r2(nu95)*p2.r2*s12 - 12*r2(nu95)*
         p2.r2*d*s12 + 2*r2(nu95)*p2.r2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,r2,mu95)*gs^4*
      Nc * (  - 4*p1(nu95)*s12^2 + 4*p1(nu95)*d*s12^2 - p1(nu95)*d^2*s12^2 - 8
         *p1(nu95)*p2.r1*s12 + 8*p1(nu95)*p2.r1*d*s12 - 2*p1(nu95)*p2.r1*d^2*
         s12 - 8*p1(nu95)*p2.r2*s12 + 8*p1(nu95)*p2.r2*d*s12 - 2*p1(nu95)*
         p2.r2*d^2*s12 + 8*p2(nu95)*s12^2 - 4*p2(nu95)*d*s12^2 + 16*p2(nu95)*
         p2.r1*s12 - 8*p2(nu95)*p2.r1*d*s12 + 16*p2(nu95)*p2.r2*s12 - 8*
         p2(nu95)*p2.r2*d*s12 - 8*r1(nu95)*s12^2 + 4*r1(nu95)*d*s12^2 - 16*
         r1(nu95)*p2.r1*s12 + 8*r1(nu95)*p2.r1*d*s12 - 16*r1(nu95)*p2.r2*s12
          + 8*r1(nu95)*p2.r2*d*s12 - 16*r2(nu95)*s12^2 + 12*r2(nu95)*d*s12^2
          - 2*r2(nu95)*d^2*s12^2 - 32*r2(nu95)*p2.r1*s12 + 24*r2(nu95)*p2.r1*d
         *s12 - 4*r2(nu95)*p2.r1*d^2*s12 - 32*r2(nu95)*p2.r2*s12 + 24*r2(nu95)
         *p2.r2*d*s12 - 4*r2(nu95)*p2.r2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,r2,mu95)*gs^4*
      Nc^3 * ( 2*p1(nu95)*s12^2 - 2*p1(nu95)*d*s12^2 + 1/2*p1(nu95)*d^2*s12^2
          + 4*p1(nu95)*p2.r1*s12 - 4*p1(nu95)*p2.r1*d*s12 + p1(nu95)*p2.r1*d^2
         *s12 + 4*p1(nu95)*p2.r2*s12 - 4*p1(nu95)*p2.r2*d*s12 + p1(nu95)*p2.r2
         *d^2*s12 - 4*p2(nu95)*s12^2 + 2*p2(nu95)*d*s12^2 - 8*p2(nu95)*p2.r1*
         s12 + 4*p2(nu95)*p2.r1*d*s12 - 8*p2(nu95)*p2.r2*s12 + 4*p2(nu95)*
         p2.r2*d*s12 + 4*r1(nu95)*s12^2 - 2*r1(nu95)*d*s12^2 + 8*r1(nu95)*
         p2.r1*s12 - 4*r1(nu95)*p2.r1*d*s12 + 8*r1(nu95)*p2.r2*s12 - 4*
         r1(nu95)*p2.r2*d*s12 + 8*r2(nu95)*s12^2 - 6*r2(nu95)*d*s12^2 + 
         r2(nu95)*d^2*s12^2 + 16*r2(nu95)*p2.r1*s12 - 12*r2(nu95)*p2.r1*d*s12
          + 2*r2(nu95)*p2.r1*d^2*s12 + 16*r2(nu95)*p2.r2*s12 - 12*r2(nu95)*
         p2.r2*d*s12 + 2*r2(nu95)*p2.r2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*
      gs^4*Nc^-1 * ( 8*p1.r1*p2.r1*s12 - 4*p1.r1*p2.r1*d*s12 + 8*p1.r1*p2.r2*
         s12 - 4*p1.r1*p2.r2*d*s12 + 4*p1.r1*s12^2 - 2*p1.r1*d*s12^2 + 12*
         p1.r2*p2.r1*s12 - 8*p1.r2*p2.r1*d*s12 + p1.r2*p2.r1*d^2*s12 + 12*
         p1.r2*p2.r2*s12 - 8*p1.r2*p2.r2*d*s12 + p1.r2*p2.r2*d^2*s12 + 6*p1.r2
         *s12^2 - 4*p1.r2*d*s12^2 + 1/2*p1.r2*d^2*s12^2 + 8*p2.r1*p2.r2*s12 - 
         4*p2.r1*p2.r2*d*s12 + 8*p2.r1*r1.r2*s12 - 4*p2.r1*r1.r2*d*s12 + 4*
         p2.r1*s12^2 - 2*p2.r1*d*s12^2 + 8*p2.r1^2*s12 - 4*p2.r1^2*d*s12 + 8*
         p2.r2*r1.r2*s12 - 4*p2.r2*r1.r2*d*s12 + 4*r1.r2*s12^2 - 2*r1.r2*d*
         s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*
      gs^4*Nc * (  - 16*p1.r1*p2.r1*s12 + 8*p1.r1*p2.r1*d*s12 - 16*p1.r1*p2.r2
         *s12 + 8*p1.r1*p2.r2*d*s12 - 8*p1.r1*s12^2 + 4*p1.r1*d*s12^2 - 24*
         p1.r2*p2.r1*s12 + 16*p1.r2*p2.r1*d*s12 - 2*p1.r2*p2.r1*d^2*s12 - 24*
         p1.r2*p2.r2*s12 + 16*p1.r2*p2.r2*d*s12 - 2*p1.r2*p2.r2*d^2*s12 - 12*
         p1.r2*s12^2 + 8*p1.r2*d*s12^2 - p1.r2*d^2*s12^2 - 16*p2.r1*p2.r2*s12
          + 8*p2.r1*p2.r2*d*s12 - 16*p2.r1*r1.r2*s12 + 8*p2.r1*r1.r2*d*s12 - 8
         *p2.r1*s12^2 + 4*p2.r1*d*s12^2 - 16*p2.r1^2*s12 + 8*p2.r1^2*d*s12 - 
         16*p2.r2*r1.r2*s12 + 8*p2.r2*r1.r2*d*s12 - 8*r1.r2*s12^2 + 4*r1.r2*d*
         s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*
      gs^4*Nc^3 * ( 8*p1.r1*p2.r1*s12 - 4*p1.r1*p2.r1*d*s12 + 8*p1.r1*p2.r2*
         s12 - 4*p1.r1*p2.r2*d*s12 + 4*p1.r1*s12^2 - 2*p1.r1*d*s12^2 + 12*
         p1.r2*p2.r1*s12 - 8*p1.r2*p2.r1*d*s12 + p1.r2*p2.r1*d^2*s12 + 12*
         p1.r2*p2.r2*s12 - 8*p1.r2*p2.r2*d*s12 + p1.r2*p2.r2*d^2*s12 + 6*p1.r2
         *s12^2 - 4*p1.r2*d*s12^2 + 1/2*p1.r2*d^2*s12^2 + 8*p2.r1*p2.r2*s12 - 
         4*p2.r1*p2.r2*d*s12 + 8*p2.r1*r1.r2*s12 - 4*p2.r1*r1.r2*d*s12 + 4*
         p2.r1*s12^2 - 2*p2.r1*d*s12^2 + 8*p2.r1^2*s12 - 4*p2.r1^2*d*s12 + 8*
         p2.r2*r1.r2*s12 - 4*p2.r2*r1.r2*d*s12 + 4*r1.r2*s12^2 - 2*r1.r2*d*
         s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*
      gs^4*Nc^-1 * (  - 4*p1.r1*p2.r1*s12 + 4*p1.r1*p2.r1*d*s12 - p1.r1*p2.r1*
         d^2*s12 - 4*p1.r1*p2.r2*s12 + 4*p1.r1*p2.r2*d*s12 - p1.r1*p2.r2*d^2*
         s12 - 2*p1.r1*s12^2 + 2*p1.r1*d*s12^2 - 1/2*p1.r1*d^2*s12^2 + 8*p2.r1
         *p2.r2*s12 - 4*p2.r1*p2.r2*d*s12 - 16*p2.r1*r1.r2*s12 + 12*p2.r1*
         r1.r2*d*s12 - 2*p2.r1*r1.r2*d^2*s12 + 4*p2.r1*s12^2 - 2*p2.r1*d*s12^2
          + 8*p2.r1^2*s12 - 4*p2.r1^2*d*s12 - 16*p2.r2*r1.r2*s12 + 12*p2.r2*
         r1.r2*d*s12 - 2*p2.r2*r1.r2*d^2*s12 - 8*r1.r2*s12^2 + 6*r1.r2*d*s12^2
          - r1.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*
      gs^4*Nc * ( 8*p1.r1*p2.r1*s12 - 8*p1.r1*p2.r1*d*s12 + 2*p1.r1*p2.r1*d^2*
         s12 + 8*p1.r1*p2.r2*s12 - 8*p1.r1*p2.r2*d*s12 + 2*p1.r1*p2.r2*d^2*s12
          + 4*p1.r1*s12^2 - 4*p1.r1*d*s12^2 + p1.r1*d^2*s12^2 - 16*p2.r1*p2.r2
         *s12 + 8*p2.r1*p2.r2*d*s12 + 32*p2.r1*r1.r2*s12 - 24*p2.r1*r1.r2*d*
         s12 + 4*p2.r1*r1.r2*d^2*s12 - 8*p2.r1*s12^2 + 4*p2.r1*d*s12^2 - 16*
         p2.r1^2*s12 + 8*p2.r1^2*d*s12 + 32*p2.r2*r1.r2*s12 - 24*p2.r2*r1.r2*d
         *s12 + 4*p2.r2*r1.r2*d^2*s12 + 16*r1.r2*s12^2 - 12*r1.r2*d*s12^2 + 2*
         r1.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*
      gs^4*Nc^3 * (  - 4*p1.r1*p2.r1*s12 + 4*p1.r1*p2.r1*d*s12 - p1.r1*p2.r1*
         d^2*s12 - 4*p1.r1*p2.r2*s12 + 4*p1.r1*p2.r2*d*s12 - p1.r1*p2.r2*d^2*
         s12 - 2*p1.r1*s12^2 + 2*p1.r1*d*s12^2 - 1/2*p1.r1*d^2*s12^2 + 8*p2.r1
         *p2.r2*s12 - 4*p2.r1*p2.r2*d*s12 - 16*p2.r1*r1.r2*s12 + 12*p2.r1*
         r1.r2*d*s12 - 2*p2.r1*r1.r2*d^2*s12 + 4*p2.r1*s12^2 - 2*p2.r1*d*s12^2
          + 8*p2.r1^2*s12 - 4*p2.r1^2*d*s12 - 16*p2.r2*r1.r2*s12 + 12*p2.r2*
         r1.r2*d*s12 - 2*p2.r2*r1.r2*d^2*s12 - 8*r1.r2*s12^2 + 6*r1.r2*d*s12^2
          - r1.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*
      gs^4*Nc^-1 * (  - 3*s12^3 + 2*d*s12^3 - 1/4*d^2*s12^3 - 6*p2.r1*s12^2 + 
         4*p2.r1*d*s12^2 - 1/2*p2.r1*d^2*s12^2 - 6*p2.r2*s12^2 + 4*p2.r2*d*
         s12^2 - 1/2*p2.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*
      gs^4*Nc * ( 6*s12^3 - 4*d*s12^3 + 1/2*d^2*s12^3 + 12*p2.r1*s12^2 - 8*
         p2.r1*d*s12^2 + p2.r1*d^2*s12^2 + 12*p2.r2*s12^2 - 8*p2.r2*d*s12^2 + 
         p2.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)*Prop(p1 + 
      p2)^2*Prop( - r1 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*
      gs^4*Nc^3 * (  - 3*s12^3 + 2*d*s12^3 - 1/4*d^2*s12^3 - 6*p2.r1*s12^2 + 4
         *p2.r1*d*s12^2 - 1/2*p2.r1*d^2*s12^2 - 6*p2.r2*s12^2 + 4*p2.r2*d*
         s12^2 - 1/2*p2.r2*d^2*s12^2 );

