l [interf1_1]= + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)^2*
      Prop(p1 + p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^4*Nc^-1
       * (  - 2*s12^3 + 2*d*s12^3 - 1/2*d^2*s12^3 - 8*p2.r1*p2.r2*s12 + 8*
         p2.r1*p2.r2*d*s12 - 2*p2.r1*p2.r2*d^2*s12 - 4*p2.r1*s12^2 + 4*p2.r1*d
         *s12^2 - p2.r1*d^2*s12^2 - 8*p2.r2*s12^2 + 8*p2.r2*d*s12^2 - 2*p2.r2*
         d^2*s12^2 - 8*p2.r2^2*s12 + 8*p2.r2^2*d*s12 - 2*p2.r2^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)^2*Prop(p1
       + p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^4*Nc * ( 4*
         s12^3 - 4*d*s12^3 + d^2*s12^3 + 16*p2.r1*p2.r2*s12 - 16*p2.r1*p2.r2*d
         *s12 + 4*p2.r1*p2.r2*d^2*s12 + 8*p2.r1*s12^2 - 8*p2.r1*d*s12^2 + 2*
         p2.r1*d^2*s12^2 + 16*p2.r2*s12^2 - 16*p2.r2*d*s12^2 + 4*p2.r2*d^2*
         s12^2 + 16*p2.r2^2*s12 - 16*p2.r2^2*d*s12 + 4*p2.r2^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)^2*Prop(p1
       + p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*gs^4*Nc^3 * (  - 
         2*s12^3 + 2*d*s12^3 - 1/2*d^2*s12^3 - 8*p2.r1*p2.r2*s12 + 8*p2.r1*
         p2.r2*d*s12 - 2*p2.r1*p2.r2*d^2*s12 - 4*p2.r1*s12^2 + 4*p2.r1*d*s12^2
          - p2.r1*d^2*s12^2 - 8*p2.r2*s12^2 + 8*p2.r2*d*s12^2 - 2*p2.r2*d^2*
         s12^2 - 8*p2.r2^2*s12 + 8*p2.r2^2*d*s12 - 2*p2.r2^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)^2*Prop(p1
       + p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^4*Nc^-1 * ( 8*
         p1.r2*p2.r1*s12 - 8*p1.r2*p2.r1*d*s12 + 2*p1.r2*p2.r1*d^2*s12 + 8*
         p1.r2*p2.r2*s12 - 8*p1.r2*p2.r2*d*s12 + 2*p1.r2*p2.r2*d^2*s12 + 4*
         p1.r2*s12^2 - 4*p1.r2*d*s12^2 + p1.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)^2*Prop(p1
       + p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^4*Nc * (  - 16
         *p1.r2*p2.r1*s12 + 16*p1.r2*p2.r1*d*s12 - 4*p1.r2*p2.r1*d^2*s12 - 16*
         p1.r2*p2.r2*s12 + 16*p1.r2*p2.r2*d*s12 - 4*p1.r2*p2.r2*d^2*s12 - 8*
         p1.r2*s12^2 + 8*p1.r2*d*s12^2 - 2*p1.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)^2*Prop(p1
       + p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*gs^4*Nc^3 * ( 8*
         p1.r2*p2.r1*s12 - 8*p1.r2*p2.r1*d*s12 + 2*p1.r2*p2.r1*d^2*s12 + 8*
         p1.r2*p2.r2*s12 - 8*p1.r2*p2.r2*d*s12 + 2*p1.r2*p2.r2*d^2*s12 + 4*
         p1.r2*s12^2 - 4*p1.r2*d*s12^2 + p1.r2*d^2*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)^2*Prop(p1
       + p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4*Nc^-1 * ( 2*
         s12^3 - 2*d*s12^3 + 1/2*d^2*s12^3 + 8*p2.r1*p2.r2*s12 - 8*p2.r1*p2.r2
         *d*s12 + 2*p2.r1*p2.r2*d^2*s12 + 4*p2.r1*s12^2 - 4*p2.r1*d*s12^2 + 
         p2.r1*d^2*s12^2 + 8*p2.r2*s12^2 - 8*p2.r2*d*s12^2 + 2*p2.r2*d^2*s12^2
          + 8*p2.r2^2*s12 - 8*p2.r2^2*d*s12 + 2*p2.r2^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)^2*Prop(p1
       + p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4*Nc * (  - 4*
         s12^3 + 4*d*s12^3 - d^2*s12^3 - 16*p2.r1*p2.r2*s12 + 16*p2.r1*p2.r2*d
         *s12 - 4*p2.r1*p2.r2*d^2*s12 - 8*p2.r1*s12^2 + 8*p2.r1*d*s12^2 - 2*
         p2.r1*d^2*s12^2 - 16*p2.r2*s12^2 + 16*p2.r2*d*s12^2 - 4*p2.r2*d^2*
         s12^2 - 16*p2.r2^2*s12 + 16*p2.r2^2*d*s12 - 4*p2.r2^2*d^2*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop( - q - r1)^2*Prop(p1
       + p2)^2*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*gs^4*Nc^3 * ( 2*
         s12^3 - 2*d*s12^3 + 1/2*d^2*s12^3 + 8*p2.r1*p2.r2*s12 - 8*p2.r1*p2.r2
         *d*s12 + 2*p2.r1*p2.r2*d^2*s12 + 4*p2.r1*s12^2 - 4*p2.r1*d*s12^2 + 
         p2.r1*d^2*s12^2 + 8*p2.r2*s12^2 - 8*p2.r2*d*s12^2 + 2*p2.r2*d^2*s12^2
          + 8*p2.r2^2*s12 - 8*p2.r2^2*d*s12 + 2*p2.r2^2*d^2*s12 );

