l [interf4_3]= + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*
      Prop( - p2 - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r1,
      mu95)*gs^4*Nc * ( 64*r2(nu95)*p2.r1*p2.r2 - 16*r2(nu95)*p2.r1*p2.r2*d + 
         32*r2(nu95)*p2.r1*r1.r2 - 8*r2(nu95)*p2.r1*r1.r2*d + 16*r2(nu95)*
         p2.r1*s12 - 4*r2(nu95)*p2.r1*d*s12 + 32*r2(nu95)*p2.r1^2 - 8*r2(nu95)
         *p2.r1^2*d + 32*r2(nu95)*p2.r2*r1.r2 - 8*r2(nu95)*p2.r2*r1.r2*d + 16*
         r2(nu95)*p2.r2*s12 - 4*r2(nu95)*p2.r2*d*s12 + 32*r2(nu95)*p2.r2^2 - 8
         *r2(nu95)*p2.r2^2*d + 16*r2(nu95)*r1.r2*s12 - 4*r2(nu95)*r1.r2*d*s12
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r1,mu95)*gs^4
      *Nc^3 * (  - 64*r2(nu95)*p2.r1*p2.r2 + 16*r2(nu95)*p2.r1*p2.r2*d - 32*
         r2(nu95)*p2.r1*r1.r2 + 8*r2(nu95)*p2.r1*r1.r2*d - 16*r2(nu95)*p2.r1*
         s12 + 4*r2(nu95)*p2.r1*d*s12 - 32*r2(nu95)*p2.r1^2 + 8*r2(nu95)*
         p2.r1^2*d - 32*r2(nu95)*p2.r2*r1.r2 + 8*r2(nu95)*p2.r2*r1.r2*d - 16*
         r2(nu95)*p2.r2*s12 + 4*r2(nu95)*p2.r2*d*s12 - 32*r2(nu95)*p2.r2^2 + 8
         *r2(nu95)*p2.r2^2*d - 16*r2(nu95)*r1.r2*s12 + 4*r2(nu95)*r1.r2*d*s12
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r2,mu95)*gs^4
      *Nc * (  - 64*r1(nu95)*p2.r1*p2.r2 + 16*r1(nu95)*p2.r1*p2.r2*d - 32*
         r1(nu95)*p2.r1*r1.r2 + 8*r1(nu95)*p2.r1*r1.r2*d - 16*r1(nu95)*p2.r1*
         s12 + 4*r1(nu95)*p2.r1*d*s12 - 32*r1(nu95)*p2.r1^2 + 8*r1(nu95)*
         p2.r1^2*d - 32*r1(nu95)*p2.r2*r1.r2 + 8*r1(nu95)*p2.r2*r1.r2*d - 16*
         r1(nu95)*p2.r2*s12 + 4*r1(nu95)*p2.r2*d*s12 - 32*r1(nu95)*p2.r2^2 + 8
         *r1(nu95)*p2.r2^2*d - 16*r1(nu95)*r1.r2*s12 + 4*r1(nu95)*r1.r2*d*s12
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,r2,mu95)*gs^4
      *Nc^3 * ( 64*r1(nu95)*p2.r1*p2.r2 - 16*r1(nu95)*p2.r1*p2.r2*d + 32*
         r1(nu95)*p2.r1*r1.r2 - 8*r1(nu95)*p2.r1*r1.r2*d + 16*r1(nu95)*p2.r1*
         s12 - 4*r1(nu95)*p2.r1*d*s12 + 32*r1(nu95)*p2.r1^2 - 8*r1(nu95)*
         p2.r1^2*d + 32*r1(nu95)*p2.r2*r1.r2 - 8*r1(nu95)*p2.r2*r1.r2*d + 16*
         r1(nu95)*p2.r2*s12 - 4*r1(nu95)*p2.r2*d*s12 + 32*r1(nu95)*p2.r2^2 - 8
         *r1(nu95)*p2.r2^2*d + 16*r1(nu95)*r1.r2*s12 - 4*r1(nu95)*r1.r2*d*s12
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*
      gs^4*Nc * (  - 8*p2.r1*p2.r2*r1.r2 + 4*p2.r1*p2.r2*r1.r2*d + 4*p2.r1*
         p2.r2*s12 - 2*p2.r1*p2.r2*d*s12 + 8*p2.r1*p2.r2^2 - 4*p2.r1*p2.r2^2*d
          - 8*p2.r1*r1.r2^2 + 4*p2.r1*r1.r2^2*d - 4*p2.r1^2*s12 + 2*p2.r1^2*d*
         s12 - 8*p2.r1^3 + 4*p2.r1^3*d - 4*p2.r2*r1.r2*s12 + 2*p2.r2*r1.r2*d*
         s12 - 8*p2.r2*r1.r2^2 + 4*p2.r2*r1.r2^2*d - 8*p2.r2^2*r1.r2 + 4*
         p2.r2^2*r1.r2*d - 4*r1.r2^2*s12 + 2*r1.r2^2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*
      gs^4*Nc^3 * ( 8*p2.r1*p2.r2*r1.r2 - 4*p2.r1*p2.r2*r1.r2*d - 4*p2.r1*
         p2.r2*s12 + 2*p2.r1*p2.r2*d*s12 - 8*p2.r1*p2.r2^2 + 4*p2.r1*p2.r2^2*d
          + 8*p2.r1*r1.r2^2 - 4*p2.r1*r1.r2^2*d + 4*p2.r1^2*s12 - 2*p2.r1^2*d*
         s12 + 8*p2.r1^3 - 4*p2.r1^3*d + 4*p2.r2*r1.r2*s12 - 2*p2.r2*r1.r2*d*
         s12 + 8*p2.r2*r1.r2^2 - 4*p2.r2*r1.r2^2*d + 8*p2.r2^2*r1.r2 - 4*
         p2.r2^2*r1.r2*d + 4*r1.r2^2*s12 - 2*r1.r2^2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,r2,mu95)*gs^4
      *Nc * ( 64*p2(nu95)*p2.r1*p2.r2 - 16*p2(nu95)*p2.r1*p2.r2*d + 32*
         p2(nu95)*p2.r1*r1.r2 - 8*p2(nu95)*p2.r1*r1.r2*d + 16*p2(nu95)*p2.r1*
         s12 - 4*p2(nu95)*p2.r1*d*s12 + 32*p2(nu95)*p2.r1^2 - 8*p2(nu95)*
         p2.r1^2*d + 32*p2(nu95)*p2.r2*r1.r2 - 8*p2(nu95)*p2.r2*r1.r2*d + 16*
         p2(nu95)*p2.r2*s12 - 4*p2(nu95)*p2.r2*d*s12 + 32*p2(nu95)*p2.r2^2 - 8
         *p2(nu95)*p2.r2^2*d + 16*p2(nu95)*r1.r2*s12 - 4*p2(nu95)*r1.r2*d*s12
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,r2,mu95)*gs^4
      *Nc^3 * (  - 64*p2(nu95)*p2.r1*p2.r2 + 16*p2(nu95)*p2.r1*p2.r2*d - 32*
         p2(nu95)*p2.r1*r1.r2 + 8*p2(nu95)*p2.r1*r1.r2*d - 16*p2(nu95)*p2.r1*
         s12 + 4*p2(nu95)*p2.r1*d*s12 - 32*p2(nu95)*p2.r1^2 + 8*p2(nu95)*
         p2.r1^2*d - 32*p2(nu95)*p2.r2*r1.r2 + 8*p2(nu95)*p2.r2*r1.r2*d - 16*
         p2(nu95)*p2.r2*s12 + 4*p2(nu95)*p2.r2*d*s12 - 32*p2(nu95)*p2.r2^2 + 8
         *p2(nu95)*p2.r2^2*d - 16*p2(nu95)*r1.r2*s12 + 4*p2(nu95)*r1.r2*d*s12
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*
      gs^4*Nc * ( 16*p2.r1*p2.r2*r1.r2 - 8*p2.r1*p2.r2*r1.r2*d + 8*p2.r1*p2.r2
         *s12 - 4*p2.r1*p2.r2*d*s12 + 24*p2.r1*p2.r2^2 - 12*p2.r1*p2.r2^2*d + 
         4*p2.r1*r1.r2*s12 - 2*p2.r1*r1.r2*d*s12 + 8*p2.r1^2*p2.r2 - 4*p2.r1^2
         *p2.r2*d + 8*p2.r1^2*r1.r2 - 4*p2.r1^2*r1.r2*d - 4*p2.r1^2*s12 + 2*
         p2.r1^2*d*s12 - 8*p2.r1^3 + 4*p2.r1^3*d + 4*p2.r2*r1.r2*s12 - 2*p2.r2
         *r1.r2*d*s12 + 8*p2.r2^2*r1.r2 - 4*p2.r2^2*r1.r2*d + 4*p2.r2^2*s12 - 
         2*p2.r2^2*d*s12 + 8*p2.r2^3 - 4*p2.r2^3*d )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r1,mu95,nu95)*
      gs^4*Nc^3 * (  - 16*p2.r1*p2.r2*r1.r2 + 8*p2.r1*p2.r2*r1.r2*d - 8*p2.r1*
         p2.r2*s12 + 4*p2.r1*p2.r2*d*s12 - 24*p2.r1*p2.r2^2 + 12*p2.r1*p2.r2^2
         *d - 4*p2.r1*r1.r2*s12 + 2*p2.r1*r1.r2*d*s12 - 8*p2.r1^2*p2.r2 + 4*
         p2.r1^2*p2.r2*d - 8*p2.r1^2*r1.r2 + 4*p2.r1^2*r1.r2*d + 4*p2.r1^2*s12
          - 2*p2.r1^2*d*s12 + 8*p2.r1^3 - 4*p2.r1^3*d - 4*p2.r2*r1.r2*s12 + 2*
         p2.r2*r1.r2*d*s12 - 8*p2.r2^2*r1.r2 + 4*p2.r2^2*r1.r2*d - 4*p2.r2^2*
         s12 + 2*p2.r2^2*d*s12 - 8*p2.r2^3 + 4*p2.r2^3*d )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*
      gs^4*Nc * (  - 48*p2.r1*p2.r2*r1.r2 + 24*p2.r1*p2.r2*r1.r2*d - 8*p2.r1*
         p2.r2*s12 + 4*p2.r1*p2.r2*d*s12 - 16*p2.r1*p2.r2^2 + 8*p2.r1*p2.r2^2*
         d - 16*p2.r1*r1.r2*s12 + 8*p2.r1*r1.r2*d*s12 - 16*p2.r1*r1.r2^2 + 8*
         p2.r1*r1.r2^2*d - 48*p2.r1^2*p2.r2 + 24*p2.r1^2*p2.r2*d - 32*p2.r1^2*
         r1.r2 + 16*p2.r1^2*r1.r2*d - 16*p2.r1^2*s12 + 8*p2.r1^2*d*s12 - 32*
         p2.r1^3 + 16*p2.r1^3*d - 8*p2.r2*r1.r2*s12 + 4*p2.r2*r1.r2*d*s12 - 16
         *p2.r2*r1.r2^2 + 8*p2.r2*r1.r2^2*d - 16*p2.r2^2*r1.r2 + 8*p2.r2^2*
         r1.r2*d - 8*r1.r2^2*s12 + 4*r1.r2^2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p1,r2,mu95,nu95)*
      gs^4*Nc^3 * ( 48*p2.r1*p2.r2*r1.r2 - 24*p2.r1*p2.r2*r1.r2*d + 8*p2.r1*
         p2.r2*s12 - 4*p2.r1*p2.r2*d*s12 + 16*p2.r1*p2.r2^2 - 8*p2.r1*p2.r2^2*
         d + 16*p2.r1*r1.r2*s12 - 8*p2.r1*r1.r2*d*s12 + 16*p2.r1*r1.r2^2 - 8*
         p2.r1*r1.r2^2*d + 48*p2.r1^2*p2.r2 - 24*p2.r1^2*p2.r2*d + 32*p2.r1^2*
         r1.r2 - 16*p2.r1^2*r1.r2*d + 16*p2.r1^2*s12 - 8*p2.r1^2*d*s12 + 32*
         p2.r1^3 - 16*p2.r1^3*d + 8*p2.r2*r1.r2*s12 - 4*p2.r2*r1.r2*d*s12 + 16
         *p2.r2*r1.r2^2 - 8*p2.r2*r1.r2^2*d + 16*p2.r2^2*r1.r2 - 8*p2.r2^2*
         r1.r2*d + 8*r1.r2^2*s12 - 4*r1.r2^2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,r2,mu95)*gs^4
      *Nc * ( 64*p1(nu95)*p2.r1*p2.r2 - 16*p1(nu95)*p2.r1*p2.r2*d + 32*
         p1(nu95)*p2.r1*r1.r2 - 8*p1(nu95)*p2.r1*r1.r2*d + 16*p1(nu95)*p2.r1*
         s12 - 4*p1(nu95)*p2.r1*d*s12 + 32*p1(nu95)*p2.r1^2 - 8*p1(nu95)*
         p2.r1^2*d + 32*p1(nu95)*p2.r2*r1.r2 - 8*p1(nu95)*p2.r2*r1.r2*d + 16*
         p1(nu95)*p2.r2*s12 - 4*p1(nu95)*p2.r2*d*s12 + 32*p1(nu95)*p2.r2^2 - 8
         *p1(nu95)*p2.r2^2*d + 16*p1(nu95)*r1.r2*s12 - 4*p1(nu95)*r1.r2*d*s12
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,r2,mu95)*gs^4
      *Nc^3 * (  - 64*p1(nu95)*p2.r1*p2.r2 + 16*p1(nu95)*p2.r1*p2.r2*d - 32*
         p1(nu95)*p2.r1*r1.r2 + 8*p1(nu95)*p2.r1*r1.r2*d - 16*p1(nu95)*p2.r1*
         s12 + 4*p1(nu95)*p2.r1*d*s12 - 32*p1(nu95)*p2.r1^2 + 8*p1(nu95)*
         p2.r1^2*d - 32*p1(nu95)*p2.r2*r1.r2 + 8*p1(nu95)*p2.r2*r1.r2*d - 16*
         p1(nu95)*p2.r2*s12 + 4*p1(nu95)*p2.r2*d*s12 - 32*p1(nu95)*p2.r2^2 + 8
         *p1(nu95)*p2.r2^2*d - 16*p1(nu95)*r1.r2*s12 + 4*p1(nu95)*r1.r2*d*s12
          )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*
      gs^4*Nc * ( 64*p1.r2*p2.r1*p2.r2 - 16*p1.r2*p2.r1*p2.r2*d + 32*p1.r2*
         p2.r1*r1.r2 - 8*p1.r2*p2.r1*r1.r2*d + 16*p1.r2*p2.r1*s12 - 4*p1.r2*
         p2.r1*d*s12 + 32*p1.r2*p2.r1^2 - 8*p1.r2*p2.r1^2*d + 32*p1.r2*p2.r2*
         r1.r2 - 8*p1.r2*p2.r2*r1.r2*d + 16*p1.r2*p2.r2*s12 - 4*p1.r2*p2.r2*d*
         s12 + 32*p1.r2*p2.r2^2 - 8*p1.r2*p2.r2^2*d + 16*p1.r2*r1.r2*s12 - 4*
         p1.r2*r1.r2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r1,mu95,nu95)*
      gs^4*Nc^3 * (  - 64*p1.r2*p2.r1*p2.r2 + 16*p1.r2*p2.r1*p2.r2*d - 32*
         p1.r2*p2.r1*r1.r2 + 8*p1.r2*p2.r1*r1.r2*d - 16*p1.r2*p2.r1*s12 + 4*
         p1.r2*p2.r1*d*s12 - 32*p1.r2*p2.r1^2 + 8*p1.r2*p2.r1^2*d - 32*p1.r2*
         p2.r2*r1.r2 + 8*p1.r2*p2.r2*r1.r2*d - 16*p1.r2*p2.r2*s12 + 4*p1.r2*
         p2.r2*d*s12 - 32*p1.r2*p2.r2^2 + 8*p1.r2*p2.r2^2*d - 16*p1.r2*r1.r2*
         s12 + 4*p1.r2*r1.r2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*
      gs^4*Nc * (  - 64*p1.r1*p2.r1*p2.r2 + 16*p1.r1*p2.r1*p2.r2*d - 32*p1.r1*
         p2.r1*r1.r2 + 8*p1.r1*p2.r1*r1.r2*d - 16*p1.r1*p2.r1*s12 + 4*p1.r1*
         p2.r1*d*s12 - 32*p1.r1*p2.r1^2 + 8*p1.r1*p2.r1^2*d - 32*p1.r1*p2.r2*
         r1.r2 + 8*p1.r1*p2.r2*r1.r2*d - 16*p1.r1*p2.r2*s12 + 4*p1.r1*p2.r2*d*
         s12 - 32*p1.r1*p2.r2^2 + 8*p1.r1*p2.r2^2*d - 16*p1.r1*r1.r2*s12 + 4*
         p1.r1*r1.r2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(p2,r2,mu95,nu95)*
      gs^4*Nc^3 * ( 64*p1.r1*p2.r1*p2.r2 - 16*p1.r1*p2.r1*p2.r2*d + 32*p1.r1*
         p2.r1*r1.r2 - 8*p1.r1*p2.r1*r1.r2*d + 16*p1.r1*p2.r1*s12 - 4*p1.r1*
         p2.r1*d*s12 + 32*p1.r1*p2.r1^2 - 8*p1.r1*p2.r1^2*d + 32*p1.r1*p2.r2*
         r1.r2 - 8*p1.r1*p2.r2*r1.r2*d + 16*p1.r1*p2.r2*s12 - 4*p1.r1*p2.r2*d*
         s12 + 32*p1.r1*p2.r2^2 - 8*p1.r1*p2.r2^2*d + 16*p1.r1*r1.r2*s12 - 4*
         p1.r1*r1.r2*d*s12 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*
      gs^4*Nc * ( 32*p2.r1*p2.r2*s12 - 8*p2.r1*p2.r2*d*s12 + 16*p2.r1*r1.r2*
         s12 - 4*p2.r1*r1.r2*d*s12 + 8*p2.r1*s12^2 - 2*p2.r1*d*s12^2 + 16*
         p2.r1^2*s12 - 4*p2.r1^2*d*s12 + 16*p2.r2*r1.r2*s12 - 4*p2.r2*r1.r2*d*
         s12 + 8*p2.r2*s12^2 - 2*p2.r2*d*s12^2 + 16*p2.r2^2*s12 - 4*p2.r2^2*d*
         s12 + 8*r1.r2*s12^2 - 2*r1.r2*d*s12^2 )

       + Prop(cut,-q,m2)*Prop(cut,r1)*Prop(cut,r2)*Prop(q + p1)^2*Prop( - p2
       - r1)*Prop( - p2 - r2)*Den(cut, - q.p1 + q.p2*u)*e_(r1,r2,mu95,nu95)*
      gs^4*Nc^3 * (  - 32*p2.r1*p2.r2*s12 + 8*p2.r1*p2.r2*d*s12 - 16*p2.r1*
         r1.r2*s12 + 4*p2.r1*r1.r2*d*s12 - 8*p2.r1*s12^2 + 2*p2.r1*d*s12^2 - 
         16*p2.r1^2*s12 + 4*p2.r1^2*d*s12 - 16*p2.r2*r1.r2*s12 + 4*p2.r2*r1.r2
         *d*s12 - 8*p2.r2*s12^2 + 2*p2.r2*d*s12^2 - 16*p2.r2^2*s12 + 4*p2.r2^2
         *d*s12 - 8*r1.r2*s12^2 + 2*r1.r2*d*s12^2 );

