id r1.r2*TOPO(30) = +1*Den(2)*TOPO(30)*DD11;
id p1.r1*TOPO(30) = +(-1)*Den(2)*TOPO(30)*DD7+Num(-u)*Den(2+2*u)*TOPO(30)*DD11+Num(-m2+m2*u*z)*Den(2*z+2*u*z)*TOPO(30)*1;
id p2.r1*TOPO(30) = +1*Den(2)*TOPO(30)*DD7+(-1)*Den(2+2*u)*TOPO(30)*DD11+(-1)*Den(2)*TOPO(30)*DD13+Num(m2+m2*z)*Den(2*z+2*u*z)*TOPO(30)*1;
id p1.r2*TOPO(30) = +1*Den(2)*TOPO(30)*DD7;
id p2.r2*TOPO(30) = +(-1)*Den(2)*TOPO(30)*DD7+1*Den(2)*TOPO(30)*DD13+Num(-m2)*Den(2*z)*TOPO(30)*1;
