id r1.r2*TOPO(41) = +Num(1+u)*Den(2*u)*TOPO(41)*DD10+Num(m2*u-m2*z)*Den(2*u*z)*TOPO(41)*1;
id p1.r1*TOPO(41) = +1*Den(2)*TOPO(41)*DD8+1*Den(2*u)*TOPO(41)*DD10+1*Den(2)*TOPO(41)*DD12+Num(-m2)*Den(2*u)*TOPO(41)*1;
id p2.r1*TOPO(41) = +(-1)*Den(2)*TOPO(41)*DD8+(-1)*Den(2*u)*TOPO(41)*DD10+Num(m2*z-m2*u)*Den(2*u*z)*TOPO(41)*1;
id p1.r2*TOPO(41) = +(-1)*Den(2)*TOPO(41)*DD8+Num(-1-u)*Den(2*u)*TOPO(41)*DD10+(-1)*Den(2)*TOPO(41)*DD12+Num(m2*z-m2*u+m2*u*z)*Den(2*u*z)*TOPO(41)*1;
id p2.r2*TOPO(41) = +1*Den(2)*TOPO(41)*DD8;
