id r1.r2*TOPO(19) = +Num(1+u)*Den(2*u)*TOPO(19)*DD6+Num(-1-u)*Den(2*u)*TOPO(19)*DD7+Num(-1-u)*Den(2*u)*TOPO(19)*DD12+Num(m2+m2*z)*Den(2*z)*TOPO(19)*1;
id p1.r1*TOPO(19) = +(-1)*Den(2)*TOPO(19)*DD6+1*Den(2)*TOPO(19)*DD12+Num(-m2)*Den(2*z)*TOPO(19)*1;
id p2.r1*TOPO(19) = +1*Den(2)*TOPO(19)*DD6;
id p1.r2*TOPO(19) = +1*Den(2)*TOPO(19)*DD7;
id p2.r2*TOPO(19) = +Num(-1-u)*Den(2*u)*TOPO(19)*DD6+1*Den(2*u)*TOPO(19)*DD7+1*Den(2*u)*TOPO(19)*DD12+Num(-m2)*Den(2*z)*TOPO(19)*1;
