id r1.r2*TOPO(38) = +Num(1+u)*Den(2)*TOPO(38)*DD9+Num(m2-m2*u*z)*Den(2*z)*TOPO(38)*1;
id p1.r1*TOPO(38) = +(-1)*Den(2)*TOPO(38)*DD7+Num(-u)*Den(2)*TOPO(38)*DD9+Num(-m2+m2*u*z)*Den(2*z)*TOPO(38)*1;
id p2.r1*TOPO(38) = +1*Den(2)*TOPO(38)*DD7+Num(u)*Den(2)*TOPO(38)*DD9+1*Den(2)*TOPO(38)*DD12+Num(-m2*u)*Den(2)*TOPO(38)*1;
id p1.r2*TOPO(38) = +1*Den(2)*TOPO(38)*DD7;
id p2.r2*TOPO(38) = +(-1)*Den(2)*TOPO(38)*DD7+Num(-1-u)*Den(2)*TOPO(38)*DD9+(-1)*Den(2)*TOPO(38)*DD12+Num(-m2+m2*z+m2*u*z)*Den(2*z)*TOPO(38)*1;
