id r1.r2*TOPO(35) = +Num(1+u)*Den(2)*TOPO(35)*DD9+Num(m2-m2*u*z)*Den(2*z)*TOPO(35)*1;
id p1.r1*TOPO(35) = +(-1)*Den(2)*TOPO(35)*DD6+1*Den(2)*TOPO(35)*DD12+Num(-m2)*Den(2*z)*TOPO(35)*1;
id p2.r1*TOPO(35) = +1*Den(2)*TOPO(35)*DD6;
id p1.r2*TOPO(35) = +1*Den(2)*TOPO(35)*DD6+Num(-u)*Den(2)*TOPO(35)*DD9+(-1)*Den(2)*TOPO(35)*DD12+Num(m2*u)*Den(2)*TOPO(35)*1;
id p2.r2*TOPO(35) = +(-1)*Den(2)*TOPO(35)*DD6+(-1)*Den(2)*TOPO(35)*DD9+Num(-m2+m2*z)*Den(2*z)*TOPO(35)*1;
