  L Had = + gv(ti)*cgv(tj)*Nc * ( 4*p1(mu95)*p2(nu95) + 4*p1(nu95)*p2(mu95) )

       + gv(ti)*cgv(tj)*d_(mu95,nu95)*Nc * (  - 2*m2 )

       + gv(ti)*cga(tj)*e_(p1,p2,mu95,nu95)*Nc * (  - 4 )

       + ga(ti)*cgv(tj)*e_(p1,p2,mu95,nu95)*Nc * (  - 4 )

       + ga(ti)*cga(tj)*Nc * ( 12*p1(mu95)*p2(nu95) - 10*p1(mu95)*p2(nu95)*d
          + 2*p1(mu95)*p2(nu95)*d^2 + 12*p1(nu95)*p2(mu95) - 10*p1(nu95)*
         p2(mu95)*d + 2*p1(nu95)*p2(mu95)*d^2 )

       + ga(ti)*cga(tj)*d_(mu95,nu95)*Nc * (  - 14*m2 + 41/3*d*m2 - 4*d^2*m2
          + 1/3*d^3*m2 );

