id r1.r2*TOPO(37) = +1*Den(2)*TOPO(37)*DD11;
id p1.r1*TOPO(37) = +(-1)*Den(2)*TOPO(37)*DD6+1*Den(2)*TOPO(37)*DD12+Num(-m2)*Den(2*z)*TOPO(37)*1;
id p2.r1*TOPO(37) = +1*Den(2)*TOPO(37)*DD6;
id p1.r2*TOPO(37) = +1*Den(2)*TOPO(37)*DD6+Num(-u)*Den(2+2*u)*TOPO(37)*DD11+(-1)*Den(2)*TOPO(37)*DD12+Num(m2*u+m2*u*z)*Den(2*z+2*u*z)*TOPO(37)*1;
id p2.r2*TOPO(37) = +(-1)*Den(2)*TOPO(37)*DD6+(-1)*Den(2+2*u)*TOPO(37)*DD11+Num(m2*z-m2*u)*Den(2*z+2*u*z)*TOPO(37)*1;
