id r1.r2*TOPO(31) = +1*Den(2)*TOPO(31)*DD11;
id p1.r1*TOPO(31) = +1*Den(2)*TOPO(31)*DD8+Num(-u)*Den(2+2*u)*TOPO(31)*DD11+(-1)*Den(2)*TOPO(31)*DD13+Num(m2*u+m2*u*z)*Den(2*z+2*u*z)*TOPO(31)*1;
id p2.r1*TOPO(31) = +(-1)*Den(2)*TOPO(31)*DD8+(-1)*Den(2+2*u)*TOPO(31)*DD11+Num(m2*z-m2*u)*Den(2*z+2*u*z)*TOPO(31)*1;
id p1.r2*TOPO(31) = +(-1)*Den(2)*TOPO(31)*DD8+1*Den(2)*TOPO(31)*DD13+Num(-m2)*Den(2*z)*TOPO(31)*1;
id p2.r2*TOPO(31) = +1*Den(2)*TOPO(31)*DD8;
