id r1.r2*TOPO(39) = +Num(1+u)*Den(2)*TOPO(39)*DD9+Num(m2-m2*u*z)*Den(2*z)*TOPO(39)*1;
id p1.r1*TOPO(39) = +1*Den(2)*TOPO(39)*DD5;
id p2.r1*TOPO(39) = +(-1)*Den(2)*TOPO(39)*DD5+1*Den(2)*TOPO(39)*DD12+Num(-m2)*Den(2*z)*TOPO(39)*1;
id p1.r2*TOPO(39) = +(-1)*Den(2)*TOPO(39)*DD5+Num(-u)*Den(2)*TOPO(39)*DD9+Num(-m2+m2*u*z)*Den(2*z)*TOPO(39)*1;
id p2.r2*TOPO(39) = +1*Den(2)*TOPO(39)*DD5+(-1)*Den(2)*TOPO(39)*DD9+(-1)*Den(2)*TOPO(39)*DD12+Num(m2)*Den(2)*TOPO(39)*1;
