id r1.r2*TOPO(16) = +Num(-1-u)*Den(2*u)*TOPO(16)*DD5+Num(-1-u)*Den(2*u)*TOPO(16)*DD7+Num(-m2+m2*u*z)*Den(2*u*z)*TOPO(16)*1;
id p1.r1*TOPO(16) = +1*Den(2)*TOPO(16)*DD5;
id p2.r1*TOPO(16) = +1*Den(2*u)*TOPO(16)*DD5+Num(1+u)*Den(2*u)*TOPO(16)*DD7+(-1)*Den(2)*TOPO(16)*DD13+Num(m2)*Den(2*u*z)*TOPO(16)*1;
id p1.r2*TOPO(16) = +1*Den(2)*TOPO(16)*DD7;
id p2.r2*TOPO(16) = +(-1)*Den(2)*TOPO(16)*DD7+1*Den(2)*TOPO(16)*DD13+Num(-m2)*Den(2*z)*TOPO(16)*1;
