id r1.r2*TOPO(18) = +Num(-1-u)*Den(2*u)*TOPO(18)*DD5+Num(1+u)*Den(2*u)*TOPO(18)*DD8+Num(-1-u)*Den(2*u)*TOPO(18)*DD13+Num(m2+m2*z)*Den(2*z)*TOPO(18)*1;
id p1.r1*TOPO(18) = +1*Den(2)*TOPO(18)*DD5;
id p2.r1*TOPO(18) = +1*Den(2*u)*TOPO(18)*DD5+Num(-1-u)*Den(2*u)*TOPO(18)*DD8+1*Den(2*u)*TOPO(18)*DD13+Num(-m2)*Den(2*z)*TOPO(18)*1;
id p1.r2*TOPO(18) = +(-1)*Den(2)*TOPO(18)*DD8+1*Den(2)*TOPO(18)*DD13+Num(-m2)*Den(2*z)*TOPO(18)*1;
id p2.r2*TOPO(18) = +1*Den(2)*TOPO(18)*DD8;
