L Had= - 2*Prop(cut,-q,m2)*gv(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*
      p2(nu95)*Nc*m2 - 2*Prop(cut,-q,m2)*gv(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2
      *u)*p1(nu95)*p2(mu95)*Nc*m2 + Prop(cut,-q,m2)*gv(ti)*cgv(tj)*Den(cut, - 
      q.p1 + q.p2*u)*d_(mu95,nu95)*Nc*m2^2 + 2*Prop(cut,-q,m2)*gv(ti)*cga(tj)*
      Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*Nc*m2 + 2*Prop(cut,-q,m2)*
      ga(ti)*cgv(tj)*Den(cut, - q.p1 + q.p2*u)*e_(p1,p2,mu95,nu95)*Nc*m2 - 6*
      Prop(cut,-q,m2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(mu95)*
      p2(nu95)*Nc*m2 + 5*Prop(cut,-q,m2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2
      *u)*p1(mu95)*p2(nu95)*Nc*d*m2 - Prop(cut,-q,m2)*ga(ti)*cga(tj)*Den(cut,
       - q.p1 + q.p2*u)*p1(mu95)*p2(nu95)*Nc*d^2*m2 - 6*Prop(cut,-q,m2)*ga(ti)
      *cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*Nc*m2 + 5*Prop(cut,
      -q,m2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*p2(mu95)*Nc*d*
      m2 - Prop(cut,-q,m2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*p1(nu95)*
      p2(mu95)*Nc*d^2*m2 + 7*Prop(cut,-q,m2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + 
      q.p2*u)*d_(mu95,nu95)*Nc*m2^2 - 41/6*Prop(cut,-q,m2)*ga(ti)*cga(tj)*Den(
      cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*Nc*d*m2^2 + 2*Prop(cut,-q,m2)*ga(ti)
      *cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*Nc*d^2*m2^2 - 1/6*Prop(
      cut,-q,m2)*ga(ti)*cga(tj)*Den(cut, - q.p1 + q.p2*u)*d_(mu95,nu95)*Nc*d^3
      *m2^2;

